### ISSUE TITLE
New Xiangqi pieces

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#10]
Not really an issue, but here is a full set of Xiangqi pieces, so that my set is not just copying from the other set used.
[XQ2.zip](https://github.com/gbtami/pychess-variants/files/3504035/XQ2.zip)

On a completely unrelated note, some English fixes for the chat:

"XXX leaved lobby" -> "XXX left the lobby."
"XXX joined to lobby" -> "XXX joined the lobby."

**Comment by gbtami** [comment]
Awesome! Thx a lot! Should I remove your previous xiangqi piece set? At this moment both are available.

English fixes are always welcome! :)

Btw. if you are interested and have some free time can you take a look at https://github.com/gbtami/pychess-variants/issues/11 and maybe https://github.com/gbtami/pychess-variants/issues/12, please? While the former seems easier the latter can be rather challenging :)
