### ISSUE TITLE
Importing finished game from brain king

### ISSUE THREAD

**Issue by CricketForJapan** [gbtami/pychess-variants#1000]
[

**Exact URL where the bug happened**https://www.pychess.org/QA6De1xB

**Steps to reproduce the bug** I imported correspondence game, but no pieces are appearing.  Analysis is not possible.

**What did you expect to happen?**  I have analysed embassy games in the past. I used same method, copy and paste from Brainking.  I just tested the older imports - https://www.pychess.org/eM1Tpqyb   these are no longer working either.

**What happened instead?**
Did not work at all.  Worked fine previously. 
**Operating system and browser version**

](https://www.pychess.org/QA6De1xB)

**Comment by gbtami** [comment]
Copy-paste the PGN you wanted to import here, please.

**Comment by CricketForJapan** [comment]
[Event "Casual Game"]
[Site "BrainKing.com (Prague, Czech Republic)"]
[Date "2022.07.08"]
[Round "?"]
[White "nstre"]
[Black "CricketForJapan"]
[Result "0-1"]
[Variant "Embassy"]
[SetUp "1"]
[FEN "rnbqkmcbnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBQKMCBNR w KQkq - 0 1"]

1. e4 b6 2. i3 Nc6 3. Bi2 Bb7 4. Nc3 e6 5. b3 Qf6 6. Bb2 O-O 7. f3 Qj6+
8. Af2 i5 9. j4 Qi7 10. jxi5 g5 11. h4 Bd4 12. Ah3 Ae7 13. g3 Ng7 14. Qe2 Nh5
15. Ng2 Rg8 16. g4 Nf6 17. Aj5 Qh8 18. Ah6 Cd8 19. Axj7 Qg7 20. Ah6 Qh8
21. hxg5 Ne8 22. f4 Ab4 23. a3 Axc2# 0-1

**Comment by gbtami** [comment]
We changed Embassy to be Capablaca with specific start FEN. It is no longer a standalone variant on pychess.
Thx for reporting this bug!
