### ISSUE TITLE
King incorrectly highlighted in imported game when visiting through link to starting position in analysis board

### ISSUE THREAD

**Issue by kezsulap** [gbtami/pychess-variants#1002]
https://www.pychess.org/BN9tYX0u?ply=0
![Screenshot from 2022-09-16 01-05-18](https://user-images.githubusercontent.com/16389252/190523765-ac01d985-b98e-4e6f-8256-23d58aea580b.png)

**Comment by kezsulap** [comment]
Also there's some random highlight of the previous move

**Comment by gbtami** [comment]
Possible related to https://github.com/lichess-org/chessground/issues/243
