### ISSUE TITLE
Empire game glitched, did not note checkmate

### ISSUE THREAD

**Issue by kthejoker** [gbtami/pychess-variants#1021]
https://www.pychess.org/quHLGKW2

Steps to reproduce:

Played checkmating move in Empire variant.

Expected behavior:

Engine declares checkmate.

Actual behavior:

Engine gave move to black, but black is unable to move (because checkmate) so timer for black is just running down.

![image](https://user-images.githubusercontent.com/625949/199044541-221b0c5b-98a5-4298-ac44-08caa7aa98d9.png)

**Comment by kthejoker** [comment]
to be fair, when I refreshed the page it correctly showed the checkmate, so it was just a glitch within the client.

**Comment by gbtami** [comment]
Possible just connection issue.
