### ISSUE TITLE
Add Futuristic sounds

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [gbtami/pychess-variants#1026]
I created my sounds of shogisnap and shogislam, other sounds – add please.

**Comment by gbtami** [comment]
Create PR, please.

**Comment by gbtami** [comment]
Where are the files?

**Comment by Rechefiltr-is-Fire** [comment]
In PR

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/0508c5f1a8aab65406a043eea2b3e4119308e8bc
