### ISSUE TITLE
Incomplete FEN validation in editor 

### ISSUE THREAD

**Issue by kezsulap** [gbtami/pychess-variants#1027]
![Screenshot_20221105_152953](https://user-images.githubusercontent.com/16389252/200113225-a8511fe7-f137-4f94-8d53-dcbdf7a4f714.jpg)
The only thing is checked is if both sides have exactly one king each, it allows to go to analysis's board/challenge window if the side to move is checking enemy king

**Comment by Fulmene** [comment]
The FEN validation is not meant to be complete. If it doesn't allow server-crashing positions then it's fine. It can allow illegal positions all it wants.
