### ISSUE TITLE
Keep Rematch even after analysis?

### ISSUE THREAD

**Issue by notruck** [gbtami/pychess-variants#103]
Jarl asked on Discord: "Would it be possible to keep the rematch button there after analysis?"

Also, it'd be nice if the [analysis board] button can be opened in a new tab/window, like on Lichess.

**Comment by gbtami** [comment]
There is no rematch button in analysis on lichess and also analysis is opening in the same tab. Fix me if I'm wrong.
I like pychess behavior to be the same as lichess as much as possible.

**Comment by gbtami** [comment]
Btw. analysis board is opening in the same tab on lichess for me.
On the other hand players get playing page of particular game by default (with rematch button) not the analysis page.
