### ISSUE TITLE
Allow the circle piece set to be available for the fairy piece set variants.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#1030]
The black and white circle piece set should be made available for all of the variants in the Fairy Piece variants group except Shogun. This means Shako, Grand, Seirawan, and Hoppel Poppel. The only exception would be Shogun since these need piece promotion pieces.

**Comment by gbtami** [comment]
I started to add it to all variants gradually.

**Comment by gbtami** [comment]
Done via https://github.com/gbtami/pychess-variants/commit/7f7ec1b1967262416c4391f9b671e4f9c497ce91
