### ISSUE TITLE
Toggle Check sound separately from other sounds?

### ISSUE THREAD

**Issue by notruck** [gbtami/pychess-variants#104]
This one is also from Jarl: "is it possible to not have the computer announce check without turning off sound altogether?"

**Comment by gbtami** [comment]
This needs configurable sounds. In pychess (desktop app) we have that.
![http://i.imgur.com/EFTFho7.png](http://i.imgur.com/EFTFho7.png)

**Comment by gbtami** [comment]
Changed sound theme back to lichess "standard" one. (I used "robot" before.)
