### ISSUE TITLE
Incomplete crazyhouse960 game

### ISSUE THREAD

**Issue by ianfab** [gbtami/pychess-variants#106]
https://pychess-variants.herokuapp.com/skUuhtcm shows an incomplete game. I am suspecting the next move might have been a castling move, but I do not know. The profile page https://pychess-variants.herokuapp.com/@/shuvashish76 shows a different final position.

**Comment by gbtami** [comment]
I don't know what happened here. Maybe a temporary mongodb issue.
Anyhow it is ok now. (I did nothing.)
