### ISSUE TITLE
Variant - Shogun chess

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#107]
Requesting a variant for shogun chess :)

Rules:

-Starting positions unchanged from standard chess.

-Based on Crazyhouse, but with the additional rule that promotions happen at the 6-8th ranks, so pieces can only be dropped in the first 5 ranks.

-Every piece (including the Pawn) can promote to one piece except the King, just like in Shogi. 

-Pawn -> Captain (C) = moves just like a King.
-Knight -> General (G) = Knight + King (Centaur)
-Bishop -> Archbishop (A) = Bishop + Knight (Princess)
-Rook -> Mortar (M) = Rook + Knight (Empress)
-Duchess (D) -> Queen. Duchess moves like a Ferz.

-Each player can only have one of each super piece (Q, G, A, M) can be out at a time. For example, if an archbishop is out in play, then there should be no option for promotion when a bishop promotes.

-Like Shogi, an unpromoted piece can promote if it starts its move in a promotion zone. This should be much rarer than Shogi because you can't drop in a promotion zone.

Variants.ini configuration:

# Shogun
[shogun:crazyhouse]
ferz = d
archbishop = a
chancellor = m
commoner = c
centaur = g
promotionRank = 6
promotionLimit = a:1 m:1 g:1 q:1
promotionPieceTypes = c
promotedPieceType = r:m b:a n:g d:q
pocketSize = 5

Pieces are attached. Pieces that aren't included in the zip are their default Merida style. The Archbishop uses the wAr.svg and bAr.svg files.

[Shogun Pieces.zip](https://github.com/gbtami/pychess-variants/files/4025974/Shogun.Pieces.zip)

Boards are also attached.

[Shogun Boards.zip](https://github.com/gbtami/pychess-variants/files/4025975/Shogun.Boards.zip)

**Comment by ianfab** [comment]
As far as I can see there are two issues with the config:
* Fairy-SF uses the spelling "fers", not "ferz".
* If the queen in the starting position is supposed to be a promoted fers, the start FEN needs to use +D/+d instead of Q/q, otherwise the queens will not be demoted to a fers when being captured.

Furthermore some questions for clarification:
* Does "so pieces can only be dropped in the first 5 ranks" only refer to pawns or all pieces? If the latter, then whiteDropRegion/blackDropRegion need to be defined accordingly. The exclusion of the promotion zone from the drop region only applies to pawns.
* Did you drop the capture the flag win rule regarding squares d1/e1/d8/e8?

**Comment by CouchTomato87** [comment]
Thanks for the proofreading! Yes, the promotion zone applies to all pieces. And yes, the capture the flag rule is not needed because there are drops (so stalemate is super rare). If I went with no drops, I would've kept that.

**Comment by Little-Magician** [comment]
# Tomatogun 
[shogun:crazyhouse]
startFen = rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
pieceToCharTable = PNBRQS.AM.C.........G++++.+................Kpnbrqs.am.c.........g++++.+................k
fers = s
archbishop = a
chancellor = m
commoner = c
centaur = g
promotionRank = 7
promotionLimit = a:1 m:1 g:1
promotionPieceTypes = c
promotedPieceType = r:m b:a n:g s:q

**Comment by gbtami** [comment]
Shouldn't startFen have to be
 rnb+fkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNB+FKBNR[-] w KQkq - 0 1
instead? I mean you can forget what works or not works in Winboard here. This is for Fairy-Stockfish only!

**Comment by CouchTomato87** [comment]
Yeah, and the symbol is D, not F

**Comment by CouchTomato87** [comment]
One additional line to be added:

firstRankPawnDrops = true

**Comment by CouchTomato87** [comment]
I totally forgot the archbishops had to be colored to like the rest of the promoted pieces, so here they are: 
[Shogun As.zip](https://github.com/gbtami/pychess-variants/files/4048640/Shogun.As.zip)
