### ISSUE TITLE
Request for adding byo-omi time option for all games listed in Pychess. 

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#1078]
I’m wondering what is the problem with adding byo-omi time as an option for games played? It’s similar to Bronstein time but simply gives each player an exact amount of time she or he has to input a move otherwise the game is logged as a loss for the player who fails to make a move within 30 seconds.

**Comment by gbtami** [comment]
It has nearly 0 benefit and just complicates the GUI
