### ISSUE TITLE
Option to show tiny blue dots on Shogi pieces to show piece movement

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#1082]
I’ve seen this option on iPhone shogi apps that allow you to turn on blue dots on the shogi pieces to show where a piece is able to move. This becomes especially useful when trying to figure out which of the generals you can use for a particular move because each one has its weaknesses and it’s hard to remember which one can move back or diagonally. Having this feature makes it easier to figure out which general to use and also helps locate the pieces you want to move more easily. The bishop and the rook look similar unless you’re really good at figuring out the kanji piece symbol but having the blue dots on the piece to locate which direction it can move makes this easier to see. Gbtami, please consider it as it’s a visual improvement to help players who want to use the Japanese kanji pieces learn to using the pieces without being forced to convert to the international sets.

**Comment by gbtami** [comment]
We already have "tiger striped" pieces.
![https://i.imgur.com/khhjhco.png](https://i.imgur.com/khhjhco.png)

**Comment by gbtami** [comment]
Also ![https://lichess.org/HlLOOWDr/black](https://lichess.org/HlLOOWDr/black)
