### ISSUE TITLE
Fluidity Chess

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [gbtami/pychess-variants#1096]
Since this variant is currently not submitted by Chess Variants Pages, _**it's still a draft**_. So CVP editors have made interactive diagram for it.

**Comment by Rechefiltr-is-Fire** [comment]
It can be on Lichess, but Thibault is more conservative even than you)

**Comment by gbtami** [comment]
Is it supported by FairyStockfish?

**Comment by Rechefiltr-is-Fire** [comment]
How to embed this in FairyStockfish? (sorry by my counterquestion)

**Comment by gbtami** [comment]
See here https://github.com/fairy-stockfish/Fairy-Stockfish/wiki/Variant-configuration
