### ISSUE TITLE
Merida archbishop and cancellor

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#11]
At this moment A and C in Capa variants are Cburnett pieces from https://commons.wikimedia.org/wiki/Category:SVG_chess_pieces
They are looking strange/alien between Merida pieces.
It would be cool to have some new Merida style A and C.

**Comment by CouchTomato87** [comment]
I can tackle this, no problem.

Responding to your question in the other issue for XQ, you can delete my other set. To me, it was kind of "incomplete" anyways.

As for sittuyin, I'm not sure if I can contribute yet or not. A full set is a bit of work, and it's a game that doesn't seem to be very popular, even in its own country. Between the set you already have from Makruk and maybe a set using common western chess pieces, I'm guessing that would make most people happy? If it's more popular though, I can devote some time to it.

**Comment by gbtami** [comment]
Thx a lot!
Agreed on sittuyin. Merida A+C seems much more useful at this moment.

**Comment by CouchTomato87** [comment]
Would you prefer pieces that are more unique like as in https://www.houseofstaunton.com/musketeer-chess-chancellor-and-archbishop-kit-camaratta-kit.html

Or do you want to go with the chimera-like pieces you have now?

**Comment by gbtami** [comment]
If one like to use unique pieces we already have Hawk and Elephant you created before.
Btw you can toggle A+C vs H+E in Seirawan, Shouse, Capablanca and Capahouse games now!

In Merida set I prefer to go with chimera-like pieces because they are well known and can help recognize how they are moving. I would like if their upper and lower parts where composed from the corresponding Merida pieces somehow, not from Cburnett.

**Comment by CouchTomato87** [comment]
Okay, here they are
[MeridaCapablanca.zip](https://github.com/gbtami/pychess-variants/files/3511462/MeridaCapablanca.zip)

**Comment by gbtami** [comment]
Thx a lot! Will try them soon.

**Comment by gbtami** [comment]
May I ask some little correction?
1. The new A and C should be same tall as Knight, Bishop and Rook.
2. They should be vertically aligned the same also.
3. The bottom of A should be same wide as Bishop bottom
4. The bottom of C should be same wide as Rook top!
Sry for the nitpicking.

I imagine something like Cburnett in cutechess just cooked from Merida ingredients :)
![Cburnett](https://user-images.githubusercontent.com/479964/63295884-169dc280-c2ce-11e9-8267-7f88ed9a40fd.png)

**Comment by gbtami** [comment]
I'v added your new Merida pieces as additional choice in Capablaca (but only for Capablanca!) to the site to let you see what I'm talking about.
![Merida1](https://user-images.githubusercontent.com/479964/63297779-75653b00-c2d2-11e9-935b-a12523af5cdb.png)

**Comment by CouchTomato87** [comment]
Okay, I can do that. Although note that the rook top in the chancellor is not the same size as the actual rook's

**Comment by CouchTomato87** [comment]
Alright, here they are. I kept the rook top the same :)
[MeridaCapa2.zip](https://github.com/gbtami/pychess-variants/files/3518281/MeridaCapa2.zip)

**Comment by CouchTomato87** [comment]
Also as a bonus, I updated the Hawk and Elephant (yet again). Did a little recoloring to match Merida more, and also resized and repositioned 
[SPiecesAgain.zip](https://github.com/gbtami/pychess-variants/files/3518469/SPiecesAgain.zip)
them to match a little better.

**Comment by gbtami** [comment]
Thx a lot!
Just noticed that in black achbishop .svg some garbage is shown. Maye remaining curves from knight you used.
![bA](https://user-images.githubusercontent.com/479964/63330396-0e786e00-c334-11e9-93d8-29d3acbfb27b.png)

**Comment by gbtami** [comment]
Fixed it.
