### ISSUE TITLE
Spartan pawn is incorrect 

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [gbtami/pychess-variants#1104]
The Hoplite in merida set seems very outstyle, I can draw another image today

**Comment by gbtami** [comment]
The Spartan chess piece set was created with the agreement of several people including the variant author.
If you want to create another piece set, it is welcome of course.

**Comment by gbtami** [comment]
Btw he pasted a 3D set on Discord as well.
![https://cdn.discordapp.com/attachments/702842849384988742/1089981527233933332/The_Spartans.jpg](https://cdn.discordapp.com/attachments/702842849384988742/1089981527233933332/The_Spartans.jpg)

**Comment by Rechefiltr-is-Fire** [comment]
![bP spartan](https://user-images.githubusercontent.com/101206332/229272302-86abb4eb-c2ad-4ee9-929e-5efa9ad3ad13.svg)
