### ISSUE TITLE
Doubutsu set

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [gbtami/pychess-variants#1118]
Sorry by my sparkling ideas. It seems ideal for this variant.
![wF dobutsu](https://user-images.githubusercontent.com/101206332/231855284-e57d6a7c-703b-4f30-99f2-c3e4e247ab3d.svg)
![bF dobutsu](https://user-images.githubusercontent.com/101206332/231855330-bc09aabb-e5e4-4a9a-bc87-ea766b320a44.svg)
![wW dobutsu](https://user-images.githubusercontent.com/101206332/231855362-01216f48-8dc9-42a4-9b0a-1a2a498d62d1.svg)
![bW dobutsu](https://user-images.githubusercontent.com/101206332/231855395-8a31226e-cca7-4056-a8ae-0dda7bae4840.svg)
![wP dobutsu](https://user-images.githubusercontent.com/101206332/231855426-0b9f18ad-157c-406a-b5b0-bb154f8ad039.svg)
![bP dobutsu](https://user-images.githubusercontent.com/101206332/231855468-0068af9d-6e8d-439e-82e0-a139493abab0.svg)
![wG dobutsu](https://user-images.githubusercontent.com/101206332/231855500-ce776b72-88c3-4682-bd07-8db04cc9ce36.svg)
![bG dobutsu](https://user-images.githubusercontent.com/101206332/231855545-63b542f4-6f77-4791-9f7c-4df9ac21f123.svg)
![wK dobutsu](https://user-images.githubusercontent.com/101206332/231855579-3152c43d-648d-4bf1-9cee-7793c720a5b6.svg)
![bK dobutsu](https://user-images.githubusercontent.com/101206332/231855611-a87de1a6-9524-4b3f-aaed-391487a0d99a.svg)

**Comment by gbtami** [comment]
This set seems OK, except the colors  you used. They are rather random now.

**Comment by gbtami** [comment]
May I ask you to consult with other pychess devs on our Discord please? https://discord.gg/aPs8RKr
