### ISSUE TITLE
Duplicating seek requests

### ISSUE THREAD

**Issue by nnickoloff1234** [gbtami/pychess-variants#1120]
Steps to reproduce:
1. Log in with some user
2. In the lobby create some seek
3. Open a second tab in the same browser
4. You should see the same seek in both tabs at this point
5. disconnect your internet connection and wait a bit
6. Reconnect and wait until either of the tabs reconnects and refreshes the list of seeks and you will see the seek is now duplicated

![image](https://user-images.githubusercontent.com/2179288/232145501-b96b9208-70c6-4169-95f9-745e732bfabd.png)

Expected behavior:
I guess either the seek should have been preserved and should be still just a single one, or it should have been canceled by server and not recreated

**Comment by nnickoloff1234** [comment]
Off the top of my head, My gut feeling tells me storing seeks clientside and resending them feels like bad approach, but haven't thought about it much. But my first idea would be to not rely on client for storing this kind of state at all, but only have them on server. Maybe instead of deleting them right away on websocket disconnect, just mark them as disconnected and delete them certain timeout after that event if no reconnect happened if we want to handle some sporadic shortterm disconnects, I don't know.

**Comment by gbtami** [comment]
@nnickoloff1234 can you test my fix on https://pychess-variants-dev.onrender.com/ please?

**Comment by gbtami** [comment]
Or even better on your dev bug server.
