### ISSUE TITLE
Cut off move list in analysis page

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#114]
https://pychess-variants.herokuapp.com/WcV18AW1
![http://i.imgur.com/tpqiXS1.png](http://i.imgur.com/tpqiXS1.png)

**Comment by gbtami** [comment]
pepellouYesterday at 1:28 PM
I started the previous game and after 4 moves I went back to the lobby and started this game (I think the previous one had to still be running by that moment)
the strange thing is right after playing the game I went to the analysis and it was fine
only now, 30 min later, I decided to check again, and there's the bug there

**Comment by ianfab** [comment]
Sounds similar to https://github.com/gbtami/pychess-variants/issues/106. And similar as there, time solved the issue, but still a bit mysterious.

**Comment by gbtami** [comment]
Seems this is a regression caused by https://github.com/gbtami/pychess-variants/commit/6c8cf13a49f7be3c37eac57572b79b3eba6436d3
When games are not in `app["games"]` dict `load_game()` creates  a new `Game`, but in this special case with new initial FEN!
