### ISSUE TITLE
Need a good formula of delay from time control

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#115]
Fumitoks Today at 11:36 AM
i'd say m+n is a good start
for m+n time control :slight_smile:
maybe times 2
or 3m+n
something like that
that's in seconds
so for 5+5 you have 20 seconds
and for 90+30 5 minutes

gbtami Today at 11:37 AM
and for 1+0 only 3s?

Fumitoks Today at 11:38 AM
3s is 5% of your whole time
but you can also do a minimum cap of 10 seconds

**Comment by CouchTomato87** [comment]
I'm confused about what the request is

**Comment by gbtami** [comment]
Pychess gives 5 min per player to make first move now, and this is independent from variant or time control of the game. The suggestion is to make it depend on time control, because in 960 games white has only 5 min to study the starting position while black can have (in worst case) 10 min, and this is not fair. (Clocks starts after black first move!)
