### ISSUE TITLE
iPad Pro 12.9 third generation displays graphics in pixelation mode for Shogi sets.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#1154]
I’m noticing an issue that i’m not sure can be addressed when viewing content at Pychess.org when playing Shogi but I’m noticing a problem when using the iPad Pro 12.9 third generation. Admittedly this is an old model but I just wanted to let you know i’ve noticed pixelation on the Shogi sets when viewed on the iPad Pro 12.9 third generation. Further investigation has revealed my iPhone 14 Pro Max has a far denser pixel count display technology allowing it to show sites with ultra sharp quality. This explains why the same Shogi graphics that look pixelated on my old iPad Pro 129 third generation model look incredibly sharp on my iPhone 14 Pro Max. But still, I’m asking whether or not there’s a “solution” other than purchasing a new iPad Pro to fix this problem. Is there anything you guys can do to help my poor old iPad Pro third generation to see better?

**Comment by gbtami** [comment]
Is this problem occurs on lishogi.org and on lichess.org as well?
If "yes", then possible we can't solve it as well. But if "no", maybe someone can borrow their solution to pychess.

**Comment by Curious2021** [comment]
Gbtami, I did a display test using my iPad Pro third generation and I noticed no issues when viewing the Shogi sets when zooming in. Picture quality is sharp and clean. This issue is localized to viewing the Shogi sets on Pychess.org.

**Comment by gbtami** [comment]
The thing is I have no Apple device at all, so we have to wait for someone who can help to solve this issue.
Until then can you provide some more info please? OS, browser version, and a screenshot if possible.
Thx.

**Comment by Curious2021** [comment]
Ipad OS 16.5.1, Safari 15.1.

**Comment by gbtami** [comment]
Wait a min. What piece set is this? Some of them are not .svg but .png!

**Comment by Curious2021** [comment]
Bingo. That’s the issue right there. SVG is the correct format. PNG is not. And guess which one is not SVG…the international set.

**Comment by gbtami** [comment]
We have two Portella Shogi .png set borrowed from lishogi site. One kanji and internationalized. 
You can choose another (.svg) piece set on this device to avoid pixelation.
