### ISSUE TITLE
Site doesn’t work on iOS or unlogged device

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [gbtami/pychess-variants#1162]
**Exact URL where the bug happened**:
https://www.pychess.org/

**Steps to reproduce the bug**
Open Pychess.
**What did you expect to happen?**
You see that normally and can do anything.
**What happened instead?**
You see only high rank, ||| button in the left and loop of search don’t react — you can only click on your acc and see your rating in the variants.
If I go to non-mobile version (with high rank words instead of one button), it lets to read variants, blog, play memory, watch library videos, see players’ page, tourneys’ and shields’ winners, profile pages of players (incl. me) and patron page😁 — all what isn’t related to board and games.
**Operating system and browser version**
iPhone SE, iOS version 14.8.1, Safari version фиг её знает.

If this is just on my phone, I close that.

https://share.icloud.com/photos/0ccshL2jvArlV3XVj8LuAj80g

**Comment by gbtami** [comment]
Is it OK with Chrome?

**Comment by Rechefiltr-is-Fire** [comment]
I will answer tomorrow…

**Comment by Rechefiltr-is-Fire** [comment]
UPD: I checked Pychess on Yandex Browser, but results is same.

**Comment by gbtami** [comment]
Maybe your ISP/country restricts something pychess needs?
I tried on my son's iPhone 13 Pro, Safari and it worked OK.

**Comment by Rechefiltr-is-Fire** [comment]
> Maybe your ISP/country restricts something pychess needs?

I don’t know, but on Windows on my laptop it works normally.

**Comment by Rechefiltr-is-Fire** [comment]
however, https://github.com/gbtami/pychess-variants/issues/1194#issuecomment-1677902309

**Comment by gbtami** [comment]
Don't spam real issues with unrelated stuff, please.
Thx.

**Comment by Rechefiltr-is-Fire** [comment]
New info: site pychess.org doesn't work on Microsoft Edge also (connection isn't safe, http:// protocol lets me watch anything without board/games/tourneys as it was on my iPhone since July. Protocol https:// for this site is being blocked by browser)

**Comment by gbtami** [comment]
Possible your computer/OS/browser is not configured correctly, or your ISP blocks something.
At least other users from Russia doesn't reported issues.
