### ISSUE TITLE
Two click drop doesn't save

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#117]
My preference for two click drop has to be clicked every single new game

**Comment by gbtami** [comment]
Works for me. Can you attach a screenshot when you set it and another one how it looks like when it doesn't work please?

**Comment by CouchTomato87** [comment]
![No two move click](https://user-images.githubusercontent.com/52322435/72686418-8e148f80-3ac2-11ea-9250-93bb7ed3c258.png)

![No two click 2](https://user-images.githubusercontent.com/52322435/72686420-9076e980-3ac2-11ea-8e07-27b012ac135e.png)

**Comment by CouchTomato87** [comment]
I played one whole game and won at the top. I pasted a screenshot over in the second image, so sorry for the mess, but in the rematch, the option was gone again.

**Comment by gbtami** [comment]
Test it, please!
