### ISSUE TITLE
YouTube Links for Explanation Pages

### ISSUE THREAD

**Issue by CricketForJapan** [gbtami/pychess-variants#1196]
https://www.youtube.com/watch?v=WmMw97hp8C0

https://www.pychess.org/variants/asean

This explanation page should have link to the video on youtube from pyshcess.

**Comment by gbtami** [comment]
Thx. Fixed via https://github.com/gbtami/pychess-variants/commit/72a5a3ae9372fe0578f8f159e16e98ef809ebc38
