### ISSUE TITLE
Pychess down

### ISSUE THREAD

**Issue by tititogepi** [gbtami/pychess-variants#1204]
**Exact URL where the bug happened**
https://www.pychess.org/
**Steps to reproduce the bug**
Just copy the link on edge, chrome...
**What did you expect to happen?**
Pychess homepage should appear
**What happened instead?**
"Application error" appear
**Operating system and browser version**
Edge, Chrome, lastest version

**Comment by gbtami** [comment]
Yes :(
see https://discord.com/channels/634298688663191582/634298688663191584/1142168010564587620

**Comment by gbtami** [comment]
This is not related to our code base.

**Comment by tititogepi** [comment]
Oh okay :(
