### ISSUE TITLE
Please update the Vietnamese translation

### ISSUE THREAD

**Issue by M-DinhHoangViet** [gbtami/pychess-variants#1214]
I translated on Transifex yesterday but still haven't seen the update

**Comment by gbtami** [comment]
This is great! Thx a lot!
Updates from transifex to github are not automatic. I did it rn. You can test it on https://pychess-variants-dev.onrender.com/ (You may have to wait some minutes to wake it up though.)
After next server restart (around midnight CET) it will be deployed to production server as well.

**Comment by M-DinhHoangViet** [comment]
Thanks
