### ISSUE TITLE
List of variants possible on Pychess

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [gbtami/pychess-variants#1227]
This kind of list is already done in Lichess’ repo in mid-2010s _**and still not closed**_, so (not in near future, but in a range of two years maybe):

- [ ] Bughouse Chess
- [ ] Faceoff Chess
- [ ] Dove Chess
- [ ] Kamil Shatranj X
- [ ] Knightmate
- [ ] Kinzoku
- [ ] 5-check Chess
- [ ] Fluidity Chess
and you can add more…

**Comment by gbtami** [comment]
Bughouse chess is under development already. Others are not planned.
