### ISSUE TITLE
Disable draw offer/resign before game starts

### ISSUE THREAD

**Issue by shuvashish76** [gbtami/pychess-variants#1242]
Lichess grayed out those options for correspondence games 👇🏿
![2023-11-12_12-40](https://github.com/gbtami/pychess-variants/assets/48226312/ed3076fe-cee9-476e-8581-e754cf6c1259)

Pychess correspondence game 👇🏿
![2023-11-12_12-42](https://github.com/gbtami/pychess-variants/assets/48226312/2048f44a-9085-4eb3-b181-7a0a790afa5d)

**Comment by shuvashish76** [comment]
https://www.pychess.org/4jy5kgBP (PAGE NOT FOUND)

Clicking on "abort" leads to a loss of game & I got a notification for that which seems unnecessary.

**Comment by shuvashish76** [comment]
Another game where my opponent aborted
![2023-11-12_19-25](https://github.com/gbtami/pychess-variants/assets/48226312/d6d70a80-3dca-4723-8555-70c41fb9b8bd)
https://www.pychess.org/c75uIKqF

**Comment by gbtami** [comment]
Fixed already in https://github.com/gbtami/pychess-variants/commit/473276422d853bbfee8c978b4e3d146d885255c8
