### ISSUE TITLE
FEN & PGN lists colours wrong way around in shogi

### ISSUE THREAD

**Issue by CricketForJapan** [gbtami/pychess-variants#1262]
https://www.pychess.org/zULI68yn?ply=1

FEN & PGN lists Watford as white.  However black goes first in Shogi.  This is an error in the square brackets, they should be opposite way around.

[Event "PyChess rated game"]
[Site "https://www.pychess.org/zULI68yn"]
[Date "2023.11.19"]
[Round "-"]
[White "watford"]
[Black "SteveatKurihara"]
[Result "0-1"]
[TimeControl "120+1"]
[WhiteElo "1420?"]
[BlackElo "1790?"]
[Variant "Shogi"]
[FEN "lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL[-] w 0 1"]
[SetUp "1"]

1. Pc4 Pg6 2. Gc2 Pf6 3. Sd2 Pg5 4. Sf2 Rg8 5. Pe4 Kd8 6. Sde3 Rg6 7. Sd4 Pf5 8. Sfe3 Gfe8 9. Pe5 Ng7 10. Ph4 Sg8 11. Kd1 Pi6 12. Pc5 Bi7 13. Gd2 Sf7 14. Sd5 Pd6 15. Sc4 Sc8 16. Pi4 Sd7 17. Li3 Gf8 18. Gg2 Sf6 19. Ri2 Pg4 20. Pi5 Pxg3=G 21. Gxg3 P@g4 22. Gh3 Pg3=G 23. Gxg3 Bxe3=H 24. Gxe3 Pxi5 25. B@b8 Gc9 26. Bxa9=H S@g4 0-1

**Comment by gbtami** [comment]
No. Pychess (and Fairy-Stockfish when it uses UCI protocol every variant, including Shogi) uses FEN,not SFEN.
