### ISSUE TITLE
Unable to drop Pheasants in Tori Shogi

### ISSUE THREAD

**Issue by entelodonts** [gbtami/pychess-variants#1270]
[**Exact URL where the bug happened**]
first encountered here (https://www.pychess.org/GyGSFMjb) (~01:00 UTC Dec. 24)
was able to replicate here: https://www.pychess.org/PGy0mBFs
and here: https://www.pychess.org/analysis/torishogi

Bug was not present in this game: https://www.pychess.org/0z0teDXV (~10:00 UTC Dec. 23)
**Steps to reproduce the bug**
1. Get pheasant in hand in a game or analysis board for Tori Shogi
2. Attempt to place pheasant in position where it is legal

**What did you expect to happen?**
Clicking on Pheasant would highlight legal squares to place Pheasant
**What happened instead?**
Nothing - was able to select pheasant, but no highlighted squares appeared. Clicking on legal destination produced no result.
**Operating system and browser version**
first encountered on Google Chrome Version 120.0.6099.129 (64-bit)
updated to Version 120.0.6099.130 (Official Build) (64-bit), issue persisted.
replicated on Firefox 121.0 (64-bit)
and Brave Version 1.61.109 Chromium: 120.0.6099.144 (Official Build) (64-bit)
OS: Windows 10 Executive
Note: issue persists while logged out and clearing cache does not fix issue.

what I see
![image](https://github.com/gbtami/pychess-variants/assets/152752619/cdbd5cea-0e77-47b6-a492-26723056a523)
selecting the pawn for comparison (what I expect to see)
![image](https://github.com/gbtami/pychess-variants/assets/152752619/0d5c6a5b-4cb5-405c-bf6e-363f9b4af417)

**Comment by PraseodymiumSpike** [comment]
https://github.com/gbtami/pychess-variants/issues/1269

**Comment by entelodonts** [comment]
I'm having the issue with games other than Tori Shogi.
It's also not possible to drop pawns in Shogi, Kyoto Shogi, and Crazyhouse. 
Doubutsu shogi is fine though, so my guess is it's affecting pieces called 'p' in the FEN.
