### ISSUE TITLE
taking back a move breaks available moves listed on ui in Ataxx

### ISSUE THREAD

**Issue by Ralgun** [gbtami/pychess-variants#1280]
After taking back a move I was unable to play moves that were there before.

**Exact URL where the bug happened**
For example [here](https://www.pychess.org/vkgadT1r?ply=0). As far as I can tell it only affects the client.
![image](https://github.com/gbtami/pychess-variants/assets/44000325/62681d2a-b92b-4b89-a9ad-c466b55f0747)

**Steps to reproduce the bug**
1. Start a game of Ataxx (I've played against a bot and other options didn't seem to affect this bug).
2. Wait for your turn and then play any two-step move.
3. Request takeback
4. Click on the piece you've moved in your retracted move and you will only see two-step moves.

**What did you expect to happen?**
Clicking on the piece should show missing moves.
![image](https://github.com/gbtami/pychess-variants/assets/44000325/48f00da4-d5da-4d7f-9abb-badc6dff53a5)

**What happened instead?**
Some moves were missing.
![image](https://github.com/gbtami/pychess-variants/assets/44000325/275e3c57-ff3e-4cdf-9c9e-8d1fb0387c1a)

**Operating system and browser version**
Windows 10, latest Chrome

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/6ae2fe8a46dc4510dbd8eb201c45a2ed1ecedbc2
