### ISSUE TITLE
Warn in Chat before Server Restart

### ISSUE THREAD

**Issue by PraseodymiumSpike** [gbtami/pychess-variants#1285]
In the Chess.com variant section, before a server restart, it says that the server is going to restart in 1 minute or something. At least, it used to; I haven't played there in a while. This message is sent to every chat, even the individual game chats. I think we should also have this feature so people aren't surprised. Also, it should bring you back to the homepage before the restart instead of just leaving you hanging in the game.

**Comment by PraseodymiumSpike** [comment]
Also, there should be an option to continue the game with the remaining time.

**Comment by gbtami** [comment]
We have the server restart warning message as well.
