### ISSUE TITLE
Broken notification links while not on main page  

### ISSUE THREAD

**Issue by kezsulap** [gbtami/pychess-variants#1293]
![image](https://github.com/gbtami/pychess-variants/assets/16389252/88251b3d-a12a-4c5e-b9da-42b051e12598)

Instead of going to the actual game URL i.e. https://www.pychess.org/Aa58WJgV it goes to https://www.pychess.org/puzzle/Aa58WJgV when I'm on the puzzle site, https://www.pychess.org/analysis/Aa58WJgV when I'm at https://www.pychess.org/analysis/chess etc.

**Comment by gbtami** [comment]
Thx. This was already fixed in https://github.com/gbtami/pychess-variants/commit/fb17e26febdbf535609688e2a97093f2bc91f5b5
Just was not deployed yet.
