### ISSUE TITLE
1. Correspondence game problem,   2. Application cannot be installed

### ISSUE THREAD

**Issue by Renifero** [gbtami/pychess-variants#1309]
**First issue**
I can't play correspondence games with the computer. It does not work:

I click
**PLAY WITH AI**
then
**TIME CONTROL->CORRESPONDENCE**
I set **DAYS PER TURN** for example 2 days.

And it doesn't work, the game starts in **REAL TIME**, after interrupting the game for a few minutes it gives me a message that the game has been abandoned. You can't play by correspondence. I don't know what it's like when playing with an opponent or if the problem is the same because I haven't checked.

**Second issue**
You cannot install the application from the website on an Android phone, such as lishogi.org or playstrategy.org.
In lisogi.org and playstrategy.org, go to the website (on your phone) and click on the drop-down list in the upper right corner - the three dots symbol, and then click install the application.

**Comment by gbtami** [comment]
Correspondence games with AI is not supported. It is kind of meaningless.
The meaning of corr chess is to let people play each other when they live in different TZ or their free time is not overlapped, so they don't have to be online at the same time to play. AI is always (0-24) there to play  with.
