### ISSUE TITLE
Alert dialog buttons need 2 clicks to Cancel/Ok

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#1311]
Here:
![https://i.imgur.com/zj1AJg7.png](https://i.imgur.com/zj1AJg7.png)

**Comment by randompearl-stack** [comment]
https://github.com/gbtami/pychess-variants/blob/7712e88c93ae1cc12b79f9eed18330d297898405/client/lobby.ts#L918-L923
I think this is the reason why it alerts again after dismissing the first one.

**Comment by gbtami** [comment]
I don't think so. This message is coming from the server (from wsl.py) twice instead and
handled here https://github.com/gbtami/pychess-variants/blob/master/client/lobby.ts#L897
