### ISSUE TITLE
Survive server restart

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#1314]
Heroku initiates daily server restart in random times. See https://devcenter.heroku.com/articles/dynos#restarting
Stuff needs to be saved/restored are

- [x] correspondence games
- [x] lobby chat
- [x] seeks
- [x] games
- [x] tournaments

**Comment by mattgatto** [comment]
[save-regular-seeks-across-restart.diff.txt](https://github.com/user-attachments/files/16769809/save-regular-seeks-across-restart.diff.txt)

**Comment by mattgatto** [comment]
![gbtami-pychess-discord-correspondence-seeks-bug](https://github.com/user-attachments/assets/16528a6e-8b97-46d0-9139-1336fe85aa9c)

**Comment by gbtami** [comment]
Seems OK for me.
PR please :)

**Comment by gbtami** [comment]
Thx!
