### ISSUE TITLE
Dragon chess

### ISSUE THREAD

**Issue by GM-ILLESCAS** [gbtami/pychess-variants#1338]
Hello! I am Chess Grand Master Miguel Illescas. I would like very much to play dragonchess on pychess.com 
Fairy Stockfish is already able to play this modality son it shouldn't be a big deal to include it on pychess offer.

I am ready to organize several events and bring a lot of traffic to pychess.com

I was playing this modality with Ivanchuk, Anish Giri, Ivan Sokolov and many other top players and everybody likes it very much. Also amateurs - and children - love dragonchess since it is very simple to learn and funny to play.

More info about dragonchess --> https://www.edami.com/dragonchess/

**Comment by gbtami** [comment]
Hi Miguel,
First of all thx for the offer. Unfortunately our site popularity and traffic is rather low, so bringing here some big names (and lots of kids as well, of course)  would be awesome. As Fairy-Stockfish already supports it we can add it to the site with little work.

**Comment by GM-ILLESCAS** [comment]
That are great news Tamas! I will provide you with our dragon piece design which I think it's very nice. Please let me know what else can I do to help.

**Comment by Carpatos** [comment]
Miguel told me that you would like to have the image of the original dragon. I am attaching all the graphic supports we have, in case any of them are useful to you. Anyway, I've seen the piece you designed for the app and it's great!

https://we.tl/t-guPTpNtPRI

Cheers,
Carlos J. Penin - Ajedrez21

**Comment by gbtami** [comment]
Thx. We prefer to use .svg images for pieces because they scale better than pixel formats.
I like your 3D dragon very much. Is it possible to create a 2D .svg (merida and cburnett style) piece from that ?

**Comment by gbtami** [comment]
Btw our graphic designer @CouchTomato87 created a dragon piece:
![](https://cdn.discordapp.com/attachments/641327060090093581/1221206454162296903/image.png?ex=6611bc23&is=65ff4723&hm=c30460489dca41ca370d0b4783fb9c13702c060db151138e3fc3b10dac656d8e&)
What do you think about it?

**Comment by Carpatos** [comment]
Dear Bajusz,
attach SVG files.
I hope they are useful to you.

Cheers,
Carlos - Ajedrez21

**Comment by gbtami** [comment]
@Carpatos attachment is missing.

**Comment by Carpatos** [comment]
Sorry about that, here it is.

**Comment by Carpatos** [comment]
Attach SVG files
![dragonchess_white](https://github.com/gbtami/pychess-variants/assets/36102213/b9570666-30c4-4158-abca-333c63205ec5)
![dragonchess_black](https://github.com/gbtami/pychess-variants/assets/36102213/750d455f-3e3d-4b6c-8155-d52497cdbd56)
![dragonchess_neutral](https://github.com/gbtami/pychess-variants/assets/36102213/372e19d3-6ce5-4821-8b97-3ea96c59f68f)

**Comment by gbtami** [comment]
Thx. Almost there :)
They looks like this now
![dragons](https://i.imgur.com/sGJaBYL.png)

**Comment by Carpatos** [comment]
There is a version with a white background!

**Comment by Carpatos** [comment]
There is a version with a white background!
![dragonchess_white](https://github.com/gbtami/pychess-variants/assets/36102213/12748602-b396-4a20-b44a-8e2f7b9f7305)

**Comment by Carpatos** [comment]
Attach again a new version of the white dragonchess
![dragonchess_white_new](https://github.com/gbtami/pychess-variants/assets/36102213/00bc8319-88ce-46cc-a36b-0df98c4c729a)

**Comment by Carpatos** [comment]
and a new black dragonchess colored with white details.
![dragonchess_black_new](https://github.com/gbtami/pychess-variants/assets/36102213/90bfae74-9f33-4ad0-b9ac-a5fe76b4f506)

**Comment by Carpatos** [comment]
improved versions

**Comment by GM-ILLESCAS** [comment]
> Thx. Almost there :) They looks like this now ![dragons](https://camo.githubusercontent.com/e8b700675e5a6f38c4243bc5ee9319dcd21a7a7fd81e9a03c8cfc55932c115d1/68747470733a2f2f692e696d6775722e636f6d2f73474a6142594c2e706e67)

**Comment by GM-ILLESCAS** [comment]
looks very nice!!!

**Comment by gbtami** [comment]
@Carpatos thx, it is great now. ![dragons](https://i.imgur.com/w4suAoc.png)

I think this will be OK for CBurnett/Wikipedia style piece set. (@CouchTomato87 ?)

On pychess site we try to offer both Merida and CBurnett style pieces though and we use Merida style pieces as default.
Can you try to create Merida dragons as well please?

**Comment by gbtami** [comment]
Btw you can test it on https://pychess-variants-dev.onrender.com/editor/dragon
There is a gear icon at the top right corner where you can change board settings like piece sets:
![pieces](https://i.imgur.com/BLjjfBV.png)

**Comment by Carpatos** [comment]
This design was precisely created to combine with the Merida pieces! We think it will also combine very well with merida.
![merida_chessdragon](https://github.com/gbtami/pychess-variants/assets/36102213/ae8d779c-418c-4b3b-8bd3-8bc1da8d7a2b)

**Comment by Carpatos** [comment]
This design was precisely created to combine with the Merida pieces! We
think it will also combine very well with merida.

**Comment by Carpatos** [comment]
However... I upload this other set, in case you like it better to accompany the Merida style
![dragonchess_black_merida](https://github.com/gbtami/pychess-variants/assets/36102213/14824062-ef05-4516-8e26-1f78acc63e14)
![dragonchess_white_merida](https://github.com/gbtami/pychess-variants/assets/36102213/c6cb889b-a243-4342-ac72-37428f9d1e72)

**Comment by Carpatos** [comment]
However... I upload this other set, in case you like it better to accompany
the Merida style

**Comment by GM-ILLESCAS** [comment]
> Btw you can test it on https://pychess-variants-dev.onrender.com/editor/dragon There is a gear icon at the top right corner where you can change board settings like piece sets: ![pieces](https://camo.githubusercontent.com/36a4f818c58ca71bcb09d32bb510f2ec7258c40020ee443162086aac7f8d2a68/68747470733a2f2f692e696d6775722e636f6d2f424c6a6a6642562e706e67)

It works perfect! I can't wait to play on the official site!

**Comment by GM-ILLESCAS** [comment]
But it should allow dragon promotion!

![image](https://github.com/gbtami/pychess-variants/assets/164373758/a92698f4-3bbc-4733-81c6-c3cd595e28a2)

**Comment by gbtami** [comment]
Nice catch :)
Created https://github.com/fairy-stockfish/Fairy-Stockfish/pull/766

**Comment by GM-ILLESCAS** [comment]
Thanks! Please let me know when the dragonchess will be available for the public, I would like to organize a tournament and need time to prepare it :-)

**Comment by gbtami** [comment]
We are almost there. The only remaining thing is a new version of [ffish.js ](https://www.npmjs.com/package/ffish)
We use that on client side (in browser) code to provide promotion choices.

**Comment by gbtami** [comment]
@GM-ILLESCAS it is available from now on. See https://www.pychess.org/blogs/Spring_Update
If you have any question please join our Heroku server https://discord.gg/aPs8RKr
or send me private message on lichess https://lichess.org/@/gbtami

**Comment by gbtami** [comment]
Created the very first Dragon chess arena tournament https://www.pychess.org/tournament/nfKJ9zn7
I added you to (https://www.pychess.org/@/dearmike) "Tournament Directors" so you can create tournaments as well in "Play"->"Tournaments" menu.

**Comment by GM-ILLESCAS** [comment]
Hi Tamas,
that is great, congratulations!

I will be missing this one since I have lunch outside today, but I will
soon start organizing some events!

Is it possible to set up by default the dragon figurine which I provided?
My pupils are more used to this design, and I already recorded a lot of
videos with this design in my old Windows app.

Thanks
Miguel Illescas

**Comment by GM-ILLESCAS** [comment]
Hi Tamas,
that is great, congratulations!

I will be missing this one since I have lunch outside today, but I will soon start organizing some events!

Is it possible to set up by default the dragon figurine which I provided? My pupils are more used to this design, and I already recorded a lot of videos with this design in my old Windows app.

Thanks
Miguel Illescas

**Comment by gbtami** [comment]
Sure, no problem. I changed it in the source code. It will be available after the next server restart.
