### ISSUE TITLE
New game dialog regression

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#1374]
puppylin reported on Discord:
"A legutóbbi változtatások után nem tudok játszani a számítógéppel. Nem tudom megerősíteni a játék kezdetét, mert a gomb valahol lejjebb található. A teljes oldal lefelé mozog, de a felugró ablak mozdulatlan marad."
![](https://i.imgur.com/zjAFDCP.png)

**Comment by randompearl-stack** [comment]
Thanks.
