### ISSUE TITLE
Unable to log in anymore

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#14]
For some reason I can't log in anymore. I come in as anonymous and even after going through the login dialogue of using my lichess account, it spits me back into the lobby as Anonymous, but the login button is gone.

**Comment by gbtami** [comment]
I''v just added BOT auth stuff and server was in maintenance mode. Restarted it now. If you have open tabs with site, close them and retry now.

**Comment by CouchTomato87** [comment]
Still doesn't work...

**Comment by gbtami** [comment]
Are you using the same username for lichess login and for pychess-variants login?
Are you sure the passwd is correct?

**Comment by CouchTomato87** [comment]
There's not even a pychess-variants login. It just asks me to authorize lichess to use my account to login

**Comment by gbtami** [comment]
Still can't reproduce.

I tried several scenario.

I. If I was already logged in to the site with my lichess acc it preserves my name in browser cookie.
This case I don't have to log in again.

II. If I cleared browser cookie and I'm currently logged out on lichess:

1. When I arrive to the site I get an AnonymousXXXX username on nav bar.
2. I click on the "Login with Lichess" button.
3. I get this page
![login0](https://user-images.githubusercontent.com/479964/63210371-db449d80-c0ed-11e9-802f-cfdb802db11f.png)
4. I get this page
![login2](https://user-images.githubusercontent.com/479964/63210379-e7305f80-c0ed-11e9-9f20-ec9e7a94d270.png)
5. I have my lichess username on the nav bar.

III. If I'm currently logged in on lichess using another browser tab same sequence but without step 3.

What is your scenario? What exact steps are you doing? And where it is different from above list?

**Comment by CouchTomato87** [comment]
I guess this seems to be working now. We can reopen if this comes up again

**Comment by gbtami** [comment]
Can you confirm that you added USA to your lichess profile just before it started working again?
Or you just tweaked anything else there?
I'm asking this because today https://lichess.org/@/nurture faced with similar problem, but after he added a single line to his profile, "Login with lichess" started to work for him.

**Comment by CouchTomato87** [comment]
I actually did do that. I was probably tweaking my lichess profile a bit when it wasn't working. And just added USA because I saw that was missing.
