### ISSUE TITLE
Announcement sounds while playing

### ISSUE THREAD

**Issue by catask** [gbtami/pychess-variants#140]
If there's an option to turn this on or off it would be nice. I like to hear the piece sound for e.g. drops/captures, but sometimes the 'check' sound or 'victory' sound would be nice to turn off time to time, without muting the whole browser.

**Comment by gbtami** [comment]
Yes. Now the site uses lichess robot sound theme. Standard theme should be added also.
https://github.com/ornicar/lila/tree/master/public/sound

**Comment by gbtami** [comment]
Changed sound theme back to lichess "standard" one. (I used "robot" before.)
