### ISSUE TITLE
Custom setups with no castling in Seriawan chess is tripping up the gating rules 

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#1406]
**Exact URL where the bug happened**

**Steps to reproduce the bug**

rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/QBBNNRKR[HEhe] w BCDFGbcdfg - 0 1 is a custom Seriwan chess setup that should work correctly if castling rules are disabled. Apparently the gating rules in Seirawan chess doesn’t recognize this possiblility. This may need an update to the coding to account for this scenario. 

**What did you expect to happen?**

**What happened instead?**

**Operating system and browser version**

**Comment by gbtami** [comment]
Wrong repository. This should go to https://github.com/fairy-stockfish/Fairy-Stockfish/issues
