### ISSUE TITLE
Crazyhouse 960 games unable to start

### ISSUE THREAD

**Issue by catask** [gbtami/pychess-variants#141]
I notice that the game only start with the 'Ready' voiceover, when it didn't come then the game couldn't be started and there was no resign, draw, or abort buttons on there. No move/premove could be made by either player. Eventually we were able to get the game going, on one time there was a slight delay where no action could be taken but then after 'Ready' it was possible to make moves.

**Comment by gbtami** [comment]
Fixed via d6f8e22
If you still experience this feel free to reopen.
