### ISSUE TITLE
zh960 game piece icons in the hand disappear after flip board command

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#1419]
pkr5025 reported on Discord:
pretty minor issue, but when spectating zh960 on firefox, when I hit 'f' and flip the board, the piece icons in the hand disappear.
Before
![](https://cdn.discordapp.com/attachments/884382880338415616/1234189681353162812/Screenshot_2024-04-28_at_12.08.06_PM.png?ex=662fd436&is=662e82b6&hm=d6bba7f7b9a092120d1e7a0ab32e08790125f7180daf2b400a5b898195ae107b&)
After
![](https://cdn.discordapp.com/attachments/884382880338415616/1234189717839286323/Screenshot_2024-04-28_at_12.08.13_PM.png?ex=662fd43e&is=662e82be&hm=5784a0cb7e2068c56653f1b9118d65685111868814f809aa87988092b6d59544&)

refreshing brings the piece icons back, but also resets the board orientation

**Comment by randompearl-stack** [comment]
https://github.com/gbtami/pychess-variants/blob/8b5f958bec4927734bd6928f6e7ba5c5744b12a2/client/editor/pieceRow.ts#L39-L46
https://github.com/gbtami/pychess-variants/blob/8b5f958bec4927734bd6928f6e7ba5c5744b12a2/client/pocketRow.ts#L19

Not sure where exactly it is controlled but when the board is flipped the `--piecerows: 1` inline style disappears. Also, the issue affects all variants with pockets.

**Comment by gbtami** [comment]
Thx for the pointer! It helped a lot.
