### ISSUE TITLE
capablanca960 castling rules ignored in game when position allows it.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#1435]
**Exact URL where the bug happened** https://www.pychess.org/hFFmFD6h

**Steps to reproduce the bug** setup any capablanca960 position and when possible…drag king onto rock…castling rule is ignored.

**What did you expect to happen?** castling would be allowed. 

**What happened instead?** castling rule ignored.

**Operating system and browser version** ios latest edition ipad pro 3rd generation.

**Comment by gbtami** [comment]
Works for me. See https://www.pychess.org/jMC9TkOe
If you can provide exact steps to produce this feel free to reopen.
