### ISSUE TITLE
Hostage Chess

### ISSUE THREAD

**Issue by Finlip** [gbtami/pychess-variants#144]
One variant that I came across is hostage chess. I would love to see it get implemented here.  hostagechess.com is a great website with a free book and playing program.

**Comment by gbtami** [comment]
Pychess-variants is heavily based on Fairy-Stockfish. I use it for move generation, validation, SAN conversion, analysis, BOT play, etc-etc. Because of this I can add variants only supported by Fairy-Stockfish. Until it is not there I have to close this issue, sry.

**Comment by ianfab** [comment]
Also see https://github.com/ianfab/Fairy-Stockfish/issues/19
