### ISSUE TITLE
Xiangqi Piece Sets

### ISSUE THREAD

**Issue by Eventlesstew** [gbtami/pychess-variants#1461]
I made two piece sets for Xiangqi. One set has guides to help people get used to the Hanzi while the other removes those guides for those who prefer it just for how it looks.

I tried making a pull request but gave up because I have no idea how to delete commits I don't need. (I don't mean to be nitpicky, but what's wrong with implementing a simple X button?)
[Guided.zip](https://github.com/gbtami/pychess-variants/files/15284813/Guided.zip)
[Basic.zip](https://github.com/gbtami/pychess-variants/files/15284812/Basic.zip)

**Comment by randompearl-stack** [comment]
Before making changes, you should update the branch you are merging with to the parent repository (sync fork), so any previous commits will already be reflected.

**Comment by gbtami** [comment]
Also the preferred way to create PRs is first [create a branch](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell) for your PR work (don't work in the master branch!).
This way only commits in that branch will be affected in a particular PR.
Deleting commits in git is not possible. git is a VCS (version control system) designed to preserve all versions of your source files, but you can do `git revert` which will undo a particular git commit.

**Comment by Eventlesstew** [comment]
> Before making changes, you should update the branch you are merging with to the parent repository (sync fork), so any previous commits will already be reflected.

Alright then

**Comment by Eventlesstew** [comment]
> Also the preferred way to create PRs is first [create a branch](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell) for your PR work (don't work in the master branch!).
> 
> This way only commits in that branch will be affected in a particular PR.
> 
> Deleting commits in git is not possible. git is a VCS (version control system) designed to preserve all versions of your source files, but you can do `git revert` which will undo a particular git commit.

I did create a new branch btw.

**Comment by randompearl-stack** [comment]
Are any of you going to add the piece sets?

**Comment by gbtami** [comment]
I planned, but had no time so far. If you can turn this into a PR it would be appreciated.

**Comment by randompearl-stack** [comment]
completed?
