### ISSUE TITLE
Adding a crazyhouse variant to Khans Chess.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#1472]
This is the one crazyhouse variant of the asymmetrical chess variants I’d like to see implemented. Interestingly enough none of the other variants like Orda, Empire, Synochess, Chak have crazyhouse variants. But this one, Khans chess deserves it. The unique powers of the scouts and the Khatun make this chess variant a special one in my book, more so than Orda or Orda Mirror chess. A crazghouse variant of Khans Chess would take the cake. Please consider.

**Comment by gbtami** [comment]
The combination of existing variants and specific game rules (anti, zn, 960, mirror, etc-etc) are nearly endless.
I suggest to use our Discord #variant-workshop channel to share your ideas.  There is a thread "Unofficial fork for alternate variants" where you can ask autocorr to consider to add it to  https://pychess-alternates.onrender.com
