### ISSUE TITLE
Mansindam piece colors don’t change when playing white or black.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#1477]
**Exact URL where the bug happened** just play any game with mansindam.

**Steps to reproduce the bug** play either white or black.

**What did you expect to happen?** piece colors would be reflected based on the side you play with.

**What happened instead?** regardless of side you’re playing, color stays the same.

**Operating system and browser version** ipad OS latest version.

**Comment by Curious2021** [comment]
I just want to clarify this bug is happening with the set pieces that resembles shogi pieces with the shapes pointing in the direction of the piece set only. Not the western style pieces.

**Comment by gbtami** [comment]
In shogi style piece sets the kings are different.
You can check it on http://127.0.0.1:8080/editor/mansindam selecting the piece set you use then click "FLIP BOARD"
