### ISSUE TITLE
Disable private matches (PLAY WITH A FRIEND) for bughouse

### ISSUE THREAD

**Issue by nnickoloff1234** [gbtami/pychess-variants#1495]
Disable private matches (PLAY WITH A FRIEND) for bughouse, it is currently not implemented but bughouse option nevertheless appears for PLAY WITH A FRIEND mode resulting in server error when used

**Comment by gbtami** [comment]
This was fixed via https://github.com/gbtami/pychess-variants/commit/bdc0c2baebcb89111f3ba09636288e74e9ba76c7 I think.
