### ISSUE TITLE
Piece Sets and Boards

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#15]
I noticed that some people didn't even know you could change the piece sets by clicking the settings button on the top right. I think for a game about one game (like lichess) it's fine to keep it in the overall settings, but in this game where different types of games are played, I think it makes more sense to have this option within the game interface instead of the top menu bar, kind of like what they do in playok.com. As of now, the interface uses a lot of space for just three buttons (abort, draw, and resign). Maybe you can squeeze in graphics options too?

Along those lines, maybe this is already planned, but would you be able to split the piece sets and boards so you can mix and match, like you can do in lichess? 

Also, the thumbnail previews when looking at other player's games does not update with your current theme.

**Comment by gbtami** [comment]
Agreed. I plan to add preferences menu later, similar to lichess.

Will fix thumbnail boards. Thx for noticing it!

**Comment by CouchTomato87** [comment]
Another thought: Alternatively, you could have the options for pieces and boards in the top left in that little window that has the game name and the players. There's plenty of space on the right side of that window.

**Comment by gbtami** [comment]
I plan to add something similar what lichess has.
![menu](https://user-images.githubusercontent.com/479964/63638566-4e1fbc80-c68a-11e9-8071-e44d7deefc64.png)

**Comment by CouchTomato87** [comment]
Right. The only problem though is that in lichess, your changes apply for the whole site, so it makes sense to put it in the "general menu." However here, you have multiple different games with different sets, so it's hard to do that without changing the menu for each game. And in that case, it's not so obvious (case in point, people have to keep reminding viewers that they can change piece sets by clicking the gear in the top right in games like shogi, etc).

**Comment by gbtami** [comment]
I agree that my temporary gear solution is far from being ideal :)
On the other hand I want to keep as much as I can from  lichess UI look and feel. What about adding a so-called hamburger menu right after the movelist navigation buttons? I mean similar what lichess uses on analysis mode. 
![analysis](https://user-images.githubusercontent.com/479964/63638952-93de8400-c68e-11e9-8479-7a6d5476cfbc.png)

**Comment by gbtami** [comment]
You can select available pieces sets in settings panel now. (click on gear button)

**Comment by CouchTomato87** [comment]
Hey! If you don't mind, I'd like to add one fourth and final piece set option for the combo pieces (archbishop, chancellor, etc)! I've always preferred them to have their own look rather than just mix pieces together, so I used the designs from http://musketeerchess.net/ (hopefully that's okay). They're also adapted for the Merida style.

[Musketeers.zip](https://github.com/gbtami/pychess-variants/files/3588441/Musketeers.zip)

**Comment by gbtami** [comment]
Great, thx! Committed them.
Seems https://github.com/gbtami/pychess-variants/blob/master/static/images/pieces/merida/WC2.svg has transparency issue yet.

**Comment by CouchTomato87** [comment]
Whoops. That's what happens when Inkscape just gives you a white background the whole time lol. I fixed it now.

**Comment by gbtami** [comment]
As I see it is still transparent :)

**Comment by CouchTomato87** [comment]
Lol, that's insane! I'm pretty sure I fixed it. I just changed it yet again now -- double checked now too :)

**Comment by gbtami** [comment]
Added boards to settings (independent from pieces).

**Comment by CouchTomato87** [comment]
Awesome!!! I'll get out some new shogi and xiangqi boards for you (mostly recolors) :D

**Comment by CouchTomato87** [comment]
I put in a replacement shogiban1.png. I also uploaded two new boards... ShogiMaple (based on our favorite chess board), and ShogiCheckeredWood (basically one of the wooden shogi boards, but checkered). I'd replace the gray and red textured boards currently being used. I'm loving the green textured one though :)

**Comment by gbtami** [comment]
Done.

**Comment by CouchTomato87** [comment]
Thanks! Somehow the checkered wood board got messed up, and I had to re-commit that one... Sorry!

**Comment by gbtami** [comment]
Np. the new boards are cool! Thx!

**Comment by CouchTomato87** [comment]
If you add this line to the css wrap: "background-position: center;"

Does that fix the edge line disappearing?

**Comment by gbtami** [comment]
No it doesn't. At least at some zoom value this is how it renders in Firefox
![shogi](https://user-images.githubusercontent.com/479964/64956530-1bcd3d80-d88b-11e9-81ba-c336be597e8c.png)

**Comment by CouchTomato87** [comment]
Hmm, I used the exact same dimensions as the original svg. The dimensions are also all multiples of 9. I think the problem is simply the fact that the edge will inevitably be cut off if the scaling goes from an odd to even or even to odd number of pixels. The original svg also cuts off (but it's two pixels thick, so it just becomes thinner). 

https://css-tricks.com/almanac/properties/i/image-rendering/

I wonder if this helps? Although some of those features like crisp-edges or pixelated work on some browsers, but not others. Otherwise, I wonder if another solution is that for these boards swith grids, can you can add a 1 px stroke to it in the code?

I should also mention that on my MacBook Chrome browser, the boards and scaling bar actually extend outside their box. 

![Image 9-16-19 at 8 54 AM](https://user-images.githubusercontent.com/52322435/64959673-a26c2580-d85f-11e9-8ddb-57249577b0e7.jpg)

**Comment by gbtami** [comment]
Interesting. On Ubuntu 18.04 Chromium 76.0.3809.100 it is OK.

**Comment by CouchTomato87** [comment]
Nice!

I just updated some boards... I updated Shogiban2 and the shogicheckeredwood files. As much as it pains me, could you replace the green shogi board to make room for shogiban2? Also, I think it would make sense to have Shogiban1 and Shogiban2 be 2nd and 3rd in order (so that classic shogi boards come before the more radical checkered boards).

I also added two new xiangqi boards, a paper one and a dark wooden one. :)

I think that's all I've got for boards, haha

**Comment by gbtami** [comment]
Uploaded. Thx!

**Comment by CouchTomato87** [comment]
Is that something you'd want me to do next?

Also, I updated all the internationalized xiangqi graphics now.

**Comment by gbtami** [comment]
Makruk and Sittuyin has no Guides. If you can write something similar to Shogi/Xiangqi it would be appreciated. Regarding pieces I have on minor thing always wanted to fix. Makruk pieces are little wrong placed vertically. Th top of the King is out of square. Maybe all pieces (except powns) should be moved a little down.
![makruk](https://user-images.githubusercontent.com/479964/65489954-847c7180-deac-11e9-9155-3e5ea687f87b.png)


Thx  again!

**Comment by gbtami** [comment]
Seems the blacks pawn lost their circles in updated Xiangqi set.

**Comment by CouchTomato87** [comment]
Whoops! Fixed it. Also reduced the gradient on some pieces.

I can do the guides. Yeah, moving the pieces should be no big deal.  I was wondering if you ever wanted a replacement set because the files for those pieces are incredibly complex with a million layers. I bet their file size isn't the best.

**Comment by gbtami** [comment]
After latest Xiangqi update some aliens appeared in black camp :)
![xiangqi](https://user-images.githubusercontent.com/479964/65574140-ebf9f600-df6c-11e9-82c6-8a63d4a13085.png)

**Comment by CouchTomato87** [comment]
Yikes! They should be fixed now. Not sure why the advisor ring disappeared. It showed up on Inkscape. I fixed that too, somehow.

**Comment by gbtami** [comment]
Thx! Deployed.

**Comment by CouchTomato87** [comment]
I committed updated Makruk pieces. I couldn't find any decent 2D pieces, so I just shifted the ones we have, like you requested (I still don't like the knight).

I'll work on creating Makruk/Sittuyin guides as well as updating the Xiangqi one next.

**Comment by gbtami** [comment]
Thx a lot! Deployed.

**Comment by CouchTomato87** [comment]
> Uploaded. Thx!
> 
> Btw. we should offer more boards in settings dialog if we use little/shrinked 1x2 .pgn board thumbnails instead of full board images. They are defined in https://github.com/gbtami/pychess-variants/blob/master/static/site.css#L680
> 
> Something like this:
> ![Képernyőkép_2019-09-17_11-03-50](https://user-images.githubusercontent.com/479964/65027581-e4b66500-d93a-11e9-884d-4319791393c0.png)

Do you want me to make these board icons too?

**Comment by gbtami** [comment]
I think we have enough boards and pieces at this moment users can choose, from so I say no.

The only remaining thing I'm not satisfied is the gray Makruk board I have added before. The white king top and all black pieces bottom are rendered over the grid lines somehow. I'm not sure what would be the better way to fix it. Shorten the pieces a bit or drop this board and find another?
![makruk](https://user-images.githubusercontent.com/479964/66290492-c1e6f300-e8df-11e9-9c36-eedcd8b8496e.png)

**Comment by gbtami** [comment]
Btw I have another interesting issue with Makruk pieces. The concentric circles of pawns produces some kind of visual illusion effect. If I move my eyes vertically while I'm looking at the board I see ghost pawn chains above and/or bellow the real pawn chains. Can you see this effect? :)

**Comment by CouchTomato87** [comment]
I saw the pieces overlapping and then I actually kinda liked it. It gave kind of a 3D feeling. For an alternative board, I think it's okay.

And no, I don't see that pawn effect myself, but I can definitely see that happening to people lol.

**Comment by gbtami** [comment]
OK, if you "kinda liked it", let it as it is now :) 
If you can find alternative boards for variants having less than 6, feel free to commit  them any time.

**Comment by Diwaditya** [comment]
Woah :octocat:
