### ISSUE TITLE
Players using edge don't see light/dark squares

### ISSUE THREAD

**Issue by catask** [gbtami/pychess-variants#150]
Players using edge (the old version) can't see light/dark squares, just one giant blob. Reproducible issue, reported by many users.

**Comment by gbtami** [comment]
Yes, I'v seen this in opper's video https://www.youtube.com/watch?v=he-4JmbzUNs :)
I'm sorry to say but unfortunately I don't have enough time to support not compatible shit MS browsers myself. My only suggestion is https://support.microsoft.com/en-us/help/4501095/download-the-new-microsoft-edge-based-on-chromium
If anyone else has time/knowledge to fix it, any PR is welcome.

**Comment by catask** [comment]
Heh, agreed with you since it work on every browser I tried. Maybe can put a message on pychess to use another browser? Like ‘pychess work best with chrome/chromium edge’ or something like this.

**Comment by gbtami** [comment]
Good idea, thx!

**Comment by gbtami** [comment]
Chromium based Edge will kill old Edge soon, so I close this.
