### ISSUE TITLE
[Feature request] query string ?pieceSet=intlkakao

### ISSUE THREAD

**Issue by khonkhortisan** [gbtami/pychess-variants#1507]
I'm loading puzzles in an iframe in Anki so that I can individually schedule their reviews with spaced repetition. 장기 / janggi is one of those games where I'd prefer to not have the pieces in a foreign language.

https://lishogi.org/study/O591ZfdK/Qck0YxmN?pieceSet=Ryoko_1Kanji
https://lishogi.org/study/O591ZfdK/Qck0YxmN?pieceSet=western
https://lichess.org/training/mix?pieceSet=merida
https://lichess.org/training/mix?pieceSet=pixel
https://www.pychess.org/puzzle/janggi?pieceSet=hanjablue
https://www.pychess.org/puzzle/janggi?pieceSet=intlkakao

(I haven't yet gotten around to tracking down the janggi puzzle list, but I'm adding this feature request for lidraughts and pychess at the same time, and leaving online-go alone because it isn't necessary to understand the language nor differentiate variants)

**Comment by gbtami** [comment]
I don't understand what you want, sry. Piece set can be selected in board settings.

**Comment by gbtami** [comment]
@khonkhortisan OK, after reading it again I understand now :)
I don't plan to implement it in this project though.
But.
This will be https://github.com/gbtami/pychess-boardimage
It is already usable for variants based on "normal" boards using squared fields.
Supporting Shogi, Xiangqi, Janggi need some further coding (support not just pieces CSS, but boards as well).
