### ISSUE TITLE
Shogi analysis drop move suggestion rendering bug

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#151]
https://www.pychess.org/hyFlAWHC
See move 45
https://files.catbox.moe/dax8vy.mkv

**Comment by aphirst** [comment]
Sorry I had the video set to follow the cursor! I thought selecting the window region would override that, but it just set the video size. Whoops.

I can put some of this into text if it would help, and also add some comments that I didn't say in the video, or which might not have been clear.

Also this is technically two bugs, and I'd bet my life they're related.

**1. Suggested piece drops**
* click on move 45, K-7c (by me, white)
* the suggested move for black is a drop R*5c, but the piece graphic is upside down
* notice in my video that the suggested piece, the rook, is oriented as if it's one of white's pieces, i.e. it's upside down
* it's the same problem if you flip the board; it's a suggestion for black but it's pointing in the direction that black's pieces should
* problem persists no matter what settings you change, piece graphics, board flips etc.
* problem occurs for both players too, click on move 48, Sx6g; the suggested piece drop (B*8h) for white is oriented as if it's one of black's pieces

**2. ALL pieces on the board**
* with the board oriented from black's view, change the piece graphics
* all pieces currently on the board flip upside-down
* this persists if you keep changing the piece graphics
* it fixes itself if you flip the board around, and the problem doesn't occur from white's view
* **interesting note**: while this problem occurs, notice that the suggested piece drops match the "correct" player's wrongly-oriented pieces

Does this only happen for handicapped games, or if the non-AI player is a certain colour? Does it matter whether the current logged in user was in the game being analysed? Why is it only happening on my machine?

**Comment by aphirst** [comment]
The reason handicap games come into question could be that the "first player" is white, in opposition to normal shogi games where the first player is black.

**Comment by aphirst** [comment]
!!!

Both problems do NOT occur if I view the same game record after logging out of pychess. It really does seem to matter that you're viewing it as the user who played that game.

**Comment by CouchTomato87** [comment]
Bug reproduced.

1) You need to play a HANDICAP game
2) You (the human) need to be playing as WHITE
3) You need to be in ANALYSIS (not looking at the analysis as a spectator)

**Comment by aphirst** [comment]
On further analysis, only 2. and 3. are required. I can reproduce the same issue now simply as white, logged in, in analysis mode. Handicap does not seem relevant.
