### ISSUE TITLE
When kings are in check on both boards partner board check mark is incorrect

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#1516]
https://pychess-variants-dev.onrender.com/wpoF2vMG
![https://i.imgur.com/ERO6lGx.png](https://i.imgur.com/ERO6lGx.png)

**Comment by gbtami** [comment]
This still the same.

**Comment by nnickoloff1234** [comment]
@gbtami 
how do you reproduce it exactly?
i found 2 similar problems and fixed both of them - one was when scrolling moves of old games including the one in the link, the second when doing a manual F5 refresh when position is such that both boards have a king in check. what is the scenario in which you reproduce this bug now?

**Comment by gbtami** [comment]
The game link is presented in my very first comment.
When I click on it, it opens the game (on DEV server) first without the move list like this
![https://i.imgur.com/y0PYH59.png](https://i.imgur.com/y0PYH59.png)
here the check marks are OK, but after 1-2 sec (when the move list appears)
the red check mark on  partner board moves to the white King on g1.

**Comment by nnickoloff1234** [comment]
![image](https://github.com/gbtami/pychess-variants/assets/2179288/be0d994a-703e-429d-926f-7c24e66ff068)
I don't reproduce it, maybe you are still using some cached js?

**Comment by gbtami** [comment]
No. I clear browser cache regularly while I'm testing other stuff. You can see the game result on thin screenshot as well, and it was committed after your check mark fixes.
![https://i.imgur.com/fxPvXMC.png](https://i.imgur.com/fxPvXMC.png)

**Comment by gbtami** [comment]
Btw I just noticed it rn, there is a last move mark of B@h6 as well on the partner board in my case, while it happened on the left board. Strange thing is there is no last move mark on your screenshot at all.

**Comment by nnickoloff1234** [comment]
Ok, i reproduced what is on your schreenshot exactly how you describe it with the delay before loading the move list etc. using Chrome. My screenshot was with Firefox.

**Comment by nnickoloff1234** [comment]
turns out it was not because of browser, but because i was logged in on firefox and seeing it in player's mode, since this is one of my games and was not logged in on chrome and seeing the game in spectator's mode as anon is where the difference came from
