### ISSUE TITLE
suggestion: allow the sideway pawn chess variant as an option for KoTH for testing. 

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#1518]
Currently sidewaypawn chess is a separate variant on the alt site of pychess for testing. But i was thinking this would be a great opportunity to allow this variant to be made an option for KoTH. Imagine being able to play KoTH and having the ability to allow the pawns to move sideways to letting the king get to the center of the board? i think allowing KoTH to have this ability added for testing would be a great way to see if this is a feasible option for this game variant. Currently KoTH has a 960 option already. Adding sideway pawn ability to this variant would be a good way of testing its viability as an option.

**Comment by gbtami** [comment]
For variant suggestion use pychess Discord please. Thx.
