### ISSUE TITLE
bughouse check (checkamate) highlight wrong

### ISSUE THREAD

**Issue by nnickoloff1234** [gbtami/pychess-variants#1523]
There is a check on both boards, but same coordinate is used to highlight the king on both boards thus making a wrong highlight on the other board.

Unclear if this happens every time there is a check on both boards, or the fact that it is a checkmate caused it, or even maybe the clock running out the same time as seen on the screenshot might have caused some sort of flag end game message simultaneously that resulted in wrong rendering of highlighted square.

![image](https://github.com/gbtami/pychess-variants/assets/2179288/d07176bf-56c8-4128-afce-9eb4e4863204)

**Comment by gbtami** [comment]
You can find another example with game link in https://github.com/gbtami/pychess-variants/issues/1516
