### ISSUE TITLE
when rematching anon who expired the new anon after refresh joins as spectator

### ISSUE THREAD

**Issue by nnickoloff1234** [gbtami/pychess-variants#1533]
found in bughouse, might be relevant in normal mode as well

- play a game between named user and anon user in 2 different browsers
- wait some time (enough for anon to expire) after game ends
- offer rematch with named user
- accept rematch on the page of the anon user
- both browsers open the new game, but anon browser is now logged in with different anon user and is spectator of a game between the named user and the old anon user (who however is impossible to be logged in again)

**Comment by gbtami** [comment]
I think we should disable anons to play bug completely.
https://discord.com/channels/634298688663191582/884382880338415616/1247510356427931740

**Comment by nnickoloff1234** [comment]
closing. anons disabled for bughouse, dont know if this bug relevant for normal variants at all in any way
