### ISSUE TITLE
when a user is logged in in 2 browsers and plays a game, logging out from one, abandons the game

### ISSUE THREAD

**Issue by nnickoloff1234** [gbtami/pychess-variants#1534]
found in bughouse (maybe not only) 

when a user is logged in in 2 browsers and plays a game, logging out from one, abandons the game even though the other browser is not logged off

**Comment by gbtami** [comment]
It happens here https://github.com/gbtami/pychess-variants/blob/master/server/login.py#L212
I just wanted that /ban admin command somehow kick off the user completely. Possible it can be implemented several other better ways.
