### ISSUE TITLE
sending invalid moves possible in bughouse when scrolled to previous position

### ISSUE THREAD

**Issue by nnickoloff1234** [gbtami/pychess-variants#1535]
1. play some moves
2. scroll back from the move list
3. play alternative move - make sure it is not valid according to last position, but current old position allows it
4. it gets send and results in game over with "invalid move" message

**Comment by gbtami** [comment]
For other variants this is prevented by https://github.com/gbtami/pychess-variants/blob/master/client/roundCtrl.ts#L954
