### ISSUE TITLE
Custom FEN position for Seirawan chess considered illegal via dialog box.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#1552]
Created this FEN position via the editor when creating a custom position for Seirawan Chess.

nknrbbqr/pppppppp/8/8/8/8/PPPPPPPP/RQNBBNKR[HEhe]   w BCDFGbcdfg - 0 1

The dialog box says this is an illegal position. I unckecked all the options for castling so this position should be allowed. Why is this position illegal?

**Comment by gbtami** [comment]
This is duplicate of https://github.com/gbtami/pychess-variants/issues/1460
