### ISSUE TITLE
Pychess TV not functioning

### ISSUE THREAD

**Issue by CricketForJapan** [gbtami/pychess-variants#1553]
**Exact URL where the bug happened**  
https://www.pychess.org/tv

**Steps to reproduce the bug**
the moves are not appear, as the move box is blanked out

**What did you expect to happen?**
Watch pychess TV

**What happened instead?**
Moves are not appearing.

**Operating system and browser version**  Windows 10, Chrome, Edge and Firefox
![TV](https://github.com/user-attachments/assets/dcb2124e-a77a-444c-af14-b4a2fee70dbe)

**Comment by gbtami** [comment]
It was already fixed in git via https://github.com/gbtami/pychess-variants/commit/4eb0b3445acd6fe524acf841bd184628b3bf129c
I will deploy today.

**Comment by CricketForJapan** [comment]
I am sorry I only searched open tickets.  Just found a recent closed ticket with same issue, I did not notice that.

**Comment by gbtami** [comment]
Thx for the report anyhow.
