### ISSUE TITLE
Non standard setups finally allowed in S-Chess but at the cost of gating the pieces in the corner.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#1556]
Here's the URL illustrating the issue.

https://www.pychess.org/vezMGPs6

I was successfully able to setup the board in this example which was a long standing issue in a previous Github ticket that had been outstanding. But this short game illustrates a slight issue involving the gated pieces as a result of the new issue. In the game the white bishop moves out of the corner but the option to bring a gated piece which in this case should have been the elephant didn't happen. And I immediately realized the solution to allowing the board setups has been done by sacrificing the option to allow gated pieces that should be allowed to appear in the corner where normally the rooks are located. 

So I'm placing this ticket to make you aware of this small issue right now that needs addressing. Although I admire the fact the board setup issue has been fixed...but only at the cost of allowing gated pieces being recognized in the corners. Once this issue is fixed the whole issue can finally be put to rest.

**Comment by gbtami** [comment]
This is the starting FEN of the game you linked: `rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBNKRQB[HEhe] w BCDFGbcdfg - 0 1`
If you want to enable gating on "h" it have to be in starting FEN gating/castling rights part  as well.

**Comment by Curious2021** [comment]
would this have worked had the checkmarks for castling been enabled? i doubt the logic of keeping the checkmarks for castling on would recognize non standard but viable positions where castling can be allowed - for example, double fischer random for instance.

**Comment by gbtami** [comment]
Editor knows nothing about Fischer random. 960 check mark was never implemented so far.
