### ISSUE TITLE
Add custom seek buttons

### ISSUE THREAD

**Issue by smartchessguiapp** [gbtami/pychess-variants#158]
Upon creating a seek, store the seek parameters in a newly created custom seek button, placed under the normal seek buttons.

Consider this pull request:

https://github.com/gbtami/pychess-variants/pull/157

Screenshot:

![https://i.imgur.com/Qf8wFce.png](https://i.imgur.com/Qf8wFce.png)

**Comment by smartchessguiapp** [comment]
Thanks for resolving the image link. I don't know if this can be done per post or per user. If it is per user, then I'm very happy.

**Comment by gbtami** [comment]
Markdown: `![https://i.imgur.com/Qf8wFce.png](https://i.imgur.com/Qf8wFce.png)`
See https://guides.github.com/features/mastering-markdown/

**Comment by smartchessguiapp** [comment]
I thought it was like discord. So that adiminstrator has to allow resolving images. I did not even try markdown. Does this mean that if I'm allowed to post, then I'm also granted my images being resolved?

**Comment by gbtami** [comment]
Exactly.
