### ISSUE TITLE
Login forgotten within short time

### ISSUE THREAD

**Issue by smartchessguiapp** [gbtami/pychess-variants#159]
The app logs me out very frequently. I don't know if the cookie is only for the session, or it has a low max age, or frequent server restarts are causing this.

**Comment by gbtami** [comment]
What "very frequently" exactly means here?

**Comment by smartchessguiapp** [comment]
It was on the site yesterday. Others also complained. Today it is better. So in theory how long a login should last?

**Comment by gbtami** [comment]
Logins should be preserved while server is running.
Sever was restarted several times yesterday. I restart it nearly after all commit.
What "today is better" means?

**Comment by smartchessguiapp** [comment]
Login was preserved today ok.

But why not store login in db? I have an oauth linked bot in Node.js and there you can store the login. I use Firebase-firestore for this ( but it works with several stores, it must work with MongoDB too ). Ok, this is Node.js, but there has to be something similar in Python.

Here is the npm package to give you some idea:

https://www.npmjs.com/package/@aestheticbookshelf/oauth

**Comment by gbtami** [comment]
Ok, I find https://github.com/alexpantyukhin/aiohttp-session-mongo 
Will add it to pychess soon. Thx for the hint!
