### ISSUE TITLE
Remove MyWebSocketResponse when time comes

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#1595]
See https://github.com/aio-libs/aiohttp/issues/3122 and https://github.com/python/cpython/pull/118960

**Comment by cjavad** [comment]
I actually referenced your original solution to this issue trying to solve it, it was a truet annoying bug 😅

**Comment by gbtami** [comment]
https://github.com/python/cpython/pull/118960 merged \o/
