### ISSUE TITLE
1Kanji pieces

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#16]
Here is the first version of 1 Kanji pieces. I feel like there will probably be issues (with centering, sizing, etc), so expect changes. Unfortunately there is no font available that replicates the ones typically used for shogi pieces, so I had to pick one that's close enough. 

I was also lazy with naming the pieces. But basically I just used the abbreviation of the piece. The number before is the direction (0 = up, 1 = down), and the number 1 after just means 1 kanji as opposed to 2. P before a letter means promoted. T = tokin (promoted pawn).

[1Kanji.zip](https://github.com/gbtami/pychess-variants/files/3513136/1Kanji.zip)

**Comment by gbtami** [comment]
Thx a lot again!
Will add them next week.

**Comment by gbtami** [comment]
May I ask you to rename the files similar to other shogi piece collections we already have, please?
It would be huge help for me!

**Comment by CouchTomato87** [comment]
[1Kanji.zip](https://github.com/gbtami/pychess-variants/files/3518248/1Kanji.zip)

Here you go!

**Comment by gbtami** [comment]
Cool, thx! Deployed it to the site.
One thing I noticed that pawns seems little alien. Maybe they are from different font?

**Comment by CouchTomato87** [comment]
You're correct that they're a different font! For some reason that character did not exist in the font I was using. On top of that, I did not give that character enough stroke because I thought it was a smaller piece. I've updated it by thickening the stroke a little, and I also shortened the little "tail" at the bottom so that it does not stick out as much.

I also updated the silvers and the down-facing rook (1HI) 
[Pawn and Silver.zip](https://github.com/gbtami/pychess-variants/files/3520178/Pawn.and.Silver.zip)
because they were not centered properly.

**Comment by gbtami** [comment]
Just updated them on the site. Seems cool! Thx a lot!

**Comment by CouchTomato87** [comment]
Apparently the "tail" of the pawn sticks out beyond the piece under certain scales (weird!), and the down-facing rook is still off-center. I'll need to fix those again later today.

**Comment by CouchTomato87** [comment]
Okay! I made a lot of changes now. I decided to be a little braver and manipulate the characters. I modified the pawn to look like how it typically looks in shogi. I also changed the kings so that they're more square instead of the skinny ones. I modified the tails of the dragon horses so that they don't stick out as much. And once again, I re-centered the downward rook.

[1KanjiUpdate.zip](https://github.com/gbtami/pychess-variants/files/3522949/1KanjiUpdate.zip)

**Comment by CouchTomato87** [comment]
Sorry for flooding you with so many images, but here's an update to the xiangqi set as well. I gave all the pieces a drop shadow for a 3D look. My next goal with images is to do the same pieces but with Chinese characters (just to keep the same style). But before that, I'll work on a guide for Shogi.

[XQ3.zip](https://github.com/gbtami/pychess-variants/files/3523094/XQ3.zip)

**Comment by CouchTomato87** [comment]
Aaaand one more! I just realized that the white elephant from S Chess has its gradient backwards! This was from when you told me that the elephant was facing right instead of left, so I flipped it, but never flipped the gradient back.

[WE.zip](https://github.com/gbtami/pychess-variants/files/3523199/WE.zip)

**Comment by gbtami** [comment]
Site updated. Thx a lot again!

**Comment by CouchTomato87** [comment]
Awesome! Finally satisfied with the kanji, haha. I do feel that maybe the S Chess white elephant stroke is a little too thick when seeing it in game. Next time I send you a batch of pieces I'll send an updated elephant with it.

**Comment by CouchTomato87** [comment]
Also would it be possible to make the 1 kanji the default set? That's what the Japanese sites do

**Comment by gbtami** [comment]
Sure. On next server restart that will be the default for new users.

**Comment by CouchTomato87** [comment]
For what it's worth, the thumbnails when you look at games played still shows 2-kanji pieces, but I think you're planning on making that update with whatever set you use? 

Also, I updated the Dragon images.

**Comment by gbtami** [comment]
Indeed. I was thought that the first css is used for game list thumbnail. But seems this needs more.
Thx for the heads up.
