### ISSUE TITLE
Docker setup not working

### ISSUE THREAD

**Issue by gp-it-be** [gbtami/pychess-variants#1606]
Steps to reproduce:

1. Clone of the repo
2. run "docker compose up --build" in the root folder

This produces:
#21 [frontend 10/10] RUN yarn md
#21 sha256:948ad1fe9575ab0b3c130f4094ac7171670afdd739eb0185fc671a3e9b0d73cf
#21 0.499 yarn run v1.22.22
#21 0.519 $ ./md2html.sh
#21 0.525 /bin/sh: 1: ./md2html.sh: not found
#21 0.532 error Command failed with exit code 127.
#21 0.532 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#21 ERROR: executor failed running [/bin/sh -c yarn md]: exit code: 127
------
 > [frontend 10/10] RUN yarn md:
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yarn md]: exit code: 127

OS: windows

**Comment by gp-it-be** [comment]
Converting the lineendings of md2html.sh to LF seems to fix this for my machine, have to verify.

Now getting different error:

#15 0.581 yarn run v1.22.22
#15 0.603 $ ./md2html.sh
#15 0.627 node:internal/modules/cjs/loader:1228
#15 0.627   throw err;
#15 0.627   ^
#15 0.627
#15 0.627 Error: Cannot find module '/app/md2html.js'
#15 0.627     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
#15 0.627     at Module._load (node:internal/modules/cjs/loader:1051:27)
#15 0.627     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
#15 0.627     at node:internal/main/run_main_module:28:49 {
#15 0.627   code: 'MODULE_NOT_FOUND',
#15 0.627   requireStack: []
#15 0.627 }
#15 0.627
#15 0.627 Node.js v20.17.0
#15 0.631 mv: cannot stat '*.html': No such file or directory
#15 0.645 node:internal/modules/cjs/loader:1228
#15 0.645   throw err;
#15 0.645   ^
#15 0.645
#15 0.645 Error: Cannot find module '/app/md2html.js'
#15 0.645     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
#15 0.645     at Module._load (node:internal/modules/cjs/loader:1051:27)
#15 0.645     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
#15 0.645     at node:internal/main/run_main_module:28:49 {
#15 0.645   code: 'MODULE_NOT_FOUND',
#15 0.645   requireStack: []
#15 0.645 }
#15 0.645
#15 0.645 Node.js v20.17.0
#15 0.648 mv: cannot stat '*.html': No such file or directory
#15 0.656 error Command failed with exit code 1.
#15 0.656 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#15 ERROR: executor failed running [/bin/sh -c yarn md]: exit code: 1
------
 > [11/11] RUN yarn md:
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yarn md]: exit code: 1

**Comment by gp-it-be** [comment]
I seem to be able to fix that by adding the file md2html.js in the list of files to copy in server.Dockerfile line 8:

COPY cp2static.sh md2html.sh **md2html.js** esbuild.mjs tsconfig.json yarn.lock /app/

**Comment by gbtami** [comment]
After https://github.com/gbtami/pychess-variants/commit/db62f39ab66af6fe60b5fb88cfe0b420dd7080c5 it works for me on Linux again. Feel free to reopen if it has issues on Windows still.

**Comment by gp-it-be** [comment]
On windows I need to convert the lineendings of the file md2html.sh to LF, then it works great now out of the box!

Not too sure if that's an issue because of my git settings (git has some linefeed settings) or something else.

Does it work on linux when you'd convert the file to LF?  If not lets just keep it working on Linux and blame windows users for their choice of OS ;)

**Comment by gbtami** [comment]
Yes, possible your issue is rooted in your git settings because the file contains LF only (I'm working on Linux)
![https://i.imgur.com/xZZDNj2.png](https://i.imgur.com/xZZDNj2.png)
