### ISSUE TITLE
CSS problem on DOBUTSU puzzle

### ISSUE THREAD

**Issue by M-DinhHoangViet** [gbtami/pychess-variants#1641]
**Exact URL where the bug happened**
https://pychess.org/puzzle/UtbLS
**Steps to reproduce the bug**

**What did you expect to happen?**

**What happened instead?**

**Operating system and browser version**
Cốc cốc lastest Windows11

![image](https://github.com/user-attachments/assets/c51b1505-fa12-4388-a483-09fd745781f5)

**Comment by gbtami** [comment]
It works OK on Ubuntu 24.04 using Chromium, Firefox, Brave browsers. It is OK on my very old Huawei mobile as well.
Possible a browser or some browser extension issue on win11.

**Comment by gbtami** [comment]
I suggest to try it with another browser. If that is OK, then you can try to remove the browser extensions you use one by one.

**Comment by M-DinhHoangViet** [comment]
![image](https://github.com/user-attachments/assets/6faeb714-43e3-493b-b4bf-19c58049caf1)
![image](https://github.com/user-attachments/assets/eb9b1213-9067-426a-8f35-cd08a8dd1f0e)

**Comment by gbtami** [comment]
Is this means you solved it?

**Comment by M-DinhHoangViet** [comment]
> Is this means you solved it?

no ![image](https://github.com/user-attachments/assets/23f86967-720e-4c37-b8ea-1a60e82d236a)

**Comment by gbtami** [comment]
The pocket pieces on lichess are not resized along with the board so they can align it with the right side panel.
lishogi and pychess resize pocket pieces along with the board so it can't be aligned with the right side panel.
I don't consider this a bug, but if you can come up with a better layout solution, PR is always welcome.
![https://i.imgur.com/BRztxaJ.png](https://i.imgur.com/BRztxaJ.png)
![https://i.imgur.com/Kjw5tpi.png](https://i.imgur.com/Kjw5tpi.png)
