### ISSUE TITLE
Fog covers the entire screen on correspondence preview

### ISSUE THREAD

**Issue by PLMMJ-FH** [gbtami/pychess-variants#1669]
Title. When I look at a fog of war game from a preview, it shows me naught but fog. Screenshot:
![PychessAllFog](https://github.com/user-attachments/assets/b15c5d43-3e5c-402a-8f86-8ec3dc1ffa13)

**Comment by gbtami** [comment]
This is intentional. 
Calculating visibility info from FEN is allowed in the game play page only to prevent leaking hidden info.
