### ISSUE TITLE
Multiple Ouk Chaktrang (cambodian) puzzles from one game

### ISSUE THREAD

**Issue by PLMMJ-FH** [gbtami/pychess-variants#1670]
There are multiple puzzles from the same game, sometimes even just one move apart.

https://www.pychess.org/pFHwZFhn There are several puzzles from this game, all Rook + King mates. There are others but I forgot game IDs.

**Comment by PLMMJ-FH** [comment]
https://www.pychess.org/nlsFwSRC is one.

**Comment by gbtami** [comment]
Report bad puzzles on our Discord #puzzle-review channel, please.
Some of the admins will delete them. Thx.

**Comment by PLMMJ-FH** [comment]
I do not use Discord.
