### ISSUE TITLE
Squares that you cannot drop a piece to are shown as green when premoving

### ISSUE THREAD

**Issue by PLMMJ-FH** [gbtami/pychess-variants#1675]
Title. When trying to premove drop a Knight in Gorogoro+, for example, the last two ranks show as green instead of blue. Attempting to drop the piece there does nothing.
![Pychess Drop Bug](https://github.com/user-attachments/assets/b07c1923-ccb2-4f06-bb33-01af52531424)
Observed in https://www.pychess.org/Scfiv7em

**Comment by gbtami** [comment]
- Those two squares are green to indicate the last move.

**Comment by randompearl-stack** [comment]
I think PLMMJ-FH was referring to the 1 and 2 ranks, not the 44-45 squares. I could be wrong but the last two ranks comprise the promotion area, and you can't drop pieces there.

**Comment by gbtami** [comment]
Yea, I misread it. Sry.
Those green dots indicate invalid drop squares. In Shogi you are not allowed to drop if that will result an immobile piece there. For example pawns or lances can't be dropped to the last rank or horses to the last two ranks.

**Comment by PLMMJ-FH** [comment]
I got an email from this so I'm just going to drop in and confirm I was talking about the green dots, not the green squares. I wasn't paying enough attention sorry :/
