### ISSUE TITLE
Placement variant name

### ISSUE THREAD

**Issue by ddugovic** [gbtami/pychess-variants#168]
Can we please choose a different name for the "placement" variant?  When developing https://github.com/ddugovic/Stockfish/commit/a43361ef7dbcfa450b2a33e44fca8d78e8ce68ee I saw that names "Bronstein", "Pre-Chess", and "Shuffle" already had this rule set:

> This variant is simply a modification where players take turns placing their back rank pieces. Castling only works when the king and the corresponding rook are in their normal position.

and I saw on the Chess Variants wiki that "placement" refers to a variant where castling is always permitted.  I'd prefer not having to rename the variant in Multi-Variant Stockfish and invent a fifth variant name.

**Comment by gbtami** [comment]
"placement" name was suggested by https://lichess.org/@/boorchess
I'm fine with anything you and @ianfab agree on.

**Comment by ianfab** [comment]
Cutechess, Fairy-Stockfish, pychess, and MV-SF all already use `placement`, so I think renaming it everywhere might be more confusing than just keeping it.

**Comment by ddugovic** [comment]
OK, if I submit a PR to change [PyChess rules](https://www.pychess.org/variant/placement) to match all the other implementations, might it be accepted?

> Different than the “Placement Chess” described on the Chess Variants site, this variant is simply a modification where players take turns placing their back rank pieces. Castling only works when the king and the corresponding rook are in their normal position.

**Comment by musketeerchess** [comment]
Hi 
I think that Bronstein is the most correct name to give to this variant. When reviewing the history of this variant it’s really Bronstein who led this and even won a tournament between very strong masters.

By the way, waiting for gods to add Musketeer Chess !!

Regards

Dr Haddad
www.musketeerchess.net

**Comment by gbtami** [comment]
@ddugovic why not? :)

**Comment by ianfab** [comment]
In which regard do the rules mismatch?

**Comment by CouchTomato87** [comment]
http://mlwi.magix.net/bg/placementchess.htm

**Comment by ddugovic** [comment]
Oh, huh, now I'm looking at SF again and castling rules do seem the same?  I apologize for my confusion.

```
setoption name UCI_Variant value placement
position startpos moves R@a1 R@a8 N@b1 N@b8 B@c1 B@c8 K@d1 K@d8 Q@e1 Q@e8 B@f1 B@f8 N@g1 N@g8 R@h1 R@h8
d
```

```$ cat test.txt - | ./stockfish
Stockfish 2020-03-08 64 BMI2 Multi-Variant by D. Dugovic, F. Fichter et al.
info string variant placement startpos 8/pppppppp/8/8/8/8/PPPPPPPP/8[KQRRBBNNkqrrbbnn] w - -

 +---+---+---+---+---+---+---+---+
 | r | n | b | k | q | b | n | r |
 +---+---+---+---+---+---+---+---+
 | p | p | p | p | p | p | p | p |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 | P | P | P | P | P | P | P | P |
 +---+---+---+---+---+---+---+---+
 | R | N | B | K | Q | B | N | R |
 +---+---+---+---+---+---+---+---+

Fen: rnbkqbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBKQBNR[] w - - 16 9
```
```

**Comment by CouchTomato87** [comment]
https://www.chessvariants.com/diffsetup.dir/baseline.html

Apparently, this version is just one of several possible versions of "baseline chess." I think more specifically "Baseline chess with Fischer rules" https://www.chessvariants.com/diffsetup.dir/baselinef.html

**Comment by ddugovic** [comment]
Yeah... I messed up in Multi-Variant SF; my original plan was to implement "placement" as the Chess Variants Wiki describes, then I changed my mind but still called the variant "placement".

I agree with Dr. Haddad that Bronstein popularized this sort of play and it's a pity I didn't call the variant `bronstein` (despite the clock with the same name) or something else, leaving open the possibility of "placement" being a simpler rule set with 960-style castling.  My confusion challenges our ability to introduce similar variants.

**Comment by ianfab** [comment]
I think placement could still quite naturally be extended e.g. by allowing 960 castling when `UCI_Chess960` is enabled. Whether that is feasible of course depends a bit on which exact version of placement chess we are talking about.

**Comment by gbtami** [comment]
I think the "placement" name is a good choice because it describes well the essence of this variant.
We can use "placement960" similar to "chess960" if we want a Fischer castling variant.

**Comment by musketeerchess** [comment]
Hi
Here is what i suggest: Placement is the Natural choice, but we should pay
credit to Bronstein Also. So let's call it: Placement (or Bronstein) Chess

Best regards

Zied

Le dim. 8 mars 2020 à 23:42, Bajusz Tamás <notifications@github.com> a
écrit :
