### ISSUE TITLE
Makruk piece capturing icon error

### ISSUE THREAD

**Issue by PLMMJ-FH** [gbtami/pychess-variants#1685]
Two bugs with material diplay:
Number one: Capturing a pawn on your opponent's third rank will cause the Ferz icon to appear.
![Pawn Capture icon error](https://github.com/user-attachments/assets/d66a5622-0547-4de9-8f05-d59ed08a2e01)

Number two: Promoting a pawn causes one to appear, overwriting any pawn icons if they are present.

**Comment by gbtami** [comment]
Isn't this the same as https://github.com/gbtami/pychess-variants/issues/1650 ?

**Comment by PLMMJ-FH** [comment]
This is a different but related error as #1650 as that one was about the pieces not resembling their capturing icons and this one is about the pawns' capturing icons being weird.
