### ISSUE TITLE
Rating not updated

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#169]
https://www.pychess.org/F3LiJFLg

I think I clearly see the problem. I resigned in the game, but even though I resigned and it was recognized as a loss, if I go into my profile, it says that the game is still in progress. So I assume that's why the ratings aren't updated....

**Comment by gbtami** [comment]
Fixed by https://github.com/gbtami/pychess-variants/commit/a88a568353f4b06596d74946d9d0595709697bf6
