### ISSUE TITLE
only banner appears on safari ios 15

### ISSUE THREAD

**Issue by guest951** [gbtami/pychess-variants#1699]
**Exact URL where the bug happened**
pychess.org

**Steps to reproduce the bug**
just go to the homepage

**What did you expect to happen?**
homepage displays fully and being able to start games

**What happened instead?**
only banner appears

**Operating system and browser version**
ios 15.8.3, safari

The problem seems to come from the file `pychess-variants.br.js` for which the syntax is not understood on ios 15. It may happen because there is no target parameter given to esbuild, and the default seems to be `esnext` which may include experimental js. It would be better to set the target to something like "es2020" to ensure better compatibility.

**Comment by gbtami** [comment]
It is "ES2017". See https://github.com/gbtami/pychess-variants/blob/master/tsconfig.json#L20

**Comment by guest951** [comment]
The problem is that esbuild uses its own target setting doing the minification, even if ts files are firstly compiled to es2017 compatible js, so the target "es2017" should also be put in https://github.com/gbtami/pychess-variants/blob/master/esbuild.mjs.

**Comment by gbtami** [comment]
Added. May I ask you to test it on https://pychess-variants-dev.onrender.com please?

**Comment by guest951** [comment]
Yes it's working now, I was able to see the whole page and play games!

**Comment by gbtami** [comment]
Thx for your help!
