### ISSUE TITLE
Shogi Analysis - Doubutsu Pieces wrong aspect ratio

### ISSUE THREAD

**Issue by aphirst** [gbtami/pychess-variants#171]
https://www.pychess.org/EnRxJSyX
On move 16, the move suggestion for black move 17. Bad random-mover game, but I happen to have seen the same thing the engine saw.

Engine suggestion:
![4](https://user-images.githubusercontent.com/1735556/76172752-d67e2e80-6190-11ea-8a0e-4af0b441f5a4.png)

Board after making that move:
![3](https://user-images.githubusercontent.com/1735556/76172755-d9791f00-6190-11ea-9345-ccbeccbc1361.png)

Notice how the piece graphic in the suggestion is warped compared to the actual pieces.

**Comment by aphirst** [comment]
If this affects the other piece types, I haven't noticed it. Might be worth inspecting with a fine toothed comb, but it could just be due to some quick of the doubutsu piece graphics themselves.

**Comment by CouchTomato87** [comment]
I wonder if one of the pieces has something in the svg that's outside its boundaries?

**Comment by Fulmene** [comment]
![image](https://user-images.githubusercontent.com/13796147/76187032-d0c33000-6206-11ea-897a-f56b5471dbc2.png)
It certainly affects other piece types.

**Comment by gbtami** [comment]
This seems to be a https://github.com/gbtami/chessgroundx issue.
