### ISSUE TITLE
slow loading of existing bughouse games in round page

### ISSUE THREAD

**Issue by nnickoloff1234** [gbtami/pychess-variants#1737]
in analysis page it seems somewhat faster
check also start of new game - i think still room for improvement there

**Comment by gbtami** [comment]
After https://github.com/gbtami/pychess-variants/commit/4eeb58a20e46ce058500e074c020d519f97f9d70 it is much better now.
`load_game_bug()` is slower a bit compared to `load_game()` because it have to call `piece_to_partner()` and `POCKET_PATTERN.sub()` several times, but that is OK I think.

**Comment by nnickoloff1234** [comment]
Putting my discord message here as well for reference. Maybe another ticket is needed for optimizing this if possible:

ok i took a quick look in the logs and compared with regular single board game:
 - indeed the loading of that bughouse game (and probably any other) is slow (3.767 sec):
```
+0000 2024-12-30 11:51:43.990 [DEBUG] bug.utils_bug:60 load_game_bug parse START
+0000 2024-12-30 11:51:47.757 [DEBUG] bug.utils_bug:254 load_game_bug parse DONE
```
- BUT i believe the slowness comes from the logic for constructing the steps that pushes those steps to fairy stockfish and calls board.is_check, etc.
- difference between bughouse and regular games is that bughouse constructs those steps as part of the load_game method right after it loads it from the database. Regular games postpone that for when those steps are needed. But in logs you can see it is still slow for regular games too. Here it takes 1+ sec for a single board, so not shocking that it take 3-4 sec for 2 boards bughouse:
```
+0000 2024-12-30 12:07:13.011 [DEBUG] game:1005 create_steps() START
+0000 2024-12-30 12:07:14.355 [DEBUG] game:1086 create_steps() OK
```
- I could probably do that lazy initialization of the steps for BugH as well, but not sure what the reason behind it is. other than that i would think about ways to optimize the interaction with fairy stockfish or fairy stockfish itself, not sure what is normal and where delay comes from
