### ISSUE TITLE
Seeks not working half the time

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#174]
Sometimes a player creates a seek and the game doesn't go through. I have no idea how to reproduce this, but it's not uncommon...

This also happened during Yasser's stream with JannLee, but I'm not sure what the cause was. It was a late start by Yasser, maybe that was why?

**Comment by gbtami** [comment]
I don't understand this, sry. Can you explain what exactly "the game doesn't go through" means?

There is 15 min to start playing (make your first move). It was 5 before, but I raised it before the stream expecting Yasser will talk long. And that happened :)
So after 15 min inactivity game was aborted by the server I think.

**Comment by CouchTomato87** [comment]
One game I played, I accepted a seek, and the game opened but the "game start beep" didn't go off. Karagialis didn't see the game despite me seeing it.

A second game a seek was created. I clicked it and nothing happened. It disappeared off the menu though.

**Comment by gbtami** [comment]
Is this the same as https://github.com/gbtami/pychess-variants/issues/141 ?

**Comment by CouchTomato87** [comment]
Yes, that's part of it. Although I guess I'm also adding the fact that seeks don't seem to work from the lobby either -- where a game doesn't even start and you don't even get taken to the game page

I have a hypothesis that maybe having additional tabs of pychess may cause issues. We'd have to explore this further though to be sure.

**Comment by gbtami** [comment]
I think you find the root of this issue. As usual [Dr Watson](https://en.wikipedia.org/wiki/Dr._Watson_(debugger)) :)
Pychess server maintains the last lobby socket only on server side. Meaning the latest lobby tab you opened in your browser. I will try to fix my bad design.
Thx for the hint!

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/d6f8e22be702dfbe902e6d65a61427d9a13c075f
If you still experience this feel free to reopen.
