### ISSUE TITLE
Ingame chat scroll not autoscrolling

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#175]
In one of my games, the ingame chat did not autoscroll to the end when the chat exceeded the size of the chatbox

**Comment by gbtami** [comment]
I can't reproduce this. Can you?

**Comment by CouchTomato87** [comment]
It's happening in all my games

**Comment by gbtami** [comment]
OS? Browser?

**Comment by CouchTomato87** [comment]
Win 10, Chrome (latest version)

**Comment by gbtami** [comment]
Still can't reproduce (Win10 + latest Chrome). Just tried a game against Random-Mover.
Can you provide more info, please?

**Comment by matuser2** [comment]
I attached a recording of the problem.
I hope it helps.

![game chat scrolling](https://user-images.githubusercontent.com/62706578/101001693-1f201800-3568-11eb-9e31-92cdc821a1f5.gif)

**Comment by gbtami** [comment]
What OS, browser are you using here?

**Comment by matuser2** [comment]
Windows 10 and google chrome

**Comment by gbtami** [comment]
Thx, will try that combo again.

**Comment by gbtami** [comment]
Seems OK now. I think responsive CSS changes fixed it.
If anyone see this again, feel free to reopen.
