### ISSUE TITLE
Toggle computer analysis arrow

### ISSUE THREAD

**Issue by catask** [gbtami/pychess-variants#176]
It's no big deal, but sometimes it would be nice to have a pure diagram without any arrow as after running a computer analysis on a game, every move has an arrow. This feature would be useful for creating high quality diagrams simply by screen grabbing the current position, but there wouldn't be any arrow.

![image](https://user-images.githubusercontent.com/58996479/76722750-e8bd1700-6712-11ea-89ed-d1ab24f234cd.png)
As you can see here there is already an arrow for Ee6. Again not a big deal :)

**Comment by gbtami** [comment]
Fixed via "Save position to PNG" commit  https://github.com/gbtami/pychess-variants/commit/b6167e1800eb89b762bf2994e178b98f87dc1b53
