### ISSUE TITLE
Multiple seeks

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#177]
If someone does multiple seeks and starts a game, then the other games should be canceled. Maybe this can also be defined for time control -- as in any game that is not correspondence, just so that this more robust for whenever that's available

**Comment by gbtami** [comment]
User seeks removed when user starts to play or analyse a game. Can you produce case when this is not true?

**Comment by CouchTomato87** [comment]
This happened when we played Shogun... You were in a game with Jarl, but Jarl's 5+5 shogun seek was still in the lobby.

I wonder -- did you create a seek and Jarl created one after but then joined your game? In the case, he didn't have multiple seeks, but he joined a different game instead.

**Comment by gbtami** [comment]
Did you have more than one lobby tab open? If yes, then this may be the same issue as https://github.com/gbtami/pychess-variants/issues/174

**Comment by gbtami** [comment]
If you still experience this feel free to reopen.
