### ISSUE TITLE
Board editor

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#178]
- [x] Western chess variants
- [x] Makruk: M~ vs F in FEN
- [x] Xiangqi: DnD not correct in chessgroundx when board ranks >= 10
- [x] Shogi: "everything is opposite" issues
- [x] FEN validation to prevent server crash
- [ ] Disable (and notify) anon users they can't create new games from editor

**Comment by Fulmene** [comment]
Regarding variant specific FEN validation:
Is there anything else aside from xiangqi's palace-bound pieces and other variant's pawn on last row that @CouchTomato87 mentioned? For xiangqi pieces, it should be fine as long as Fairy-Stockfish doesn't crash, right? Current behaviour that I know of is the bound pieces can't move at all outside of their boundary and that's it, so I don't feel it's necessary to check. Same for last row pawn tbh.

Maybe you should mention that the FEN validation's objective is just to prevent server crash.

**Comment by gbtami** [comment]
Yes, the FEN validation's objective is just to prevent server crash.

**Comment by CouchTomato87** [comment]
One more feature -- some way to make it clear that the "play with machine" feature can only be used when logged in? Maybe if you're not logged in, it becomes unclickable and says "Play with machine (must be signed in)" instead?
