### ISSUE TITLE
Guides for games

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#18]
Here is what I have for my shogi guide. The txt file is in Github markdown, but I'm not sure what to do from there. There are image placeholders, but I don't know the exact directory for the images. Hopefully you know what to do do about that. :)

[ShogiGuide.zip](https://github.com/gbtami/pychess-variants/files/3528021/ShogiGuide.zip)

Also, on an unrelated note. I checked the white elephant and the borders are exactly the same as other pieces (6 px wide), so I don't know why it appears thicker in the game. Might as well leave it as is though. I should mention that the Capa sets  aren't updated with the newest elephants/hawks though.

**Comment by gbtami** [comment]
Thx!
Created a new wiki page for this at https://github.com/gbtami/pychess-variants/wiki
There you can edit the text as you like (after you accept invitation sent).
I'v uploaded the .png images to the repository here https://github.com/gbtami/pychess-variants/tree/master/static/images/ShogiGuide and linked images there.
Btw Bishop.png (the movements) is missing from .zip!

When we will have a page/menu for variants on the site I will add this as https://pychess-variants.herokuapp.com/variant/shogi and will link it from game info headers.

**Comment by gbtami** [comment]
I can't see the white elephant issue. Can you create a screenshot demonstrating it please?

Regarding Capa sets we have only one source .svg files for elephants/hawks. Maybe you just have to update your browser pages or clear browser cache.

**Comment by CouchTomato87** [comment]
Added the bishop image. The next big one eventually will be a xiangqi guide.

And I think the white elephant is really just my perception. I think my eyes are playing tricks on me because the pieces look similar.

**Comment by gbtami** [comment]
Until I find a better solution I added the Shogi-Guide to https://pychess-variants.herokuapp.com/about
It uses https://docsify.js.org/

**Comment by gbtami** [comment]
You have to refresh that About browser page to get the latest.
Btw now the site presents .md from https://github.com/gbtami/pychess-variants/tree/master/static/docs
You can think about these that .md on Wiki is your development version and .md on main repo is the production version. You can work on the former without users seeing it on the site and when you think it's OK we can copy it to the main github repo and finally I push it to Heroku.

shouse is come from ianfab, I just started to use it :)

**Comment by gbtami** [comment]
Heh, after rethinking it we can drop the wiki version and you can work on .md in the main repo.
It has the same preview feature there.

**Comment by gbtami** [comment]
Sry, my bad. I'm still learning to configure docsify. Iwas experimenting with `alias`. Of course it doesn't work for image links and my browser cheated me showing images from cache. Should work now.

**Comment by CouchTomato87** [comment]
Xiangqi guide is up now. I was inconsistent with the images and will need to fix them, but they still work overall

**Comment by gbtami** [comment]
This is awesome, thx a lot!

**Comment by CouchTomato87** [comment]
I updated the images now. Next up for the Wiki I guess would be all the chess variants. I asked Jarl if he would be willing to provide some strategy if possible :)

**Comment by gbtami** [comment]
Good idea! :)

**Comment by gbtami** [comment]
Btw. I thought you want to use your new pieces in movement images similar to Shogi-Guide.
If you don't want, no problem, just noticed this difference.

**Comment by CouchTomato87** [comment]
I was considering it, but most guides actually don't use images for xiangqi because the movements are very straightforward (unlike in shogi which has more pieces and more unique moves). At some point I can probably redo the images I used from Wikipedia with my pieces instead, but I figured these would be good enough for now. ;)

**Comment by gbtami** [comment]
Deployed first version of your Variants Guide (fixed image links). Looks great!

**Comment by gbtami** [comment]
In Seirawan section it say:
"Instead, when a piece in a player’s first rank moves, these pieces may optionally come into the square evacuated by that piece."

Shouldn't it be:
"Instead, when a piece in a player’s first rank moves the very first time(!), these pieces may optionally come into the square evacuated by that piece."

And maybe a sentence something like "If you move all your officers without gating H/A you lose the right to introduce/use them later."
I'm not sure about the wording. What do you think?

**Comment by CouchTomato87** [comment]
You're right, I totally forgot to mention that! I updated the guide (and also threw on a little strategy)

**Comment by CouchTomato87** [comment]
I also added some strategy to other variants courtesy of Jarl

**Comment by gbtami** [comment]
Maybe better to make a new button for "How to play". I'm still hesitating...

**Comment by CouchTomato87** [comment]
Maybe you can poll the audience and see what they'd like :)

**Comment by gbtami** [comment]
Made a new button for "How to play".

**Comment by gbtami** [comment]
Updated Xiangqi-Guide is wonderful!
Deployed.

**Comment by CouchTomato87** [comment]
Guides are committed for Makruk and Sittuyin now

**Comment by gbtami** [comment]
Updated Shogi-Guide with link to "Peter Heine Nielsen on Shogi" article

**Comment by CouchTomato87** [comment]
Makruk and Sittuyin guides are now updated with Entitled-Untitled's additions
