### ISSUE TITLE
i mean , can make it think deeper or wider ? it can take more time. 

### ISSUE THREAD

**Issue by zekeliu** [gbtami/pychess-variants#182]
In chess you have no control on your opponent time usage, see Nepomniachtchi :)
In theory we can slow down AI in pychess.org but it needs additional code to manage its time usage to not lose on time. I don't think it worth the effort at all.

_Originally posted by @gbtami in https://github.com/gbtami/pychess-variants/issues/181#issuecomment-601561334_

**Comment by gbtami** [comment]
No.

**Comment by zekeliu** [comment]
but the highest level is 8 , right ?

**Comment by gbtami** [comment]
Yes. The UCI parameters used for AI levels are here https://github.com/niklasf/fishnet/blob/master/fishnet.py#L116
