### ISSUE TITLE
New piece set for Sittuyin

### ISSUE THREAD

**Issue by Ka-hu** [gbtami/pychess-variants#193]
I made a new/modified version of the sittuyin pieces, I offer them as a replacement or as an alternative to the 'original'. I made a green&red version and also a black&red version. (I prefer the black version). Some of these modifications are inspired by [this image](https://i.imgur.com/H2TCSUq.jpg) (the pawn/feudal lord for example).

[Screenshot gallery](https://imgur.com/a/7jgnP0B).

**Comparison**:
![https://i.imgur.com/jAgUmeD.png](https://i.imgur.com/jAgUmeD.png)

You can try them out with these userstyles:

[Pychess-Variants Sittuyin Green-Red pieces](https://userstyles.org/styles/181745/pychess-variants-sittuyin-green-red-pieces)
[Pychess-Variants Sittuyin Black-Red pieces](https://userstyles.org/styles/181744/pychess-variants-sittuyin-black-red-pieces)

If you accept my pieces, you can find them in my [chess-pieces repository](https://github.com/Ka-hu/chess-pieces) 
(I also made another light colored [board](https://github.com/Ka-hu/chess-pieces/blob/master/boards/sittuyin.svg) for sittuyin).

**Comment by gbtami** [comment]
May I ask you to create a PR please?
You can find a similar one at https://github.com/gbtami/pychess-variants/pull/135

**Comment by gbtami** [comment]
Great contribution! Thx a lot.
