### ISSUE TITLE
Shogi - Drop pawn mate (uchifuzume) rule

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#199]
Drop pawn mate (uchifuzume) rule is currently not implemented. The rule is that a dropped pawn cannot (immediately) cause mate. Doing so would be illegal. In 81dojo or OTB, the player dropping the pawn would immediately lose. Pychess has protected players from making illegal moves. I'm not sure if this is possible per discussion on Discord, but if this is not, then this would have to go the 81dojo way and cause a loss for the pawn dropper.

**Comment by ianfab** [comment]
@gbtami This can be fixed by replacing the custom checkmate/stalemate handling in pychess by calling the new `game_end` method from pyffish to determine the game result.

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/03130d859319b0cbb8c9f7a0758922158e6236de
