### ISSUE TITLE
Byo-yomi improvements

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#209]
- [x] Change "increment" to "byo-yomi" in dialog box for starting games

- [x] When in byo-yomi, the clock background becomes yellow. For dark theme, perhaps a dark yellow?

- [x] When not in byo-yomi, also make it clear what is coming up when that happens... So possibly after the time it would say "+60 s"

- [x] Possibility of multiple byo-yomi? So to add on the above item, if there are 3 byo-yomi, it would be "+60 s (x3)" and this would stick around at the first byo-yomi and so on until you're on your final byo-yomi.

- [ ] Sound effects: Using the LowTime.mp3 when you run out of base time. Also using the countdown mp3s from 1-10 seconds. Maybe in the future have the option to have Japanese and Korean voices?

**Comment by Ka-hu** [comment]
> Sound effects: Using the countdown mp3s from 1-10 seconds. Maybe in the future have the option to have Japanese and Korean voices?

This for japanese? https://freesound.org/people/Reitanna/sounds/235106/
Maybe someone with audio editing experience could clear this up a bit and cut out 1-10 seconds.

(I guess Madoka Kitao's voice from 81Dojo cannot be used.)

**Comment by gbtami** [comment]
@Ka-hu perfect! :)

**Comment by gbtami** [comment]
I think we should add simple bip-bip-bip... for latest 10s until we don't have regional counting samples.

**Comment by Ka-hu** [comment]
Yes, the "beep" sound is important, especially in tournaments. Time out occurred during the first janggi tournament: https://www.pychess.org/LErk3AUQ

**Comment by CouchTomato87** [comment]
I don't think there should be issues with the available English sounds either. Almost everyone should know how to count in English.

**Comment by CouchTomato87** [comment]
One more request -- Turn off the sound effects and red background for the base clock if byo-yomi is available... It's confused the heck out of me multiple times when the clock was counting down.

**Comment by Fulmene** [comment]
I think this issue should be closed for the time being. More specific issues about byoyomi can be filed separately.

**Comment by CouchTomato87** [comment]
Can we do that last request first? :(

**Comment by Fulmene** [comment]
It'll be seen more easily if the issue title actually says what specific thing needs to be fixed :)

**Comment by Fulmene** [comment]
@CouchTomato87 I implemented that last request so let's close this for now.
