### ISSUE TITLE
New / updated settings menu

### ISSUE THREAD

**Issue by Ka-hu** [gbtami/pychess-variants#220]
(Not Lichess-like topnav settings yet, that would require much more work)

I changed the settings panel to have separate menus for pieces, boards, etc. Now each menu has its own "content block" and this way we have plenty of room for other piece sets, boards, options, etc. The zoom slider is still visible the default (no reason to hide it under a menu I guess).

Side note: I made an alternative sound theme (see the  .gif) and tested that, too.

[Animated GIF](https://i.imgur.com/B22u1mq.gif)  (the pieces and boards are duplicated for testing purposes, it's not a bug)

Opinions?

![screenshot](https://i.imgur.com/Jpi8xRK.png)

**Comment by gbtami** [comment]
Not bad, but I prefer to implement lichess-like topnav instead, to let users feel they are at home.
(I know what we have now is just a temp hack though.)
