### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#224]
Allow support for different languages. Given we have a lot of guides here, it may take somewhat of an involved effort. But for starters, maybe we can have level 1 involvement (interface + about page translation only) and level 2 (level 1 + guides).

Key languages (other than English) and possible sources include:

-French (benjamin?)
-Spanish
-Simplified Chinese (ilion?)
-Traditional Chinese (ilion?)
-Korean (any Korean here at least for level 1?)
-Japanese (aphirst for level 1?)
-Vietnamese
-Thai (furumin!)

I think additional languages can be provided as long as people are available. Gbtami and ianfab (maybe also Licetus/DreamPwner) could easily provide Hungarian and German translations, respectively. Galdian could do Polish, although he may only have time for level 1.

**Comment by Marken-Foo** [comment]
I (Illion) can do Chinese, and Japanese level 1, and French any amount (but benjamin would be better at it).

**Comment by kezsulap** [comment]
I (e-pluszak/oxytocyna) could do Polish level 2

**Comment by gbtami** [comment]
I'v created  https://www.transifex.com/gbtami/pychess-variants/
If you want to translate pychess create an account on transifex and join to pychess translators team!
