### ISSUE TITLE
chess games saved as Makpong

### ISSUE THREAD

**Issue by catask** [gbtami/pychess-variants#225]
https://www.pychess.org/@/catask

In the past two days the games I played vs Fairy-Stockfish are shown as Makpong instead of chess. The final game position sometimes resembles the final chess position, in other cases some pieces are missing. When clicking on the game, it shows the start position with ([color] resigned).

**Comment by gbtami** [comment]
Thx! Will fix it rn.

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/c32f3d74ec970180e86028fa65949e466956a95e
Will deploy tomorrow.
