### ISSUE TITLE
Chat keeps repeating

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#235]
![image](https://user-images.githubusercontent.com/52322435/80804215-78633b80-8b82-11ea-9b76-26784acbe7f6.png)

**Comment by gbtami** [comment]
In theory this is fixed now. Can you confirm it?

**Comment by ianfab** [comment]
For me it is not reproducible any more.

**Comment by ianfab** [comment]
@CouchTomato87 I guess we can close this?
