### ISSUE TITLE
Notation regressions

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#236]
There has been a notation regression for Shogun, where the pieces are now just "+X" instead of Q, M, A, C, G, etc.

Also, Makruk is using "S" for the Bishop, which I'm pretty sure is not correct.

**Comment by gbtami** [comment]
Can you file this in https://github.com/ianfab/Fairy-Stockfish/issues please?
Notations are coming from pyffish and it is in Fairy-Stockfish now.

**Comment by Fulmene** [comment]
Makruk has been using S (silver) for the khon from the start. Any letter is actually fine since there's no standard English notation for it.

**Comment by ianfab** [comment]
Please continue discussion in https://github.com/ianfab/Fairy-Stockfish/issues/120
