### ISSUE TITLE
Un-split sentences to improve localisation

### ISSUE THREAD

**Issue by Fulmene** [gbtami/pychess-variants#238]
Different languages have different sentence structures. It's better to translate each sentence as a whole than split up parts. This means favouring string formatting over concatenation.

**Comment by gbtami** [comment]
Are there other problematic occurrences besides results in profile page?

**Comment by Fulmene** [comment]
I just named the issue very generally to be a reference when more texts are added.

Besides the results, I also expressed my concerns about the time control prompt [here](https://discordapp.com/channels/634298688663191582/707260161621885049/707992259098050560).

**Comment by gbtami** [comment]
I think all fixed now.
If you find anything remaining feel free to reopen.
