### ISSUE TITLE
Incorrect game status in users profile game list 

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#24]
Sometimes it is "Playing right now", but if you open it it will be "Time out"
https://pychess-variants.herokuapp.com/l4JVogtw

**Comment by gbtami** [comment]
In exported mongodb game collection this game is not started and has no moves at all. Strange.

**Comment by gbtami** [comment]
After server restart it shows the same as my local server using exported games.
Seems after started game was inserted to db and couple of move was made in game, BOT stalled and the game was adjudicated bot NOT saved later to the db. And while it was served from server cache(dict) it was able to show the taken moves and adjudicated result.

**Comment by CouchTomato87** [comment]
Not sure if this is related, but in one game that was aborted midway, the kifu/game log does not show up:
https://pychess-variants.herokuapp.com/k2cePk4z

**Comment by gbtami** [comment]
On server shutdown-restart (initiated by Heroku) all ongoing games are aborted (and saved to the database), but later on client side loading move list was interrupted immediately if status was "aborted". Not related but fixed in https://github.com/gbtami/pychess-variants/commit/fc40d7d33ef83bcf833c6aa43c328e35f11df93e(not deployed yet!).
Thx for the notice!

**Comment by gbtami** [comment]
I think https://github.com/gbtami/pychess-variants/commit/302371cead8834a9ae1f19aa7d54b6d9f9bf3ea9 fixed this also.
