### ISSUE TITLE
Additional variants

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#25]
Any chance we can get grand chess, minishogi,and kyoto shogi, which are on Fairy? :)

**Comment by gbtami** [comment]
I promised Grand to Jarl so I will start with that first.

**Comment by ianfab** [comment]
Since you mentioned kyoto shogi, it reminded me that there was some fishy behavior of the search for micro- and kyotoshogi in Fairy-SF. I just fixed a bug for those two variants, and it looks stable now, so it could perhaps be used for pychess-variants. Minishogi and grand chess should anyway be stable.

**Comment by CouchTomato87** [comment]
Just a notational issue for Grand Chess... the pieces are classically referred to as Marshal (chancellor) and Cardinal (archbishop), and so the notation should also reflect that.

(Source: https://en.wikipedia.org/wiki/Grand_Chess )

**Comment by gbtami** [comment]
This is coming from Fairy-Stockfish. See https://github.com/ianfab/Fairy-Stockfish/blob/master/src/variant.cpp#L594

**Comment by CouchTomato87** [comment]
Yeah it was more directed for ianfab ;)

**Comment by ianfab** [comment]
Cutechess and XBoard use A/C instead of C/M for grand chess, so I did the same. We should not break compatibility here.

**Comment by gbtami** [comment]
Agreed.

**Comment by CouchTomato87** [comment]
That's a fair point, agreed as well. I guess we'll just blame the cutechess and xboard guys for disrespecting Christian Freeling's game deisgn ;)

**Comment by CouchTomato87** [comment]
One thing I forgot to ask before regarding the 5x5 stuff... Would a board be confined to a 5x5 size, or do you have room to add a little border (perhaps using unclickable dead squares or something)?

![MiniboardWood2](https://user-images.githubusercontent.com/52322435/65293936-e9da0680-db2a-11e9-8c60-cb1568d558bd.png)

vs 

![5x5Wooden2Border](https://user-images.githubusercontent.com/52322435/65293942-ecd4f700-db2a-11e9-91c1-e0677c913689.png)

**Comment by gbtami** [comment]
Chessground does not support any form of border.
Just notice that Xiangqi is not exception. It uses 9x10 boards. The grid lines of boards are never used by chessground for anything.

**Comment by CouchTomato87** [comment]
Alright, good to know :)

**Comment by CouchTomato87** [comment]
Whenever you get a chance, I have the boards and favicons for 5x5 shogi variants. I also have a unique set for Kyoto shogi ready to go whenever that gets implemented.  

[Shogivariants.zip](https://github.com/gbtami/pychess-variants/files/3680932/Shogivariants.zip)

**Comment by gbtami** [comment]
Thx a lot! I will add them soon.

**Comment by CouchTomato87** [comment]
[5x5Boards.zip](https://github.com/gbtami/pychess-variants/files/3718633/5x5Boards.zip)

Try these boards now

**Comment by gbtami** [comment]
Deployed, thx!

**Comment by CouchTomato87** [comment]
[Kyoto.zip](https://github.com/gbtami/pychess-variants/files/3746754/Kyoto.zip)

If you're able to get Kyoto Shogi able to work, I made these pieces... They'd probably have to be separate from the other shogi games -- like probably a different standard similar to how chess and makruk are both 8x8 but use different pieces. I didn't include kings, but those would be the same as the 1 kanji king or the international (colored) king

**Comment by gbtami** [comment]
I haven't started to implement Kyoto yet.
Looks great, thx!
