### ISSUE TITLE
Enhance drop move highlight

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#27]
@CouchTomato87 
"Speaking of last move highlights, if there was a drop, could we get a highlight from the corresponding spot in the pieces in hand? I often get confused if there was a drop or not because if there is a green piece in the middle of the board, I have to check all corners to make sure it just wasn't a long move."

**Comment by ddugovic** [comment]
Yeah, especially for spectators (who aren't expecting a drop) this would be a nice quality of life enhancement.

I took a look at the codebase however I assume chessground doesn't manage the pocket, and there are multiple files which set `lastMove`, so I gave up trying to implement this.

**Comment by gbtami** [comment]
Yep, implementing this feature needs to add lastMove to RoundController/AnalysisController classes to let pocketView() in pocket.ts have a chance to add a new css class to pocket piece type involved.

Btw adding different (new!) sound to drop moves may also help here IMO.
