### ISSUE TITLE
Insufficient material claimed incorrectly

### ISSUE THREAD

**Issue by kezsulap** [gbtami/pychess-variants#276]
https://www.pychess.org/dAaqVpV7
https://www.pychess.org/FGwvwmWq
The server assumes K+N is insufficient always even if opponent material allowing to checkmate. (in those games I posted side with knight only has an immediate forced mate, but the game ended in a draw immediately if oponent also has material which is supposed insufficient, or on timeout otherwise)

**Comment by gbtami** [comment]
Nice catch, thx!

**Comment by gbtami** [comment]
Moved to https://github.com/ianfab/Fairy-Stockfish/issues/139
