### ISSUE TITLE
Links to games when you're not logged in don't work

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#287]
Whenever you open a link directly to a game, it does not worked if you're not logged into that browser. You have to open the link twice, for some reason, to go straight to the game.

**Comment by gbtami** [comment]
"open a link directly to a game"
What this exactly means? Step-by-step please :)

**Comment by CouchTomato87** [comment]
Just click any link to a game, like https://www.pychess.org/rKFt6HPg

If your default browser is not logged in, it just goes to the lobby the first time you open the link

**Comment by gbtami** [comment]
Works for me. I need more info.

**Comment by CouchTomato87** [comment]
Did you just log off? I suspect it may be because it's still in your history. My default browser is Firefox even though I normally use Chrome, so links open in Firefox. I also have the same problem in my phone with Chrome, where I'm not logged in

**Comment by gbtami** [comment]
Yes. Tried below steps with Firefox and Chromium.
1. I logged off. 
2. Opened this github issue
3. Clicked on game link above.
Worked Ok.

**Comment by gbtami** [comment]
Finally was able to reproduce this.
It happens when you are on a page which has no websocket connection to the server (lobby and game pages have, others don't) and server restarts.
