### ISSUE TITLE
Use actual icon in the topnav settings menu's "back" button

### ISSUE THREAD

**Issue by Fulmene** [gbtami/pychess-variants#291]
![](https://cdn.discordapp.com/attachments/641327060090093581/727231955782860880/unknown.png)

**Comment by gbtami** [comment]
You can use left,right,heart icons added by https://github.com/gbtami/pychess-variants/commit/8f8fe9848a788ce2280d39d961f9acd214dafa25
Maybe we should left align menu items and add right arrow similar to lichess?
![https://i.imgur.com/s0Rv6jN.png](https://i.imgur.com/s0Rv6jN.png)
![https://i.imgur.com/eD3yZlz.png](https://i.imgur.com/eD3yZlz.png)

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/d59341f3a4e56163895d6cc157444c9125981883
