### ISSUE TITLE
Variants needs stylized icons

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#3]
Something like these, but for Makruk, Shogi etc.
![icons](https://user-images.githubusercontent.com/479964/60735993-bf2dd800-9f55-11e9-9a64-c9fe5877707b.png)

**Comment by CouchTomato87** [comment]
[Icons.zip](https://github.com/gbtami/pychess-variants/files/3365891/Icons.zip)

Here is a draft of icons. I included two different shogi ones, one with a king and one with an international-style gold general by request. I prefer the king since it's universal, but I can leave the choice up to you.

**Comment by gbtami** [comment]
Seems app.fontastic.me import has minor problems with capablanca and placement icons and major problems with makruk, sittuyin and xiangqi ones.
![fontastic](https://user-images.githubusercontent.com/479964/60772285-5a5cb400-a0f4-11e9-8a46-7fcf66a626ba.png)

There is a faq with some suggestions here: http://fontastic.me/faq

**Comment by gbtami** [comment]
Regarding the draft I like the seirawan, crazyhouse, makruk, sittuyin, shogi and xiangqi icons. (I agree with you that using shogi king is better choice.) Maybe one simple arcbishop alone for capablaca would be better in my opinion. For placement I have no better idea :)

**Comment by gbtami** [comment]
I find this issue https://github.com/andreaskoller/Fontastic/issues/1
After removing capablanca and placement icons from selection I was able to download crazyhouse, seirawan, shogi aand standard. They are committed and you can see them in game info panel now.
![shogi](https://user-images.githubusercontent.com/479964/60774693-41fe9080-a118-11e9-8fb6-19baed4a1dc8.png)

**Comment by CouchTomato87** [comment]
Cool! I'll try to redo the other ones. I think for Xiangqi, I forgot to turn the text into a path. Also, I'm working on hawk and elephant pieces you can use for S-chess, but not sure where I should put them when I'm done.

**Comment by gbtami** [comment]
Btw if you sign up to fontastic.me (it's free) you can try to import icons yourself to see are they OK or not.
http://fontastic.me/faq
If you have problems just join to PyChess on discord at https://discord.gg/Yxn7V2z

**Comment by gbtami** [comment]
Regarding hawk and elephant you can use github itself :) It's easy!

0. Install git on your local PC
https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
1. Create your own fork of this project
Just click on "Fork" button at the top right, next to the "Stars".
2. Create local clone to your PC of your fork
`git clone https://github.com/CouchTomato87/pychess-variants.git`
3. Go to your the just created local copy of this repository
`cd pychess-variants`
4. Create and  move new .svg piece files into `static/images/pieces/merida`
5. Add new files to your local git repository
`git add static/images/pieces/merida/*.svg`
6. Commit it
`git commit -m "Some descriptive short message what is this" static/images/pieces/merida/*.svg`
7. Push to your local changes to your github repository
`git push`
8. Create a pull request to this upstream repo by clicking on "New pull request" button.

**Comment by CouchTomato87** [comment]
I got a little lost after installing. I tried putting them on github after forking, but I have no idea if I'm doing this right. All this is a little beyond me haha.

**Comment by CouchTomato87** [comment]
Here are the fixed icons. The problem was that a stroke completely messed up the icon. I also included the elephant and hawk in case my sad attempt at a pull request didn't work. 
[Icons 2.zip](https://github.com/gbtami/pychess-variants/files/3370997/Icons.2.zip)

**Comment by gbtami** [comment]
No worries :) Hawk and elephant are cool, thx a lot! (I just noticed that elephants are looking to the right while knights and hawks to the left.) I'v committed them so you can try them now.
Still no luck with fixed icons on fontastic.me Download timeout :(

**Comment by CouchTomato87** [comment]
No problem! And sorry, the direction totally slipped my mind. Here are the fixed images. I also slightly tweaked the black hawk as well. 
[ElephantHawk.zip](https://github.com/gbtami/pychess-variants/files/3372765/ElephantHawk.zip)

**Comment by gbtami** [comment]
Thx! I"m in summer karate training camp this week. Next time is sunday I can try your work.

**Comment by gbtami** [comment]
Elephants committed. The black hawk is the same as before in this .zip file.

**Comment by CouchTomato87** [comment]
The black hawk is very slightly different. The mouth has been adjusted so that it's smoother.

**Comment by CouchTomato87** [comment]
Actually, I will probably have to do slight readjustments anyways... The OCD part of me sees that their vertical alignment is not consistent with the other pieces, so I'll have to fix that.

**Comment by CouchTomato87** [comment]
Here it is -- hopefully the last! I also resized the elephants and aligned them as much as I could with the other pieces. I forgot that unlike xiangqi and probably shogi, the chess pieces aren't center aligned.
[ElephantHawk3.zip](https://github.com/gbtami/pychess-variants/files/3390259/ElephantHawk3.zip)

**Comment by gbtami** [comment]
Committed, thx!

**Comment by gbtami** [comment]
Finally was able to fix some icons to let fontastic love them :)
If you feel any piece or icon needs more adjustment feel free to reopen this issue.
