### ISSUE TITLE
Game previews in "Current Games" could use an icon

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#300]
Now that board styles are uniform across variants, it's harder for me to tell what games people are playing on current games. For example, most of the 8x8 non-Tomato chess variants are indistinguishable, the 10x8 ones are indistinguishable, and Makruk/Makpong/Cambodian are indistinguishable.

Suggestion: Use the icon (or even variant name -- there is a lot of space!) in the top right of that box to signify the variant. Or perhaps have the player names be center or right-aligned, and have the icon in the top left.

Additionally, maybe the TC can be in the other corner?

**Comment by Fulmene** [comment]
I don't think time control is necessary. It'll clutter the UI without sufficient benefits.
