### ISSUE TITLE
Add alternate start name to interface

### ISSUE THREAD

**Issue by Fulmene** [gbtami/pychess-variants#311]

**Comment by gbtami** [comment]
As Tomato suggested we should use the "mode" everywhere similar to lobby.

**Comment by randompearl-stack** [comment]
This has been completed, right?

**Comment by gbtami** [comment]
No, it isn't.
Here is an example. I choose to play a 10 piece handicap shogi game:
![https://i.imgur.com/bL1kD2r.png](https://i.imgur.com/bL1kD2r.png)
But "10-Piece HC" is not shown here:
![https://i.imgur.com/YZ9ETs2.png](https://i.imgur.com/YZ9ETs2.png)
and here:
![https://i.imgur.com/807MZ8Y.png](https://i.imgur.com/807MZ8Y.png)
