### ISSUE TITLE
Remove ffishjs and stockfish.wasm files from git

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#329]
When they will be available from npm.
- [x] ffish.js
- [ ] stockfish.wasm

**Comment by SriMethan** [comment]
Seems this is not fixed yet.

**Comment by gbtami** [comment]
It is fixed. See https://github.com/gbtami/pychess-variants/commit/8a577d0913404af5267d4fe0e62cbefaa9529037#commitcomment-73563984
