### ISSUE TITLE
Games ending at the start

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#33]
This is probably known already, but this especially happens with new players... When a game is started, no one makes a move (not sure if it's because they can't), and then the game ends a few seconds later.

There was also one problem where a user was playing but it still listed him as anonymous when he chatted: https://pychess-variants.herokuapp.com/e4wE2Pub (in the game it listed him as ohioshogi, but in the game record he's still anonyous)

**Comment by gbtami** [comment]
Yes I also regularly see abandoned games from time to time. But all these games are human vs BOT games. I can imagine that new users just start some variants from lobby to see "what is this" then just close that browser tab. 
If your use case is different (human-human) I need more info to be able to reproduce it.

I don't know what to do with this. ohioshogi has no shogi game in his profile game list and the linked game he is anonymous.

**Comment by CouchTomato87** [comment]
It's actually mostly been human-human for me. I've never had issues against the bots. Sometimes I have the issue with Jarl too, and we're like "I dunno what just happened." But the games never get logged I think if you look at our history.

**Comment by gbtami** [comment]
Games shorter than 3 moves are never saved to database.
There is a time limit (20 sec?) for both players to appear in a new game. After that game will be aborted by server. But this should be written on the move list panel.

Anyhow, when this happens again open your browsers Web Console (Ctrl+Shift+K in Firefox, Ctrl+Shift+I in Chrome) and cope-paste the logs here. It may help to find what is the problem.

**Comment by CouchTomato87** [comment]
Thanks, will do that!

**Comment by CouchTomato87** [comment]
I'll leave this here for the record... Timed out on turn 2 after both players had moved: https://pychess-variants.herokuapp.com/WyvjrXxM

**Comment by gbtami** [comment]
I think https://github.com/gbtami/pychess-variants/commit/302371cead8834a9ae1f19aa7d54b6d9f9bf3ea9 fixed this also.
If you see this again feel free to reopen.
