### ISSUE TITLE
Bug: custom positions not respected in S-Chess or S-House

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#351]
The editor allows players to set up their own positions in various variants. In s-chess or s-house, this is not respected as editor changes to standard s-chess and s-house starting positions are denied. This is not logical and inconsistent since Pychess does allow Crazyhouse 960. S-Chess and S-House deserve the same courtesy that Crazyhouse 960 is afforded.

**Comment by gbtami** [comment]
Can you provide the FEN having this issue, please?

**Comment by Curious2021** [comment]
The issue is reproducible. Choose a game against Stockfish using either s-chess or s-house. Then choose the editor to “edit” the starting positions to your liking. For example, manually create a chess 960 position using the editor while in s-chess or s-house mode. In both variants the elephant and hawks are not visible in the reserve and although you can set up the chess 960 positions the editor does not allow you to play these positions with the s-chess or s-house variants even though it should be legally allowed to manually set these non standard positions.

**Comment by gbtami** [comment]
S-chess960 and S-house960 are not supported on pychess site. This means nor Fischer random castling nor rematch from same starting position (just reversed colors) are not implemented.
But custom starting positions are supported. If you provide a custom FEN causing any issue let us know please.

**Comment by Curious2021** [comment]
I don’t need Fischer Random castling rules nor do I need them when setting up nonstandard positions. In fact it’s not required for the purpose of setting up non standard starting positions. After all you have placement chess which allows non standard positions but no castling allowed. Why can’t placement chess setups be allowed in s-chess or s-house. So forget the castling rules for a minute and explain why the forbidden rule of not allowing non standard starting setups without castling rules?

**Comment by gbtami** [comment]
Here is a non standard setup S-chess game I played at this moment https://www.pychess.org/vDq5O7k1?ply=0
Maybe the problem is misunderstanding of S-chess FEN format.
In this game the starting fen was `bbrnnqkr/pppppppp/8/8/8/8/PPPPPPPP/BBRNNQKR[HEhe] w ABCDEFHabcdefh - 0 1`
where [HEhe] indicates the Hawks and Elephants in pockets, and ABCDEFHabcdefh represents the gating possibilities. KQkq is not there, so this is a "no castling" setup.
Paste your FEN here to let me reproduce this issue, please!

**Comment by Curious2021** [comment]
I now see what the problem is. Pychess is not recognizing FEN positions pasted from the clipboard even if the protocols are correct. After pasting the correct FEN protocol into Pychess the option “play with computer” is always grayed out. In order to get around the problem one has to MANUALLY set up the FEN sequence via the editor. And I’m referring to both s-chess and s-house. For example...


rbbnkqnr/pppppppp/8/8/8/8/PPPPPPPP/RBBNKQNR[HEhe] w ABCDEFHabcdefh - 0 1

Is not being recognized and you have to manually enter the above into the editor for the position to be correctly approved for playing against Stockfish.

**Comment by gbtami** [comment]
What "Pychess is not recognizing FEN positions pasted from the clipboard" exactly means?
If I copy your FEN `rbbnkqnr/pppppppp/8/8/8/8/PPPPPPPP/RBBNKQNR[HEhe] w ABCDEFHabcdefh - 0 1` with Ctrl+C then paste it to the FEN entry in new game dialog with Ctrl+V, it works for me without using the pychess editor menu. Am i missing something here?

**Comment by Curious2021** [comment]
Then why is it when I do the same thing it’s not getting recognized? I’m using the iPad Pro 2018 third generation. BTW, there’s another related issue here. I can’t see the editor on the iPhone. Even switching to landscape mode with my iPhone 11 Pro Max I can’t see the editor option. I have to use the iPad Pro to see the editor.

Again, when I try pasting valid FEN positions into the editor the option “Play with computer” is getting grayed out. To get around the problem I have to manually fiddle with the pre filled FEN code to enter via keyboard. BTW, you cannot use your fingers to set up the board position either because even if you do so...the editor may recognize the position as valid...but won’t show the elephant or hawk options in the reserve when you play against the computer. To get around this problem I have to manually drop a bishop and knight and replace them with the elephant and the hawk for Pychess to see them when I try playing a game.

**Comment by gbtami** [comment]
Mobile device support is partly implemented only. It needs lots of work to be ready. See https://github.com/gbtami/pychess-variants/issues/6

" Why do I have to remember to put the [HEhe] and the gating options when all I should be able to type in the FEN position only?"
Because pychess can't guess you want to play a game with or without pieces in hand (or with gating or without gating) if you don't provide the full(!) FEN string.
