### ISSUE TITLE
feature request - change color of rook square to blue after moving from original square.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#358]
This feature request is something I asked Lichess to consider when playing chess 960. When you play various chess 960 positions, the location of the rooks can be hard to remember where they’re located so if you see a chance to castle using the new setups may cause you to “forget” where the rooks came from causing you to make an illegal castling move. This feature would allow the player who is playing chess 960 to know if the rook square turns blue...it means the rook has moved from its original square alerting you that you can’t castle.

**Comment by gbtami** [comment]
pychess uses chessgroundx (fork of lichess developed chessground js library), and this is not implemented there.
As a workaround I suggest to use move list navigation buttons. You can go to the starting position and check the rooks initial squares.
