### ISSUE TITLE
Seirawan Chess 2 - allow Elephant and Hawk to use vacated squares of the pawns as well.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#359]
I've always wondered why GM Yasser Seirawan didn't think to allow the Elephant and the Hawk to not only fill the empty back rank that's vacated by the major pieces...but also fill the spaces by the pawns. Because if this were allowed you'd have 16 squares that could be chosen to fill the space with either the Elephant or the Hawk. If Seirawan Chess 2 gets approved...you'd have the only playing site in the world that allows you to play the Elephant and Hawk pieces to the empty squares vacated by the pawns as well.

**Comment by gbtami** [comment]
Because pychess server is heavily based on Fairy-Stockfish (valid move list, FEN, SAN generation, game adjudication, etc.) we can add variants supported by Fairy-Stockfish only.
