### ISSUE TITLE
Add a thinking time clock feature.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#362]
When playing a rapid or blitz game it would help if a thinking time clock could be added. The idea behind this is to have the player know how much time they need to think over a move before making it This feature would make it possible for players to avoid time trouble.

For a game that is 3 minutes 2 seconds increment...your thinking time per move should be 8 seconds.
If the game is 5 minutes with zero increments, total thinking time per move should be 10 seconds.
If the game is 5 minutes 3 seconds, total thinking time per move should be 13 seconds.
A game that is 90 minutes and 30 seconds increment, each move thinking time should be 4 minutes.

So a game should have two clocks. One counts down the time while the other calculates the amount of time a player needs to allot to bank time more efficiently and not get into time trouble. Gbtami, don’t close this one. This is a good idea.

**Comment by gbtami** [comment]
In chess you have to manage your time. I don't like this idea, sry.
