### ISSUE TITLE
Accept FEN using "/" for pockets

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#363]
![https://i.imgur.com/2uqXxux.png](https://i.imgur.com/2uqXxux.png)
![https://i.imgur.com/lQo7YNd.png](https://i.imgur.com/lQo7YNd.png)

**Comment by Fulmene** [comment]
The editor now accepts this after #992 , but it hasn't been recognised as valid in chess.ts's validFen function yet.
