### ISSUE TITLE
Pychess does not allow point and click to set up board positions?

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#364]
Setting up the chessboard in the editor on Lichess is done by point and click. Pychess does not have this ability. You have to manually drag and drop pieces to their positions. Point and click to set up board positions needs to be implemented.

**Comment by gbtami** [comment]
Lichess has countless featured not implemented on pychess site. Believe me I know the differences :)
Don't open new issue for them one by one please!
