### ISSUE TITLE
Cannot paste FEN positions via copy and paste

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#365]
You cannot copy and paste FEN positions using the editor. You have to manually create the desired positions using the editor.

**Comment by gbtami** [comment]
Works for me. Can you provide more info please?
Variant, FEN? OS, browser?

**Comment by Curious2021** [comment]
nnrqkbbr/pppppppp/8/8/8/8/PPPPPPPP/NNRQKBBR[HEhe] w ABCDEFGHabcdefgh - 0 1

The above FEN cannot be entered via copy and paste in the S-Chess variant using the editor dialog box. But the very same FEN is accepted MANUALLY when entered by stroke by stroke via the keyboard only. And it doesn’t matter which browser you use.

**Comment by gbtami** [comment]
Works for me. Have you selected the variant before(!) pasting this FEN?
![https://i.imgur.com/VDXRWfo.png](https://i.imgur.com/VDXRWfo.png)

**Comment by Curious2021** [comment]
Yes, I have. And whenever I do this the option to play against Stockfish is greyed out. But when I edit the FEN manually it gets accepted.

**Comment by gbtami** [comment]
Can you create a screenshot after paste/Ctrv+v for me please?

**Comment by Curious2021** [comment]
![1E18B515-A8D8-43E4-B5A7-8A0D9490D094](https://user-images.githubusercontent.com/73664660/98716979-6ac11680-235a-11eb-93b8-e6f1f1f81921.png)

**Comment by gbtami** [comment]
Maybe this is a mobile browser issue. Can you reproduce this on a desktop/laptop computer also?

**Comment by Curious2021** [comment]
Correct. I just tested this on my Windows 10 laptop and was able to copy and paste the FEN successfully there.

**Comment by gbtami** [comment]
Thx. I tried it on my mobile. It worked OK in Huawei browser and in Mobile Firefox also.
Unfortunately I have no Apple device to test it more :(

**Comment by Curious2021** [comment]
Well, in that case this bug seems localized to iOS browsers. I used Safari in my test case which failed. I also tested Microsoft Edge on Windows 10 which passed. So it does look like this is a iOS issue that needs fixing. No explanation as to WHY this is happening on iOS.

**Comment by gbtami** [comment]
I can't reproduce this latter piece color issue at all. Can you file a different issue for it with a short video recording, please?

**Comment by Curious2021** [comment]
I may have figured out the problem. Apparently Pychess adds a blank space before the FEN string causing it to interpret the blank space to be a null character making it unable to accept the FEN string. To fix the problem you have to manually edit the FEN string to remove the blank space before the first character. When the blank space is removed Pychess accepts the FEN string to be valid. This needs to be fixed.

**Comment by gbtami** [comment]
What exact steps I have to do to reproduce this "Pychess adds a blank space before the FEN string"?

**Comment by Curious2021** [comment]
Simply create an FEN string as you normally do when making them. Then copy the string and “paste” it into that dialog box. Nine out of ten times...the FEN is correct but won’t be recognized because Pychess is interpreting the space between the first character and the beginning of the dialog box to be a “null” character which causes it to think it’s an invalid character and won’t accept the FEN string. I was able to see this by looking at the FEN string and noticed “a gap” beginning at the very tip of the string where there is a physical gap. Once I deleted that gap...Pychess immediately recognized the FEN string to be correct.

**Comment by gbtami** [comment]
OK, I think I understand now. The FEN you paste contains a leading space. That is definitely not valid.
The FEN input field has no A.I. and will never fix your mistakes. If you paste correct FEN (no leading space) it will be OK.
Is it possible that when you select a FEN on your device you sometimes accidentally select one more additional character at the beginning?

**Comment by Curious2021** [comment]
Yes...and this usually happens while using my iPhone. Because when I use my iPhone I use my thumb to copy over the text making up the FEN string and I may “overshoot” the text and include as you call it some “leading space”. This is apparently making using the dialog box frustrating. But I don’t have this issue when I use the iPad. I copy the text using a keyboard shortcut and this doesn’t copy any leading space.

**Comment by gbtami** [comment]
Fix deployed. Test it with selecting additional space at the beginning please!
