### ISSUE TITLE
Stockfish Fairy is not working. Can’t play any games against the engine.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#367]
Came in this morning to play some games against Stockfish Fairy. It’s not responding at all. I set up a position and it’s sitting there and the clock stays frozen no matter what. Please fix ASAP. Thanks.

**Comment by gbtami** [comment]
Reastarted the server. Use our discord to report operational issues next time, please!
https://discord.gg/aPs8RKr
