### ISSUE TITLE
King vanishes when castling in S-Chess. Bug

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#368]
Castling in S-Chess needs an overhaul or at least an option to not castle because today I witnessed an interesting bug - when Stockfish castled the King vanished but was replaced by the Chancellor or the Hawk as it’s commonly known in S-Chess. A very unique bug this one. Because I envied Stockfish’s ability to get rid of the king when it castled and replaced it with the Seirawan chess pieces instead.

I apologize that I wasn’t able to screenshot this unusual bug but I assure you this is what occurred. This is clearly a bug that needs fixing.

**Comment by Curious2021** [comment]
![8BD94175-6B5D-44C9-BFCC-66B4961FC88F](https://user-images.githubusercontent.com/73664660/98992842-a7784380-24fb-11eb-9de7-d8c99c282869.png)

**Comment by gbtami** [comment]
As I see this is the game https://www.pychess.org/3Qv8rTKV?ply=0
I think your starting FEN `bqrknnrb/pppppppp/8/8/8/8/PPPPPPPP/BQRKNNRB[HEhe] w ABCDEFGHabcdefgh - 0 1` is invalid and confuses Fairy-Stockfish. The file letter of initial king positions "Dd" can't be part of the castling/gating availability part.
