### ISSUE TITLE
Support S-chess960

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#370]

**Comment by Curious2021** [comment]
Thank you.

**Comment by gbtami** [comment]
Unfortunately I was not wise enough and hard coded some S-chess gating+castling stuff in client side code, so this needs more than one code line change .
Progress so far (gatings offered in correct positions):
![https://i.imgur.com/aLrbhms.png](https://i.imgur.com/aLrbhms.png)

**Comment by Curious2021** [comment]
Why are there two sets of Hawks and Elephants in this screenshot?

**Comment by gbtami** [comment]
Because here when you do O-O-O white King and Rook both create a vacant square ("a1" and "b1", take a look at the black pieces!) and you can choose where you want to gate.

**Comment by Curious2021** [comment]
Can you provide the FEN string where I can test this?

**Comment by gbtami** [comment]
You can't test it yet. It is not committed.

**Comment by Curious2021** [comment]
I just came back to say I couldn’t test the castling capabilities because it wouldn’t allow me to castle...yet? Any estimate when I can test it?
