### ISSUE TITLE
Mobile phone edition of Pychess will not accept FEN strings for input for playing options.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#374]
Until yesterday I was able to input FEN strings on my iPhone to play nonstandard setups in S-Chess. This morning this ability no longer works. I can only input FEN strings on the iPad. When I try pasting FEN strings on the iPhone edition of Pychess I am not allowed to play these setups. If I remove the FEN strings it allows me to play standard positions only on the iPhone. This needs a fix.

**Comment by gbtami** [comment]
There is no "phone edition" of Pychess. It is a web page (served from Heroku) you can use in browsers.

Nothing changed on pychess side. Latest deploy happened at nov.14.
![https://i.imgur.com/GRJVB2d.png](https://i.imgur.com/GRJVB2d.png)

Can you paste the FEN you was not able to play please?

**Comment by Curious2021** [comment]
The issue seems to have been resolved with one caveat - pasting nonsymmetrical FEN strings will not be accepted via iPhone. These nonsymmetrical FEN strings will only be accepted via iPad. Symmetrical nonstandard FEN strings are now working via iPhone.

**Comment by gbtami** [comment]
Can you paste the FEN you was not able to play please?

**Comment by Curious2021** [comment]
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/NRBBKQRN[HEhe] w ABCDFGHabcdfgh 0 1

**Comment by Curious2021** [comment]
You apparently fixed this issue as well since I just re-entered this very FSN string and it's now working. But before it wasn't being accepted on my iPhone.

**Comment by gbtami** [comment]
As I mentioned nothing changed since nov.14. on pychess.org
