### ISSUE TITLE
Serious playing blindness discovered. 

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#377]
![63001DA6-B746-4E48-945C-B65815C5E897](https://user-images.githubusercontent.com/73664660/99809947-08fa6c80-2b11-11eb-99d0-6b9271271b86.png)

I've played this exact same sequence several times in a row and Stockfish still didn't see the threat my moves posed and got checkmated everytime. Why couldn't Stockfish counter my mating threat? And this is level 6.

**Comment by gbtami** [comment]
Fairy-Stockfish BOT on pychess.org is rather handicapped. According to https://github.com/gbtami/fairyfishnet/blob/master/fairyfishnet.py#L136 level 6 send UCI options skill level 16, move time 0.4s max, depth 8 max. This means Fairy plays weak moves sometimes. But I can agree that this "blindness" seems too much. If this is not a one case affair I suggest you to report it on https://github.com/ianfab/Fairy-Stockfish/issues 
Don't forget to provide a game link.
