### ISSUE TITLE
Engine suggested drop move rendering doesn't use variant pieces in Shogi and Sittuyin

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#38]
See:
```
            drawable: {
                autoShapes: shapes0,
                pieces: {
                    // drop pieces have to be in one path (wg.svg for white gold)
                    // TODO: Shogi and Sittuyin pieces are missing !
                    baseUrl: this.model["home"] + '/static/images/pieces/merida/' 
                    }
            },
```

![shogi](https://user-images.githubusercontent.com/479964/66316135-62a4d500-e917-11e9-9866-0b7dbe44d6db.png)

**Comment by CouchTomato87** [comment]
Is this something I can help on? And would the drop piece suggestion be able to match what piece set you have chosen?

**Comment by gbtami** [comment]
No and yes :)

Things to do.
- [ ] Create [symlinks](https://en.wikipedia.org/wiki/Symbolic_link) with file names expected by chessground in all variant piece set.

- [ ] Use piece set URL of user preference in above line.
