### ISSUE TITLE
Increasing the number of gated pieces by control clicking causes Pychess to stop playing S-Chess.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#386]
Increasing the number of possible gated pieces in S-Chess causes Pychess to stop playing the S-Chess variant. If you click on the Elephant and Hawk to increase their number from 1 to 2 for instance, Pychess stops responding after 4 or 5 moves and this is after it gates one of the pieces in the pockets. But when you leave the gated pieces at one a piece, Pychess plays normally.

**Comment by gbtami** [comment]
Reproduced in https://www.pychess.org/ZdwK5WDH?ply=31

**Comment by gbtami** [comment]
I think this was an issue with our fishnet workers. Should be OK now.

**Comment by Curious2021** [comment]
I need to further mention this happens on level 8. When I play using level 6 it seems to be working.  But it reappears after I set it to level 3. So it's not isolated to one level. But since it seems to work on level 6 suggests this could be a depth level issue in the analysis tool causing iitto freeze.

**Comment by gbtami** [comment]
If you notice this again feel free to reopen (with a game link).
