### ISSUE TITLE
Pychess doesn't accept custom setups using editor in S-Chess

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#388]
I tried creating a nonstandard setup using the editor for S-Chess and even though the FEN was syntaxically correct It would not allow the nonstandard setup which would be considered normal using 960 configuration rules. Even though castling is disabled it still wouldn’t allow this setup configuration. Now prior to today it was possible to generate these positions and Pychess would allow play. Now this is not possible and the only configuration it allows is the standard one. I checked to make sure there were no leading spaces and still it wouldn’t allow the setups to be used. Even though these were allowed previously.

**Comment by gbtami** [comment]
Thx for reporting this. I applied ffish.js FEN validation in some of the latest commits to prevent crashing the fishnet workers. Unfortunately it has this side effect. Will fix it ASAP.
