### ISSUE TITLE
auto scroll in chat

### ISSUE THREAD

**Issue by matuser2** [gbtami/pychess-variants#389]
Enhancemnet request for the chat interface during a game:

When reaching the end of the chat box, the additional lines appear out of sight, and the player need to scroll down manually.
It would be nice to have an auto-scroll so that the new lines will always appear at the bottom of the chat.

**Comment by gbtami** [comment]
This was reported in https://github.com/gbtami/pychess-variants/issues/175 also.
If you can provide additional info, post it there please. Thx!
