### ISSUE TITLE
The mate in one issue still hasn’t been fixed in S-Chess variant.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#390]
https://www.pychess.org/gaTWkeXn

Was in level 8...the highest that Pychess offers and I still mated it in one move. Where’s the fix for this?

**Comment by gbtami** [comment]
The bug was fixed in Fairy-Stockfish git but fairyfishnet workers got no updated binaries in https://github.com/gbtami/Fairy-Stockfish/releases to date.
Thx for the notice!

**Comment by gbtami** [comment]
New release created. Should be OK after all workers update itself.
You can follow them here https://www.pychess.org/fishnet/monitor
