### ISSUE TITLE
Pychess invalidates game because a move was considered illegal.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#391]
https://www.pychess.org/3zLJRgT2

I was losing anyway but still...Pychess makes a move that immediately invalidated the game. I have no idea why this happened.

**Comment by gbtami** [comment]
What was your latest (invalid) move?

**Comment by Curious2021** [comment]
The last move by Pychess was considered invalid. It stopped the game after making its own move!

**Comment by gbtami** [comment]
Unfortunately it is not reproducible now. I can imagine that our latest fixes affected this also.
I close this now, but feel free to reopen if it occurs again.
