### ISSUE TITLE
Invalid move in S-chess game

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#393]
https://www.pychess.org/6oUY0jIp?ply=9

**Comment by abunickabhi** [comment]
This invalid move has happened in S-House to me like 10 times, both from White and Black sides, mostly during castling+gating.

(https://www.pychess.org/JZ8pfnn2 , https://www.pychess.org/mvjP4XKY and few more games)

**Comment by gbtami** [comment]
https://www.pychess.org/18JuhxMf

**Comment by abunickabhi** [comment]
Is this the traceback generated when the error was tried to be reproduced?

**Comment by gbtami** [comment]
yes
