### ISSUE TITLE
Bump time limit to 90 minutes for games on Pychess.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#400]
Currently Pychess only allows time limits of 60 minutes per game. This appears to be an arbitrary time limit. Lichess allows up to 90 minutes per game. Request the game limit on Pychess be increased to 90 minutes. This would make it possible to allow milliseconds to work properly since in this case the milliseconds wouldn’t show up until clock reaches down to 60 minutes.

**Comment by gbtami** [comment]
Yep, we should borrow slider times/increment from https://github.com/ornicar/lila/blob/master/ui/lobby/src/setup.ts
