### ISSUE TITLE
Invalid move occuring in Shogun games too

### ISSUE THREAD

**Issue by abunickabhi** [gbtami/pychess-variants#401]
In the game, https://www.pychess.org/T8J1AqTK

Invalid move occurred in the last black move, I was premoving a knight promotion and the game abruptly stopped.

This is the first time it has happened in Shogun variant, (other than S-House).

**Comment by gbtami** [comment]
Can you remember what was that last black move?

**Comment by gbtami** [comment]
I still can't reproduce this.

**Comment by abunickabhi** [comment]
It was a rook drop move, I am not sure on which square it was. Somehow the drop move didn't get recorded, and invalid move propped up. The game was going into a time scramble too.

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/b25ad14589bf07dff521b6ef13e9daa7984b4ca3
At least I hope.
