### ISSUE TITLE
Rematch button in S-Chess960 should offer randomized setups.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#403]
When selecting S-Chess960 after selecting the option to play a game...the rematch button allows you to replay the same position but from the opposite color. A rematch in opposite colors is fine...but replaying the same position should be disallowed. The rematch button should scramble the S-Chess960 position as well since this would offer true randomized play. Otherwise the rematch button should be renamed “rematch in opposite color”. You shouldn’t have to seek a new opponent to play a new position. You seek out a new opponent if you’re looking for a different variant to play when using the Stockfish Fairy engine.

**Comment by gbtami** [comment]
I disagree. In all 960 variants rematch button produces new positions only after pair of games played.
This is the only fair solution to compensate some inferior positions. Lichess works the same way.
