### ISSUE TITLE
Allow correspondence for games in Pychess

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#404]
Correspondence games are possible in Lichess but not Pychess. Please implement correspondence games in Pychess.

**Comment by gbtami** [comment]
OK, I'm not a big fan of online corr games myself, but maybe one will send a good PR.

**Comment by CricketForJapan** [comment]
I am keen on correspondence games as fits in well with my life, especially with the longer games, as opposed to the mini variants (really fun when you just want a quick game).  On lichess only standard correspondence games are rated, all the variants are unrated. I believe lishogi.org has quite a few correspondence games on going.

**Comment by samboy** [comment]
Correspondence chess variants are available at https://brainking.com/ http://www.gamerz.net/pbmserv/ https://mindsports.nl/index.php/players-section to name just three servers.

**Comment by CricketForJapan** [comment]
Thank you for the useful links.  I already play on brainking, but I did not know about the other two. The site pychess.org is a much more modern facility and has post game computer analysis available.  If the site would host correspondence, then this would ensure a regular flow of traffic to the site, as people need to revisit regularly. The games can be unrated as far as I am concerned, as I recognise there is more scope for cheaters on correspondence. Are you available for a game on BrainKing.com?

**Comment by samboy** [comment]
I’m tapped out on chess games right now over at https://lichess.org/@/Goldrider right now, and I do not have a BrainKing account. Maybe when I get a physical set for playing chess variants (right now, https://uscfsales.com has 10x10 and 12x12 tournament chess variant boards, as well as eight different tournament quality fairy pieces one can buy) 

This feature request would be useful (heck, it would be quite useful _for me_) and maybe an open source developer will get bored and implement it for Pychess.

**Comment by gbtami** [comment]
Implementation started in https://github.com/gbtami/pychess-variants/tree/correspondence
You can follow the progress is in https://github.com/gbtami/pychess-variants/issues/1231
