### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#41]
I went back to Jarl's original idea of an elephant. How does this look?

![ElephantFavicon16](https://user-images.githubusercontent.com/52322435/66724026-abb0c980-edee-11e9-8e13-7e5a240ffb34.png)
![ElephantFavicon64](https://user-images.githubusercontent.com/52322435/66724029-af445080-edee-11e9-80f0-1d9bc12fe78e.png)

Here is the file, and I've also included the code it came with in a text file:

[favicon.zip](https://github.com/gbtami/pychess-variants/files/3722598/favicon.zip)

**Comment by gbtami** [comment]
faviconcode.txt has references to *.png files not contained in .zip
Included favicon.ico itself not working for me at all.
HELP! :)

**Comment by CouchTomato87** [comment]
oh, for some reason "favicon.ico" is not actually favicon.ico itself, but favicon.ico.zip. You have to extract the files and commit them.

**Comment by gbtami** [comment]
Thx! It is OK now.

**Comment by gbtami** [comment]
Deployed.
