### ISSUE TITLE
Pychess lets you play new game with same color with rematch button after leaving and returning to the same window.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#411]
Playing a game with one color and then closing the window to go to another website and then returning to the same window after returning causes Pychess to allow user to play the same setup using the same color. For example, if you play a game in one color and leave the window and return to the same window after returning...hitting the rematch button is supposed to allow you playing S-Chess960 with a different color. But in this case after returning to the window Pychess doesn’t recognize you played with the setup with the one color you already played with and resets the game using the same color you had previously.

**Comment by gbtami** [comment]
This is because if you leave the site and come back again that counts as different/new session. New life :)
