### ISSUE TITLE
S-Chess960 fails to recognize gated pieces are valid when making moves.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#412]
https://www.pychess.org/mXZ6GPmQ

Making a move causes Pychess to fail to recognize making a move should allow gated pieces to be placed on the board.

**Comment by gbtami** [comment]
What move exactly?

**Comment by Curious2021** [comment]
The first knight move that I played.

**Comment by gbtami** [comment]
Seems there is no "a" in nbrknqbr/pppppppp/8/8/8/8/PPPPPPPP/NQBRKBRN[HEhe] w KQBCDFGkqbcdfg - 0 1
