### ISSUE TITLE
Pychess has suddenly reverted to Random Bot 

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#414]
I was setting up a game and immediately noticed I wasn't playing against Stockfish but Random Bot. I specifically requested to play Stockfish Fairy but was paired with Random Bot. I had played Stockfish Fairy and was satisfied with its play. Why the sudden disappearance of Stockfish Fairy?

**Comment by gbtami** [comment]
This is server operational issue. Github issue tracker is for development only.
Use our Discord for this, please!
