### ISSUE TITLE
Game did not continue

### ISSUE THREAD

**Issue by MeisterPatzer** [gbtami/pychess-variants#417]
With 11 seconds left on the clock I made my move (Qg5 check) in a game of S-Chess on Pychess. But the game did not continue. The clock of my opponent did not start and my time was blinking. Later I found out that I lost the game due to time out. This bug occured multiple times in the past (last years) but not this year as far as I remember.

MeisterPatzer

[pychess-variants_6YYf7zJq.txt](https://github.com/gbtami/pychess-variants/files/5697465/pychess-variants_6YYf7zJq.txt)

**Comment by gbtami** [comment]
The blinking clock indicates that you lost the connection to the server. You can try to refresh your game tab if this happens again.
Unfortunately temporary loss of connection can happen to anyone. I lost several games on lichess.org exactly the same way myself in the past. There is nothing we can do with this.

**Comment by MeisterPatzer** [comment]
Thanks for your response,
but I can´t believe this. On lichess this never happened to me although I played there more then 10.000 games there. On pychess this happened at least 4 times to me although I only played a few hundred games there.

Frank Götze13086 Berlin
 

    Am Dienstag, 15. Dezember 2020, 18:42:30 MEZ hat Bajusz Tamás <notifications@github.com> Folgendes geschrieben:  
 
 


The blinking clock indicates that you lost the connection to the server. You can try to refresh your game tab if this happens again.
Unfortunately temporary loss of connection can happen to anyone. I lost several games on lichess.org exactly the same way myself in the past. There is nothing we can do with this.
