### ISSUE TITLE
Click destination square to move piece

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#420]
Click a destination square to make a piece move to that square is implemented in Chessbase but not Lichess. The benefit here is the piece moves to the square you choose automatically if it's able to reach that square. If there are more than one piece that can reach the same destination square then you have to select the piece to move to that square.  Currently you have to manually select each piece you want to move to the destination square in Pychess.

**Comment by gbtami** [comment]
On client side pychess use [chessgroundx](https://github.com/gbtami/chessgroundx) fork of [chessground](https://github.com/ornicar/chessground) developed by lichess, so this can happen if they implement it. I see very little chance for that.
