### ISSUE TITLE
Manually constructed S-Chess960 setups do not recognize gated pieces

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#426]
Using the editor to manually construct S-Chess positions causes Pychess to fail to recognize gated pieces during games played. But when letting Pychess generate S-Chess positions using the 960 checkmark in the dialog box the games recognize gated pieces.

**Comment by gbtami** [comment]
Can you give concrete FEN you constructed in Editor causing this issue please?

**Comment by Curious2021** [comment]
When I manually enter this position...

rbqkrnbn/pppppppp/8/8/8/8/PPPPPPPP/QNNRBBKR[HEhe] w KQkq - 0 1 It fails to recognize it’s a valid S-Chess position because it doesn’t add the appropriate gated position locations when manually inputting the board setup. You have to manually input the ABCDFGHabcdfgh part separately. But that’s not what the instructions mention when setting up the board. How are players supposed to know that when they generate their own board setups using the editor? It’s only via trial and error did I see I have to add the gated position code separately in order for it to be recognized as a valid S-Chess setup. The FEN string is what I got when I entered the pieces but NOT the gated piece valid locations. That I was forced to type in AFTER setting up the board. Otherwise you have to mention setting up a S-Chess position using the board editor is s two step process. First, enter the board position using the editor screen. But the SECOND part requires you to manually type in the gated position code for Pychess to recognize it’s a S-Chess position. Otherwise if you don’t enter the second step Pychess will ignore the gated positions for the setup.

**Comment by gbtami** [comment]
When you choose S-chess variant in Editor FEN is `rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR[HEhe] w KQBCDFGkqbcdfg - 0 1`
You can get this any time if you push the STARTING POSITION button. If you push CLEAR BOARD you have to add gaing possibilities by hand. I don't see any problem here.
Adding something similar like castling right check boxes on the right side seems non trivial and also clutters the interface IMO.
