### ISSUE TITLE
KYOTOSHOGI - Drops during Computer Analysis

### ISSUE THREAD

**Issue by CricketForJapan** [gbtami/pychess-variants#431]
In computer analysis mode the  piece to drop is not appearing.  

Is this difficult to implement as pieces has 2 possible sides when dropping?
[https://www.pychess.org/WesrTfCC?ply=18](url)

![image](https://user-images.githubusercontent.com/71611771/103856511-ac491600-50ac-11eb-88c0-aad02ca3ebee.png)

**Comment by gbtami** [comment]
Thx for reporting this! Seems other piece sets (2/3) are OK, only the default one produces this bug. Will fix it ASAP.
