### ISSUE TITLE
Bug in a makpong game

### ISSUE THREAD

**Issue by MistakeCorrect** [gbtami/pychess-variants#433]
Hi gbtami, i played a Pychess Makpong game with RandomMoverBot and in the move 21.Ne3# Not is checkmate , i can move Kd2 or Ke2 , and in other games all good but, this is a bug because a Knight cannot checkmate its own.
You can see the game [here](https://www.pychess.org/9dYhbgKL)

**Comment by gbtami** [comment]
This is Makpong not Makruk!
See the rules on https://www.pychess.org/variant/makpong

**Comment by MistakeCorrect** [comment]
Aaaa thanks gbtami!
