### ISSUE TITLE
Add Atomic960

### ISSUE THREAD

**Issue by Iubar2** [gbtami/pychess-variants#436]
Hey,
Atomic960 is a variant which alot of Atomic players are interested in. For the third Atomic960-Tournament more than 50 players regsitered (https://lichess.org/forum/team-atomic960-tournament/atomic960-tournament-third-edition-rules?page=1). The problem is that there are very few sites to play on. Since most Atomic players are used to the lichess interface, pychess would be the ideal site for this variant. I know it was suggested before, but since i found no issue i wanted to open one. Maybe some day it will be added :) If there are any questions feel free to ask me on lichess (Iubar) or the pychessdiscord

**Comment by gbtami** [comment]
Because pychess server is heavily based on Fairy-Stockfish (valid move list, FEN, SAN generation, game adjudication, etc.) we can add variants supported by Fairy-Stockfish only.
See https://github.com/ianfab/Fairy-Stockfish/issues/81
If that happens feel free to reopen this issue.

**Comment by gbtami** [comment]
Hah, progress in Fairy today https://github.com/ianfab/Fairy-Stockfish/tree/atomic_no_check

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/5b3876b0976ae6af2f49e450cbd2ad290494043b
