### ISSUE TITLE
The game freezes when you cancel promotion

### ISSUE THREAD

**Issue by ivvlspirit** [gbtami/pychess-variants#439]
In Shogun, and Shogi variants, when you move to rank 6 and are offered a promotion, if you click anywhere else on the board, your piece moves back to where it came from and you can't perform any other move besides taking pieces from the pocket. I tried recreating the problem on multiple different variants and it all produces the same result.

Unfortunately, I couldn't manage to start the program because uvloop is not supported on Windows, so I couldn't test for possible solutions.

**Comment by gbtami** [comment]
Seems it is the same in standard chess as well.
