### ISSUE TITLE
When selecting piece sets, the games with more options get cut off

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#441]
![https://media.discordapp.net/attachments/634298688663191584/805410763853922345/Screenshot_20210131-071443_Chrome.jpg?width=244&height=515](https://media.discordapp.net/attachments/634298688663191584/805410763853922345/Screenshot_20210131-071443_Chrome.jpg?width=244&height=515)

**Comment by gbtami** [comment]
Maybe we should split off boards and pieces from other settings and create their own sub menu, similar to lichess/lishogi.
Then we can change the preview images layout from horizontal to vertical.
@Fulmene what do you think?

**Comment by Fulmene** [comment]
The problem with moving board and piece settings to their own submenu lichess/lishogi-style is how pychess focuses on many different variants. The board, the pieces, and some of the checkboxes depend heavily on the variant. It's why I put all of them in the same place, under a single "choose variant" dropdown menu, in the first place.

I think we should discuss about the design more deeply before we decide. How exactly will the UI work, how will it look on mobile, etc. Some mockup images might also be useful to the discussion.

**Comment by gbtami** [comment]
I imagine something like this:
![https://i.imgur.com/R9RFzok.png](https://i.imgur.com/R9RFzok.png)
![https://i.imgur.com/d43H4Dl.png](https://i.imgur.com/d43H4Dl.png)
![https://i.imgur.com/pPhct3B.png](https://i.imgur.com/pPhct3B.png)

**Comment by Fulmene** [comment]
I still insist on putting them in the same place. I imagine something closer to this. What do you think?

![image](https://user-images.githubusercontent.com/13796147/109205774-a7196500-77d9-11eb-841f-e073a8fbb975.png)

**Comment by gbtami** [comment]
Yeah, this is def better layout than what we have now.
