### ISSUE TITLE
Problem in "all players" page of mobile site.

### ISSUE THREAD

**Issue by ghost** [gbtami/pychess-variants#453]
![20210216_185759](https://user-images.githubusercontent.com/79149430/108069611-91919600-7089-11eb-8ae8-b0d875ce1756.jpg)

There are some strange looking text in **all players page** ... _**https://www.pychess.org/allplayers**_
Clicking on the text leads to some _random user's profile._

**Comment by gbtami** [comment]
Works for me. Is this still reproducible for you?
Device? Browser?

**Comment by Diwaditya** [comment]
The text are still visible, the text is always next to the user **bzoto**.
My device name - Samsung Galaxy M01
