### ISSUE TITLE
Atomic Analysis board doesn't allow castling

### ISSUE THREAD

**Issue by catask** [gbtami/pychess-variants#462]
In this game, when under analysis mode, black can't castle in either direction (10...0-0-0), or if moving the queen out of the way, black still can't play 0-0.

https://www.pychess.org/AWPrtfCz

In other variants castling appears to be functioning in the analysis board.

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/3d6f4eb7cb2cfbba3f0ba44517c12bd5db13f6cb
