### ISSUE TITLE
In Dobutsu Shogi set cats are diff color than dogs in original design

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#463]
Original: ![https://commons.wikimedia.org/wiki/File:Shogi-Set-02.JPG](https://commons.wikimedia.org/wiki/File:Shogi-Set-02.JPG)
Ours: ![https://i.imgur.com/CFt7PUt.png](https://i.imgur.com/CFt7PUt.png)

**Comment by MistakeCorrect** [comment]
It's green. But i have a question . Why you add to all issues maked by you the Good first issue label?

**Comment by gbtami** [comment]
Because it is a "good first issue" to work on for someone who never coded anything in pychess before.
Btw. Tasshaq already fixed this :)
