### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Daslov** [gbtami/pychess-variants#467]
Hi! I would like to give one friendly suggestion. I sometimes create several games at Pychess site and because there are few people around playing those games against real opponents, and in the meantime, I do other things, read articles and so on, and don't receive any notices about someone accepting some of my games so I miss these chances regularly. I think we should receive a note that an opponent joined the game just like on Lichess. I apologize in advance if I missed something.

**Comment by visualdenniss** [comment]
In addition to that, i would also like to suggest dynamic changes in the tab name from "YourName vs OtherName" to "Your Turn" when an opponent makes a move while on other tab in the browser

**Comment by gbtami** [comment]
Committed basic new game notification. Move notification will be added soon.
