### ISSUE TITLE
Variant Request: A shogi mode

### ISSUE THREAD

**Issue by MistakeCorrect** [gbtami/pychess-variants#469]
I do not decided the name.. but is very easily:
Shogi, standard
but without crazyhouse rules. Gorogoro, dobutsu, mini, kyoto, and standard have crazyhouse rules. Why no one without?

**Comment by MistakeCorrect** [comment]
Or we can add a 3-Check Shogi.

**Comment by gbtami** [comment]
Read "How do you choose which variants to add?" and "Can you add XXX?" on https://www.pychess.org/faq please.
I don't plan to add arbitrary variants, sry.
