### ISSUE TITLE
Screen jerk

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#48]
https://pychess-variants.herokuapp.com/KYcHvK0x

Was playing with a friend and he accidentally made a wrong move because his screen jerked while grabbing the piece (move 21). His browser was Chrome

**Comment by gbtami** [comment]
Can you elaborate it, please? What exactly happened? What is the problem? Is it reproducible? Can he provide a screenshot (maybe a short video recording)?

**Comment by CouchTomato87** [comment]
I wasn't able to reproduce it, but I suspect it has to do with resolution and possibly an older version of Chrome. When he views the settings window, the scaling bar and the board images extend beyond the container. This doesn't happen on my PC, but on my laptop (Macbook) it does.

**Comment by gbtami** [comment]
OK, I still don't know from "screen jerked while grabbing the piece" what exactly happened :)

**Comment by CouchTomato87** [comment]
Remember how there was another issue with the screen jumping around when scrolling through the game moves? It's the same thing, except he was picking up a piece to move iit, and the screen jumped, while he was dragging the piece, causing him to place it on the wrong spot.

**Comment by gbtami** [comment]
I think I can imagine now, thx :) Unfortunately I can't reproduce this on my Ubuntu 19.04 (Firefox, Chromium). Can you ask him the browser version used, please ? Maybe that info can help.

**Comment by CouchTomato87** [comment]
He says version 77 (I have 78)
