### ISSUE TITLE
Flipping board in Goro Goro results in flipped pieces 

### ISSUE THREAD

**Issue by visualdenniss** [gbtami/pychess-variants#480]
Flipping board does not flip by adjusting the players point of view like in Dobutsu for example, but simply flips the board view as it is, so pieces closer to the viewer are simply upside down: 

https://user-images.githubusercontent.com/80699817/111634356-7be9ca80-8807-11eb-8414-5bca22647b20.MP4

**Comment by Diwaditya** [comment]
@visualdenniss Ya happy now!
