### ISSUE TITLE
Lobby page text collapse on top of each other when resized 

### ISSUE THREAD

**Issue by visualdenniss** [gbtami/pychess-variants#481]
texts etc. collapse on top of each other in different browser sizes, as well as the div of aside class="sidebar-second" does not return to normal layout sometimes after resizing it to smaller then full again: 

https://user-images.githubusercontent.com/80699817/111829764-2e03be00-88fe-11eb-9b05-059b64acfedd.mp4

**Comment by gbtami** [comment]
We should add more responsive layout I think.
I mean not just "mobile" and "desktop" but "tablet" layouts as well (similar to lichess).

**Comment by pepellou** [comment]
I noticed this while testing the site. There's a couple of resolution "jumps" that break things.

<img width="603" alt="Screen Shot 2021-07-13 at 12 22 52 PM" src="https://user-images.githubusercontent.com/519873/125497863-9bdeb5c2-a3d3-4860-8f01-342b983d5ea7.png">
<img width="835" alt="Screen Shot 2021-07-13 at 12 22 42 PM" src="https://user-images.githubusercontent.com/519873/125497898-323226dc-269e-4a33-93dd-9e20b8e8c841.png">

I could work on this later if nobody is doing it.

**Comment by gbtami** [comment]
One reason of these issues is the missing "tablet" layout support in all the responsive CSS stuff. I just wanted to make things work for mobile first, and later forgot to support the "middle sized" devices.

**Comment by pepellou** [comment]
Ok. Sorry if I'm lacking some context as I just got here recently. Are all those "things" working for mobile already or would this issue blocked until that happens?

**Comment by pepellou** [comment]
Oh wait, I think I didn't read the `"forgot"` so I assume this is ready to be done.

I'll add support for tablets and middle sized devices 👍

**Comment by gbtami** [comment]
I think the users profile page is not responsive still, everything else should be OK on mobile (minus the bugs filed already in other issues like https://github.com/gbtami/pychess-variants/issues/440).

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/48d119323475294a16ddad6c9bb60d1bb41708cb
