### ISSUE TITLE
yarn gulp prod issue: Can't walk dependency graph: Cannot find module '../static/ffish.js' 

### ISSUE THREAD

**Issue by makcyd** [gbtami/pychess-variants#485]
**Steps to reproduce**
1. Clone the repo
2. perform installation instructions as per README.md
3. Get to step `yarn gulp prod`

**Result**
Error:
```
[14:35:05] Can't walk dependency graph: Cannot find module '../static/ffish.js' from '/pychess-variants/client/editor.ts'
    required by /pychess-variants/client/editor.ts
[14:35:05] Can't walk dependency graph: Cannot find module '../static/ffish.js' from '/pychess-variants/client/paste.ts'
    required by /pychess-variants/client/paste.ts
[14:35:05] Can't walk dependency graph: Cannot find module '../static/ffish.js' from '/pychess-variants/client/analysisCtrl.ts'
    required by /pychess-variants/client/analysisCtrl.ts
```

**Expected result**

No error

**Workaround**

Edit files `client/editor.ts`, `client/paste.ts`, `client/analysisCtrl.ts` and change the line
  ```
  import Module from '../static/ffishjs';
  ```
  
  to
  ```
  import Module from 'ffish';
  ```

**Additional info**

I've tried to switch to `import Module from 'ffish-es6'` as it is listed in TODO, but it lead me to another error:
```
 'import' and 'export' may appear only with 'sourceType: module' (16:0) while parsing /pychess-variants/node_modules/ffish-es6/ffish.js while parsing file: /pychess-variants/node_modules/ffish-es6/ffish.js
```

I've tried to apply a solution described in [tsify issue#86](https://github.com/TypeStrong/tsify/issues/86#issuecomment-146656950) to no avail, so switched to 'ffish' that seemed to work.

**Comment by gbtami** [comment]
While your workaround enables `gulp prod` to run without error, the resulting code will not work (see browser console error messages).
My workaround is to run `heroku-postbuild` script from https://github.com/gbtami/pychess-variants/blob/master/package.json#L43
