### ISSUE TITLE
Embassy Chess - Brain King Castling

### ISSUE THREAD

**Issue by CricketForJapan** [gbtami/pychess-variants#487]
I am keen on importing Embassy games from Brain King.  This is only a request, I fully understand if it is not implemented.

Embassy Chess shorts castles on the left. Capablanca short castles on the right. The fairy-stockfish code has to have a special “Have Embassy Chess castle differently” bit of code in its source.
The reason for this is because there were some issues with a person who was heavily promoting his Capablanca Chess setup at the time. He had a patent on his setup, so when Brain King moved away from that setup, they needed a setup which predated his “invention”, hence using the 1984 Grand Chess setup on a Capablanca Chess board.

The piece letters of archbishops uses an m and M instead of the FEN convention. So m and M to a and A in FEN tag instead.

**Comment by gbtami** [comment]
Example game:  https://brainking.com/en/ArchivedGame?g=8620856&i=1
```
[Event "Casual Game"]
[Site "BrainKing.com (Prague, Czech Republic)"]
[Date "2021.02.03"]
[Round "?"]
[White "CricketForJapan"]
[Black "Walter Montego"]
[Result "0-1"]
[SetUp "1"]
[FEN "rnbqkmcbnr/pppppppppp/10/10/10/10/PPPPPPPPPP/RNBQKMCBNR w KQkq - 0 1"]

1. d4 d5 2. Nc3 Nh6 3. Bf4 Bf5 4. g4 Bxg4 5. Bxd5 c6 6. Bb3 Na6 7. Qd2 g6
8. e3 Qa5 9. f3 Be6 10. Bxe6 Cxe6 11. O-O g5 12. Bg3 Rd8 13. Ah3 Cg6 14. Ng2 f5
15. Rg1 c5 16. Bf2 b5 17. b3 cxd4 18. exd4 Cc6 19. Axg5 Cxc3+ 20. Qxc3 Qxc3
21. Ce3 Bxd4 22. Cxc3 Bxc3 23. Nf4 Rd6 24. Ai3 Af7 25. Bh4 Ng8 26. Nh5 Ri6
27. Rg7 Ad6 28. Rxe7+ Nxe7 29. Ng7+ Bxg7 30. Ah5+ Rg6 31. Bxe7 Kxe7
32. Re1+ Kf7 33. a3 Axa3+ 34. Ka2 Ab4+ 35. Kb1 Ad2+ 36. Ka2 Nb4+ 37. Ka3 Nxc2+
38. Ka2 Ac3# 0-1
```

**Comment by gbtami** [comment]
The thing is what we offer under Capablaca now as custom start position is Embassy start FEN but as you already noticed this is NOT exactly the same as Embassy chess, because of different castling rules. Fortunately Fairy supports Embassy variant natively, so we can add it to pychess import with very little effort. We just have to replace the letters in move text.
