### ISSUE TITLE
White can't castle in Placement game

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#489]
https://www.pychess.org/Px8YQHbr?ply=24
![https://i.imgur.com/WegCN9w.png](https://i.imgur.com/WegCN9w.png)

**Comment by ianfab** [comment]
https://www.pychess.org/Px8YQHbr?ply=15 FEN looks weird, it should have added kingside, not queenside castling.

**Comment by gbtami** [comment]
Yeah, as I see it was already fixed in Fairy. Seems only a new pyffish release needed.
