### ISSUE TITLE
Games page doesn't use settings for the pieces and boards

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#49]
The games page doesn't use your settings for the pieces and boards.

Also, request to have (at least) the last four games played on there :)

**Comment by gbtami** [comment]
I think the current games page should show only ongoing games.
On the other hand TV should show some of the previous games in mini boards (per variant).
See https://lichess.org/tv/crazyhouse

**Comment by CouchTomato87** [comment]
Separate but related, the shogi pieces don't transfer over to the miniboards when looking at a player history. The board still works, and all other games still work.

**Comment by gbtami** [comment]
I don't understand. Can you attach a screenshot, please?

**Comment by CouchTomato87** [comment]
![GameList](https://user-images.githubusercontent.com/52322435/71666458-e4e24100-2d2e-11ea-80c3-e099011feef3.png)

Even Kyoto Shogi's pieces and board are reflected my settings... Just not the shogi pieces

**Comment by gbtami** [comment]
Thx!
