### ISSUE TITLE
Piece drops cannot be clicked

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#5]
I brought this up earlier, but I think it's still an open issue. Basically, for any game using drops (i.e. shogi, crazyhouse, etc.), you can't drop a piece by clicking it and then clicking the destination. You can only drop by dragging, which can be an issue when timers are involved.

Out of curiosity, what does the code look like that allows you to normally move with two clicks? (I'm not very good at coding but I can try to help by comparing at least haha)

**Comment by gbtami** [comment]
Chessground API provides several event handler hooks, all documented here https://github.com/ornicar/chessground/blob/master/src/config.ts
You can see my event handlers starting at  https://github.com/gbtami/pychess-variants/blob/master/src/ctrl.ts#L702
I already started to work on this, just have to test it a little before commit.

**Comment by gbtami** [comment]
It's implemented in commit https://github.com/gbtami/pychess-variants/commit/ad6172923aeb2bb55d407f5a35422dbcd33ed8d3 
Can you test it, please?

**Comment by CouchTomato87** [comment]
Just checked with all applicable variants and it works! The only thing that is still missing is that clicking the same piece again does not deselect like it does on the main board, haha.

Also on a side note, while playing through S-chess, I noted that my elephant and hawk are pure black, while the other pieces are a very dark gray. Here are the replacements. Hopefully this is the last time for real!
[ElephantHawk4.zip](https://github.com/gbtami/pychess-variants/files/3427261/ElephantHawk4.zip)

**Comment by gbtami** [comment]
Will try to fix the remaining deselecting issue.
Updated S-chess pieces committed. Thx again!

**Comment by gbtami** [comment]
I hope https://github.com/gbtami/pychess-variants/commit/269d5944210b1c5983278414dbfbd4dcc8124424 fixed it. Can you test it again, please?

**Comment by CouchTomato87** [comment]
Works great!

**Comment by gbtami** [comment]
Thx a lot.

**Comment by gbtami** [comment]
Commented out this feature in favor of fixing issue #549
We should borrow more correct implementation from lishogi. See in
https://github.com/WandererXII/lishogi/blob/master/ui/round/src/crazy/crazyView.ts
https://github.com/WandererXII/lishogi/blob/master/ui/round/src/crazy/crazyCtrl.ts
https://github.com/WandererXII/lishogi/blob/master/ui/round/src/ctrl.ts
and https://github.com/WandererXII/lishogi/blob/master/ui/chess/css/_zh-pocket.scss#L56
