### ISSUE TITLE
Invisible black captain in shinobi

### ISSUE THREAD

**Issue by kezsulap** [gbtami/pychess-variants#504]
https://www.pychess.org/0faoHaH0
On move 5 i promoted a pawn to captain. The piece can move and source of the page says it's there
&lt;piece class="black promoted pp-piece" style="transform: translate(381.553px, 76.3105px);"&gt;&lt;/piece&gt;
but the board shows an empty square. Same thing happens for captains promoted later throughout the game.

**Comment by gbtami** [comment]
Already fixed by https://github.com/gbtami/pychess-variants/commit/68f1f2c7c16030ab291f457c1ac1ae018b50dd83
Thx!
