### ISSUE TITLE
Game deleted midway

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#51]
https://pychess-variants.herokuapp.com/dvGImgyF

It was not this game, but one before with the same player.

It was a game that I was in the middle of playing... Five moves were played (or 2 full moves and a half by chess standard). Then I made my move, and a few seconds later, the game said "READY!" It was back to my opponent's turn, even though the board showed that it was their move last. The game was stuck, and it looks like it was removed from the game record as well...

I wonder if the issue is related to us both taking a while to make our first moves? And maybe the "game abortion" was a delayed reaction to that?

**Comment by gbtami** [comment]
I think your guess is correct.

**Comment by CouchTomato87** [comment]
Can we extend the amount of time before games time out? Especially with players new to the site, they often spend up to a minute just figuring out what to do, getting their settings changed, or talking.

**Comment by gbtami** [comment]
Sure! I have to fix this anyhow.

**Comment by gbtami** [comment]
Btw I raised the starting limit to 5 min.
