### ISSUE TITLE
Chess pawn as drop piece suggestion in Kyoto game

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#510]
https://www.pychess.org/vYdAQRKp?ply=18
![https://i.imgur.com/WM3ZIGH.png](https://i.imgur.com/WM3ZIGH.png)

**Comment by Diwaditya** [comment]
Also, note this problem of **upside-down** **piece** as suggestion. (As I know in **shogi,** our opponent's pieces are **upside-down** but in _analysis_ it shows as the _example_ given below: 
- https://www.pychess.org/qbxYGmzG?ply=57

Also, our opponent's pieces (drop suggestion) should be **upside-down** is shown as up-right: https://www.pychess.org/qbxYGmzG?ply=74

_I hope you understand, what I'm saying._

**Comment by gbtami** [comment]
The root of the problem is here https://github.com/gbtami/pychess-variants/blob/master/client/document.ts#L12

Kyoto is the only variant where not all possible drop piece roles are there in the pockets.
The pawn from the pocket can be dropped as pawn or promoted pawn(!) as well. But the latter has no DOM element in the pocket (and also not on the board in this position), so if `role` is `pp-piece` `const el = document.querySelector(`piece.${role}.${color}`) as HTMLElement;` fails here.

**Comment by Diwaditya** [comment]
So, how do you fix it?
