### ISSUE TITLE
In shogi drop suggestion, the pieces are upside-down

### ISSUE THREAD

**Issue by ghost** [gbtami/pychess-variants#511]
_Is it correct? Our pieces should be **up-right** and our opponent's one should be **upside-down** but the **opposite** happens in **“Drop** **piece** **suggestion”** of **Fairy-Stockfish** **analysis.**_
Example-

-  _**https://www.pychess.org/qbxYGmzG?ply=57**_

- _**https://www.pychess.org/qbxYGmzG?ply=74**_

_**I hope you understand, what I'm saying.**_

**Comment by gbtami** [comment]
Looks OK for me.
![https://i.imgur.com/vDHNynA.png](https://i.imgur.com/vDHNynA.png)
![https://i.imgur.com/bXu6Fyy.png](https://i.imgur.com/bXu6Fyy.png)

**Comment by Diwaditya** [comment]
_But not for me:_

https://user-images.githubusercontent.com/79149430/116182031-3e972780-a739-11eb-9604-f73a8e442fa6.mp4

![Screenshot_20210427-092042_Samsung Internet](https://user-images.githubusercontent.com/79149430/116182421-e3b20000-a739-11eb-9929-7f0b1fd83f99.jpg)

_I don't know, maybe problem with the mobile site or my  browser or piece set or something else._

**Comment by Diwaditya** [comment]
@gbtami 
It looks OK from black's side (_black, the one who makes the first move in shogi._) but when you **_flip_** the board to my side _(white)_ then the **"Drop** **suggestions"** doesn't flip. Therefore, it results in upside-down piece to _white_. Or idk...
