### ISSUE TITLE
Additional pre-game time for setup in Placement in bullet

### ISSUE THREAD

**Issue by visualdenniss** [gbtami/pychess-variants#514]
It would be very practical to have an additional pre-game time for players to place their pieces like 30 seconds, especially in faster time controls such as 1 min bullet etc. Players should place their pieces in that 30 seconds and after that the game starts. 

However, i'd suggest this **_as a feature only for bullet games_** or very fast time controls but not so much for blitz or rapid games, as people might want to take more time than 30 seconds to consider carefully how they want to place the pieces etc. If someone wants to play a 10 min rapid, take his/her time to think and chill, it would probably not be a good idea to force them drop 8 pieces in 30 seconds in panic.

**Comment by gbtami** [comment]
Placement phase and game play phase are not differentiated in Placement/Sittuyin. You can always create 1.5+0 or 2+0 games if you feel 1+0 is not enough.
