### ISSUE TITLE
Hyperlink in chat

### ISSUE THREAD

**Issue by Fulmene** [gbtami/pychess-variants#516]
Implement clickable hyperlink in the chat box.

**Comment by Diwaditya** [comment]
This issue has been already filed #394 

Also, if the hyperlinks of **other** **sites** are **clickable,** the chat will be prone to **advertisements.** 
For example, lichess team leaders will advertise their teams.

**Comment by gbtami** [comment]
Agreed with Diwaditya. We have to carefully select what domains we make linakable.
