### ISSUE TITLE
Knights are missing in the piece pocket in Editor/Crazyhouse 

### ISSUE THREAD

**Issue by visualdenniss** [gbtami/pychess-variants#517]
<img width="861" alt="Screenshot 2021-05-09 at 23 30 34" src="https://user-images.githubusercontent.com/80699817/117586410-a9c10080-b120-11eb-908b-0a317b4d70c8.png">

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/e962d9d9641f73c398414ea877a46dddb7ac2509
