### ISSUE TITLE
Challenges created from "Play with a friend" automatically turn casual

### ISSUE THREAD

**Issue by mgruber161** [gbtami/pychess-variants#520]
When a logged in user creates a challenge with the "Play with a Friend"-button it always turns into a casual game. Even before it is accepted.
<img width="364" alt="Bildschirmfoto_2021-05-15_um_20 25 10" src="https://user-images.githubusercontent.com/74315620/118374479-8e407480-b5bc-11eb-9ac3-7f54e8a3f10a.png">
<img width="810" alt="Bildschirmfoto_2021-05-15_um_20 25 23" src="https://user-images.githubusercontent.com/74315620/118374482-93052880-b5bc-11eb-92cb-3f4f85592b29.png">
A challenge from a logged in user should only turn casual if it is accepted by an anon player. 
Another solution would be to make "Play with a friend" games always casual. In that case the choice of rated/casual should be removed from the challenge creation dialog.

**Comment by Diwaditya** [comment]
Everyone uses dark theme :O
