### ISSUE TITLE
goro goro  - immediate checkmate (uchifuzume)

### ISSUE THREAD

**Issue by CricketForJapan** [gbtami/pychess-variants#521]
Thanks for  goro goro dōbutsu shōgi. That is great!  According to https://en.wikipedia.org/wiki/D%C5%8Dbutsu_sh%C5%8Dgi  It has the same restrictions on dropped pieces in shogi including two pawns (nifu) and pawn drop with immediate checkmate (uchifuzume).   Is this correct on wiki?   If yes, then pychess code permits check mates with the pawns at the moment.  Please can you review. Here is an example: https://www.pychess.org/Yx1fot3y

The nifu rule is already the same as wiki.

**Comment by ianfab** [comment]
As can be seen in your example, the move is allowed, but then treated as losing/invalid. The reason for this workaround is the limitation https://github.com/ianfab/Fairy-Stockfish/issues/48.

**Comment by CricketForJapan** [comment]
I have just reviewed and shogi also permits uchifuzume  see game here:  https://www.pychess.org/YsFi7ar0
Yes, I see it states "invalid move", so players should avoid that move.

**Comment by CricketForJapan** [comment]
I see lishogi.org is the similar.  A pop up appears and states "Checkmating with a pawn drop is an illegal move", but the move is allowed.
