### ISSUE TITLE
Implement lichess shortcut keys

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#523]
Use left/right arrow keys to navigate in move list forward/backward

**Comment by Nordlandia** [comment]
* The up and down arrow keys can be used to go back and forth 10 moves

**Comment by gbtami** [comment]
Untitled_Entity: "some more useful shortcut keys on Lichess: "F" for flipping board, and "L" for toggling local analysis"

**Comment by kezsulap** [comment]
Lichess uses mousetrap library which makes the [code](https://github.com/lichess-org/lila/blob/master/ui/round/src/keyboard.ts) of shortcuts themselves very short, but requires storing minified version in repo and some trickery in [package.json](https://github.com/lichess-org/lila/blob/master/ui/site/package.json#L40) as it's not available from yarn. Do you think it's worth adding?

**Comment by gbtami** [comment]
Sure. If you can make it work, why not?
