### ISSUE TITLE
Grand chess file letters broken

### ISSUE THREAD

**Issue by IlampozhilE** [gbtami/pychess-variants#526]
Some of the file letters in grand chess appear on the wrong file. May apply to other variants too.

**Comment by gbtami** [comment]
Seems OK here. Can you provide a screenshot please?

**Comment by IlampozhilE** [comment]
![bottom right](https://user-images.githubusercontent.com/85503763/121122965-0ad31580-c840-11eb-9e9e-499625faebd4.png)

**Comment by IlampozhilE** [comment]
b,c,d,e,g,h are all kinda off center

**Comment by gbtami** [comment]
Thx a lot!
