### ISSUE TITLE
Add material value indication to Grand Chess

### ISSUE THREAD

**Issue by Tev1903** [gbtami/pychess-variants#527]
Hi all. I just wanted to leave a suggestion for those who are able/ have the time to do this. You know that indicator on Lichess that shows you or your opponent's material advantage? The one that will say, for example, +5 if you win your opponent's Rook. Well it would be very helpful if there was one for Grand Chess. The obvious reason is that, at a glance, you can see if you are down or up material. I assume most of you are chess players (better than me) who know how helpful it would be. 
One of the challenges, of course, is determining the value of the Rook/Knight compound piece and the Bishop/Knight compound piece. Smarter men than I have already done this: https://en.wikipedia.org/wiki/Empress_(chess)#Value
  https://en.wikipedia.org/wiki/Princess_(chess)#Value

According to those two articles, the Rook/Knight compound piece is worth 9 points, and the Bishop/Knight compound piece is worth 7 points. 
Now it's possible that there may be debate over those values but I think starting with those two values is better than nothing.
Anyway, thanks

.

**Comment by Diwaditya** [comment]
Actually, this is good suggestion! Maybe, this will get reopened again in the future. When we have more developers.
