### ISSUE TITLE
Show pieces captured

### ISSUE THREAD

**Issue by Tev1903** [gbtami/pychess-variants#528]
Hi again. Instead of adding material value differences for the variants, how about simply showing what pieces you captured as well as which pieces your opponent has captured. No math involved, just a little display that let's players know at a glance what they have lost and what their opponent has lost. Hope this suggestion is more reasonable to you since I think it will really enhance the playing experience and allow players to make better, quicker decisions when playing. Thanks

**Comment by gbtami** [comment]
Yes, showing material difference without diff value number seems more reasonable.

**Comment by Diwaditya** [comment]
@Tev1903 nice :D

But I am wondering, what's gonna happen with "drop variants" like crazyhouse, shogi, grand house etc.

**Comment by gbtami** [comment]
This is meaningless (not applied) in drop variants of course.

**Comment by Tev1903** [comment]
@ Diwaditya, yea as gbtami said, it's not needed in drop variants. Cuz actually, the drop variants on Pychess already have it. You can already see what has been captured for both white and black. The only difference is that you have the additional feature of putting those pieces back on the board.
 
With that said though, what I'm suggesting for non-drop variants can be more discreet than what the drop variants show. The drop variants show the captured pieces at the same size and detail as the ones still on the board since you need to be able to easily click them and put them back into play. But for non drop variants, the piece symbols can be small; just silhouettes really, like on Lichess. So the display doesn't need to take up much space on the screen.

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/f864269dbe975ea2909791a3faba53db8c8543b3
