### ISSUE TITLE
Incorrect Xiangqi game adjudication

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#53]
https://pychess-variants.herokuapp.com/jBHGPTa5

**Comment by ianfab** [comment]
@gbtami This is because of insufficient material in pyffish, right? Are variants like makruk excluded from insufficient material adjudication or why does the bug not occur for them (since in pyffish I can not find any special handling except for shogi)?

**Comment by ianfab** [comment]
I will try to consolidate the insufficient material handling if you are not already working on it.

**Comment by gbtami** [comment]
Cool, thx!
