### ISSUE TITLE
Can Play 0+0

### ISSUE THREAD

**Issue by lidevelopers** [gbtami/pychess-variants#531]
https://www.pychess.org/DNHoIVDE
![image](https://user-images.githubusercontent.com/85686806/122791077-84eeaa00-d2d6-11eb-84f1-3243dd0b8d53.png)
I can play 0+0 on pychess-variants so please fix this

**Comment by gbtami** [comment]
Provide step by step description to reproduce this, please.

**Comment by lidevelopers** [comment]
As you know using inspect element 
![image](https://user-images.githubusercontent.com/85686806/122846928-80e97900-d324-11eb-80b6-546eb08911c6.png)
just click inspect in the random color button and edit as html as enabled and its enabled and as usual click random color button to play

**Comment by lidevelopers** [comment]
please fix this or it may spam every where

**Comment by gbtami** [comment]
Fixed via 87461ec877284e080cb61df60ee74b03742ca086

**Comment by gbtami** [comment]
Thx!
