### ISSUE TITLE
Typos in Learning Guides

### ISSUE THREAD

**Issue by Tev1903** [gbtami/pychess-variants#532]
I proof read all the guides. Here's what I found...

In the Sittuyin Guide this line is written:  "When one side has only a bare king remaining, there are certain "counting rules" (see above) which come into effect..." There is nothing to "see above" as the counting rules were a part of the Makruk guide.

In Kyotoshogi Guide: "Unlike in shogi, each piece (except the King) must flip to the other side fater moving". Should say "after".

In Dobutsu Guide: "In lieu of moving a piece, you can also drop these captured back on to the board". Should say "these captured _pieces_ back on to the board.

In Xiangqi Guide: "Second is the palaces" Should say "second _are_ the palaces". 
Also "3 x 3 squares at each end of the board that _has_ diagonal lines inside". Should be "_have_" instead of "_has_".

In Capahouse 960 guide: "So for example,R@e4 means". There should be a space before the R. Same typo exists in S-Chess 960 Guide, Grandhouse Guide, Crazyhouse Guide...

In Orda Guide: "However, a very fundamental component of a majority Horde openings". Should say "a majority _of_ Horde openings".

In Synochess Guide: "If you drop them too early, you only block yoruselves in". Should be "_yourself_".

In Shinobi Guide: "is like a Knight but ocan only move". Should be "_can_". 
Also, "The Knights that start on the board can similar exert pressure". Should say, "The knights that start on the board can exert similar pressure", or, "The knights that start on the board can _similarly_ exert pressure"

**Comment by gbtami** [comment]
Thx!
@CouchTomato87 may I ask you to review this, please?

**Comment by Diwaditya** [comment]
@Tev1903 
The **Learning Guide** has been written in [markdown](https://guides.github.com/features/mastering-markdown/). So, I think you can correct these typos yourself.

https://github.com/gbtami/pychess-variants/tree/master/static/docs

**Comment by Tev1903** [comment]
> @Tev1903
> The **Learning Guide** has been written in [markdown](https://guides.github.com/features/mastering-markdown/). So, I think you can correct these typos yourself.
> 
> https://github.com/gbtami/pychess-variants/tree/master/static/docs

**Comment by Diwaditya** [comment]
Hi lol

**Comment by Tev1903** [comment]
@Diwaditya Thing is, I'm not a programmer so I have no idea what that means. I even tried to reply to you and accidentally closed the issue. So perhaps the experts should handle it lol.

**Comment by Diwaditya** [comment]
@Tev1903 
I can't find any typo in S-chess 969 guide. Did you mean S-house guide? Please clear my doubt.

**Comment by Diwaditya** [comment]
@Tev1903 
Also, please tell me what should I do with **sittuyin.md** ?

**Comment by Tev1903** [comment]
Ah, I meant the S-House guide. Where it says "So for example,R@e4".

As for Sittuyin, at the bottom of the guide, under "Tactics", It refers to the counting rules and says "see above". The problem is that the counting rules do not appear in the Sittuyin Guide. The counting rules appear in the Makruk guide. So perhaps that section in the Makruk guide should be pasted into the Sittuyin guide.

**Comment by Diwaditya** [comment]
@Tev1903 
Also, help in **Shinobi.md** would be appreciated :)

**Comment by Tev1903** [comment]
So in the Shinobi guide there are two issues. One is a typo, the other is an incorrectly structured sentence. First, the typo. Look under the wooden horse info where it says "The Wooden Horse (or Horse, for short) is like a Knight but ocan only move...". As you can see there, "ocan" should be "can".

As for the incorrectly structured sentence, in the same wooden horse info, it says "The Knights that start on the board can similar exert pressure". It should say, "The Knights that start on the board can exert similar pressure" OR "The Knights that start on the board can similarly exert pressure"

**Comment by Tev1903** [comment]
The word "exert" should come before "similar" OR the word "similar" should be changed to "similarly"

**Comment by CouchTomato87** [comment]
I can't believe I made all these typos! Thanks for looking into these. Please feel free to make changes since I'm unable to work on anything for the next couple days.

Regarding the wooden horse, thst was also a typo. It should have said "similarly."

**Comment by Diwaditya** [comment]
Should I fix 'em? :D

**Comment by Tev1903** [comment]
The man himself has spoken! Make it "similarly". Don't worry @CouchTomato87 , you were spending all your time making those awesome variants :)

**Comment by Diwaditya** [comment]
@Tev1903 
I think the writer of sittuyin guide was pointing to this as "above"
---

Additional conditions for draws: 

* The game is drawn when the player to move has no legal move and his king is not in check. The game is said to end in 'stalemate'. This immediately ends the game, provided that the move producing the stalemate position was legal.
* The game is drawn when a position has arisen in which neither player can checkmate the opponent's king with any series of legal moves. The game is said to end in a ‘dead position’. This immediately ends the game, provided that the move producing the position was legal. 
* The game is drawn upon agreement between the two players during the game. This immediately ends the game. 
* The game may be drawn if each player has made at least the last 50 consecutive moves without the movement of any pawn and without any capture.
* **As soon as a player has only a king left on his side, the number of pieces belong to the opponent shall be observed. The game may be drawn if the player having only a king (lone king) left on his side can manage to escape in a number of fixed moves (move count shall be done starting from the very first move of lonely king) against the opponent of having particular pieces shown below:
  * Lone King vs. King & A Rook	- 16 moves
  * Lone King vs. King & An Elephant & A General	- 44 moves
  * Lone King vs. King & A Knight & A General	- 64 moves**

**Comment by Tev1903** [comment]
Hmmm. Well I'm not too familiar with the rules of Makruk or Sittiyun. It looked like the counting rules in Makruk also applied to Sittiyun. it also looked like the Tactics section in Sittiyun was copy and pasted from Makruk. Looking at it now, there are minor differences. Anyway, I thought the writer of the guide copy and pasted the tactics section while forgetting to add the counting rules that he would reference. As you have raised sufficient doubt in my own mind, I wouldn't change anything. You're probably right.

**Comment by Diwaditya** [comment]
@gbtami don't you think, this should get closed? Since, the typos are fixed.
