### ISSUE TITLE
Can Play disabled time controls with AI

### ISSUE THREAD

**Issue by lidevelopers** [gbtami/pychess-variants#533]
Can Play disabled time controls with AI like 
0+0  https://github.com/gbtami/pychess-variants/issues/531
0+1  https://www.pychess.org/NS33vIQH
0+2  https://www.pychess.org/tecBJPsh
0+3  https://www.pychess.org/ejfN2EKY
0+4  https://www.pychess.org/sHWFp81z

**Comment by lidevelopers** [comment]
some games are not saved because stopped before the third move but I can prove

**Comment by lidevelopers** [comment]
bug can be reproduce using inspect element https://github.com/gbtami/pychess-variants/issues/531

**Comment by Diwaditya** [comment]
@lidevelopers 
What's the use of playing these? And how did you even do that???

**Comment by gbtami** [comment]
Thx!
