### ISSUE TITLE
Atomic explosion sound played when I open an Atomic game

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#538]

**Comment by Diwaditya** [comment]
@gbtami 
Was it a bug? I thought you designed it to be like that.

**Comment by gbtami** [comment]
Pychess always plays explosion sound, for example when there was no explosion at all. Example game https://www.pychess.org/Tp2iwBXR
But it plays explosion sound when you open an ongoing game as spectator as well.

**Comment by ChronoMonochrome** [comment]
Anyone still working on this issue?
There must be some problem with the connection:

`Closed! CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: "", type: "close", …}`
`Reconnecting in round... CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: "", type: "close", …}`
`ctrl.onOpen() Event {isTrusted: true, type: "open", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}`

https://hastebin.com/uvavabawat.apache

When spending a few seconds on a move, the explosion sound is played, and my move is never reached the server (have to press prev + next move arrows or refresh the page).
This makes fast time controls in Atomic basically unplayable as it takes a lot of time to do so, as well as distracts from the game.
Admittedly, my Internet connection leaves much to be desired, however there is no such a problem, e.g. on lichess.

**Comment by gbtami** [comment]
@ChronoMonochrome your connection issue seems unrelated to this sound issue.

**Comment by ChronoMonochrome** [comment]
@gbtami 

I see, I figured the connection issue is related to my mobile operator, most likely (the problem didn't occur when connecting to the site from another network).
Is it worth opening a new issue (whilst the problem could be relied to the mobile operator solely and its restrictions on the ports / connections)?
I will try investigating further, as weirdly enough, websockets worked on lichess but not on pychess.

**Comment by gbtami** [comment]
@ChronoMonochrome  Created https://github.com/gbtami/pychess-variants/issues/588 for this.

**Comment by ChronoMonochrome** [comment]
Thanks!
