### ISSUE TITLE
Disable "draw offers" in shogi

### ISSUE THREAD

**Issue by ghost** [gbtami/pychess-variants#540]
End of the game	
The usual way for shogi games to end is for one side to checkmate the other side's king, after which the losing player will be given the opportunity to admit defeat. Unlike western chess or xiangqi, checkmate is almost always the end result in shogi since pieces never retire from play which gives the players a sufficient number of pieces to deliver checkmate. However, there are three other possible ways for a game to end: repetition (千日手 sennichite), impasse (持将棋 jishōgi), and an illegal move (反則手). The first two – repetition and impasse – are particularly uncommon. Illegal moves are also uncommon in professional games although this may not be true with amateur players (especially beginners).

# Unlike western chess, there is no tradition of offering a mutual draw by agreement.

_From Wikipedia_

**Comment by gbtami** [comment]
In pychess the "1/2" button is used for 
a) offer/accept draw
b) claim draw, in case of repetition or x move draw rules.
I think we need the "1/2" button for b) in Shogi.

**Comment by Diwaditya** [comment]
@gbtami 
Play some games in _Lishogi,_ did you find the "**½**" icon?

**Comment by gbtami** [comment]
Yeah, according to https://en.wikipedia.org/wiki/Sennichite 4-fold repetition is automatic draw in Shogi.

**Comment by Fulmene** [comment]
There are more variants (usually regional, like makruk) where repetition draw is automatic as well so this might worth creating another issue.
