### ISSUE TITLE
Checkmate message shown twice when game ended

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#547]
![https://cdn.discordapp.com/attachments/634298688663191584/859112946793840650/Bildschirmfoto_2021-06-28_um_18.06.08.png](https://cdn.discordapp.com/attachments/634298688663191584/859112946793840650/Bildschirmfoto_2021-06-28_um_18.06.08.png)
In  game https://pychess-variants-pr-543.herokuapp.com/xGplwVpr
```
[Event "PyChess rated game"]
[Site "https://pychess-variants-pr-543.herokuapp.com/xGplwVpr"]
[Date "2021.06.28"]
[Round "-"]
[White "dugong161"]
[Black "Doctor_Sticks"]
[Result "0-1"]
[TimeControl "60+1"]
[WhiteElo "1567?"]
[BlackElo "1766?"]
[Variant "Crazyhouse"]
[FEN "nbbrnqkr/pppppppp/8/8/8/8/PPPPPPPP/NBBRNQKR w DHdh - 0 1"]
[SetUp "1"]

1. c3 Nf6 2. d4 Nb6 3. Bg5 c6 4. Bxf6 exf6 5. Nb3 d5 6. Nf3 Re8 7. e3 Bg4 8. Qd3 B@e4 9. Qd2 Bgxf3 10. gxf3 Bxf3 11. B@g2 Bxg2 12. Kxg2 N@h4+ 13. Kf1 P@g2+ 14. Kg1 B@f3 15. N@g3 gxh1=Q+ 16. Nxh1 R@g2+ 17. Kf1 Bxd1 18. Qxd1 R@g1+ 19. Ke2 Rxd1 20. Kxd1 Rxh2 21. Ng3 Rxf2 22. P@g6 hxg6 23. Bxg6 Nxg6 24. P@f5 Q@c2+ 25. Ke1 P@d2+ 26. Kxf2 d1=Q+ 27. Ne2 Qdxe2+ 28. Kg1 Qxe3+ 29. Kf1 Qcf2# 0-1
```

**Comment by pepellou** [comment]
In case it helps, it happened with Campmate too in this game: https://www.pychess.org/n77dzdHZ

It happens only when playing (I imagine also when watching), after the game ends if I enter the url again it shows correctly only once.
