### ISSUE TITLE
Disable lobby chat sounds

### ISSUE THREAD

**Issue by Diwaditya** [gbtami/pychess-variants#556]
It's annoying, frightening and no one likes it :)
Also, do the same with tournament chat.

**Comment by gbtami** [comment]
Or make it optional.

**Comment by Diwaditya** [comment]
@gbtami 
Why opinional? No one like it!?

**Comment by Diwaditya** [comment]
@gbtami 
Yay! Thank you so much gbtami!! 👍🏻
