### ISSUE TITLE
Gorogoro - Intl promoted silver image missing

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#563]

**Comment by gbtami** [comment]
Hmm, seems ok here. 
![https://i.imgur.com/yZpzVZS.png](https://i.imgur.com/yZpzVZS.png)

**Comment by CouchTomato87** [comment]
Did you try flipping it?

**Comment by gbtami** [comment]
![https://i.imgur.com/vB8t4dM.png](https://i.imgur.com/vB8t4dM.png)

**Comment by CouchTomato87** [comment]
Hmmmm maybe it was just that it didn't load at the time!

**Comment by gbtami** [comment]
OK, I close this now. Feel free to reopen if needed.
