### ISSUE TITLE
Usage of FEN/SFEN for shogi variants

### ISSUE THREAD

**Issue by ianfab** [gbtami/pychess-variants#57]
Functionality-wise SFEN seems to work fine, but from the code I am a bit confused on where shogi variants use FEN and where SFEN. This is my current understanding of how they are used (please correct me if I am wrong):
* SFEN
  * UI (current (S)FEN, copy UCI/USI)
  * fairyfishnet
* FEN
  * pyffish
  * (custom) starting FEN
* SFEN/FEN hybrid
  * PGN

Can you please help me get a better understanding of how it works currently, what are the constraints/requirements (e.g., UI -> SFEN, PGN -> ?, etc.) and what the target picture is? I think there are two possible options for future development:
1. Use SFEN everywhere including pyffish, custom starting positions and UI
2. Use SFEN only for displaying and use FEN everywhere else

**Comment by gbtami** [comment]
There is one more player in the FEN/SFEN game, chessground(x) uses FEN to draw positions in web UI iirc.
https://github.com/gbtami/chessgroundx/blob/master/src/fen.ts
And yes, this is chaotic. Feel free to unify it.

**Comment by ianfab** [comment]
Ok, thanks. Is there a specific reason why PGN uses this hybrid format or is there any GUI that can read it?

**Comment by gbtami** [comment]
No. It's a bug/inconsistency.

**Comment by ianfab** [comment]
Since FEN -> SFEN conversion is at least theoretically losing some information (although not relevant for shogi variants), I think it would make sense to use FEN basically everywhere except for displaying. For displaying of SFEN one can then either use a simple variant-agnostic FEN -> SFEN converter in the backend as you already have it, or just always fetch both FEN and SFEN from pyffish and store both separately, and only use SFEN where needed.

I will probably resume this at a later point. This needs some more thoughts.
