### ISSUE TITLE
[Feature Request] Tournament description 

### ISSUE THREAD

**Issue by Diwaditya** [gbtami/pychess-variants#571]
Features like seeing standings and time left in the tournament is currently not a requirement.

Tournament description is needed for giving players the required information… like “top 100 players in the marathon will receive an unique trophy!” and so on.

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/7275550d2663769d346fc9159799b4b62e9e896c

**Comment by Diwaditya** [comment]
@gbtami
The progress is good! We're getting lots of features pretty fast.
