### ISSUE TITLE
Crosstable and Move List not hidden in zen mode

### ISSUE THREAD

**Issue by Diwaditya** [gbtami/pychess-variants#572]
![Screenshot_20210715-154230_Samsung Internet](https://user-images.githubusercontent.com/79149430/125772882-ed0fe3f1-2b76-47c8-a665-f5cb138c1eb9.jpg)

In lichess **Crosstable** and **Move List** are hidden too. **Zen mode** with Crosstable and Move List makes no sense and uncomfort!

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/6f260eb59cb3eecc976a05109feb36ab76318761
