### ISSUE TITLE
Vertical menu size problem on mobiles

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#576]
@CouchTomato87 reported on discord:
Menu size is weird, vertically
I keep clicking the wrong thing

![https://cdn.discordapp.com/attachments/641327060090093581/867821907214729236/Screenshot_20210722-133415_Chrome.jpg](https://cdn.discordapp.com/attachments/641327060090093581/867821907214729236/Screenshot_20210722-133415_Chrome.jpg)

**Comment by Diwaditya** [comment]
@gbtami 
I've also faced that problem but I thought that's too small to get noticed. I think the text are slightly below clicking area.
