### ISSUE TITLE
Illegal pawn moves in analysis board

### ISSUE THREAD

**Issue by ghost** [gbtami/pychess-variants#577]
_When you use “ANALYSIS BOARD” in mobile…_

You can't try different variations yourself, because it's not possible to move move your pieces nor your opponent's. But you **can** do some **illegal** **works** like _Making illegal pawn moves_ when it's your turn.

https://user-images.githubusercontent.com/79149430/126889669-8f37ce33-7a62-4150-aeb6-6b1e9bc07853.mp4

https://user-images.githubusercontent.com/79149430/126889671-246a548a-4a48-447f-a689-23040b3c92b9.mp4

**Comment by gbtami** [comment]
Can you able to reproduce this on current pychess site?
