### ISSUE TITLE
Hover effect for buttons missing

### ISSUE THREAD

**Issue by visualdenniss** [gbtami/pychess-variants#580]
Buttons like Join/Withdraw, Create a new tournament button etc (Basically all green boxes) do not have any hover effect triggered by mouse hover as on lichess. 

https://user-images.githubusercontent.com/80699817/126980603-ea4f69ef-df6a-463e-9c1d-d98249d01f73.mov

**Comment by TheChessGhost** [comment]
@visualdenniss 
Not only this, Lichess has many more effects which we didn't even noticed till now. Do you think, creating an issue about one small effect will change anything. I suggest to pychess v_2 something with a huge change in the design :-/
