### ISSUE TITLE
Promotion issues in new variants

### ISSUE THREAD

**Issue by kezsulap** [gbtami/pychess-variants#583]
Orda mirror:
Blog says: "Pawns can promote to any Horde piece"
Actual behaviour in a game is they can promote to queen or kheshig

Empire:
Blog says: "Pawns on either side can only promote to a queen"
In a game it works fine, but in analysis board queen, eagles and knights are available for either side (gold knight and black eagle are invisible, but can normally move)

**Comment by gbtami** [comment]
Orda Mirror promotion should be the same as in Orda. I think the blog and the rules page should be fixed.

The latter is fixed via https://github.com/gbtami/pychess-variants/commit/17884622659cf3d79aea1a7dd09b19e085ed122a
