### ISSUE TITLE
Create a new redirect at the "learn" URL?

### ISSUE THREAD

**Issue by notruck** [gbtami/pychess-variants#585]
The [Learn] tab points to this location: https://www.pychess.org/variant

New users may not notice it, and some might only remember it as the "Learn" page. When they try to visit https://www.pychess.org/learn (typed in by hand), they will get a 404 error because it doesn't yet exist. From the 404 page, they must then edit the address to return to the PyChess.org homepage and follow the link at the top. 

Would it be a good idea to create a new (almost empty) URL at https://www.pychess.org/learn and make it auto-redirect to the existing https://www.pychess.org/variant ? 

That way, both addresses will take them where they'd like to go. Thanks!

**Comment by notruck** [comment]
Hmm, the "learn" URL on lichess is actually reserved for a different purpose. 

https://lichess.org/learn#/

Maybe it's better to just leave it as a 404 page. I don't know.

**Comment by gbtami** [comment]
Maybe we should rename the "Learn" menu to "Rules", and use https://www.pychess.org/rules instead of https://www.pychess.org/variant?

**Comment by pepellou** [comment]
Would it be a good idea to name it "Variants" instead of "Rules"?

Most of those pages contain not just rules but also some piece of info/history and strategy tips, as well as links to further resources. Also the main page when you navigate there is titled "Pychess Variants" and lists all the variants.

**Comment by gbtami** [comment]
I like it! @notruck @CouchTomato87 ?
