### ISSUE TITLE
Internet connection problem

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#588]
@ChronoMonochrome reported in https://github.com/gbtami/pychess-variants/issues/538:

Anyone still working on this issue?
There must be some problem with the connection:

Closed! CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: "", type: "close", …}
Reconnecting in round... CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: "", type: "close", …}
ctrl.onOpen() Event {isTrusted: true, type: "open", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}

https://hastebin.com/uvavabawat.apache

When spending a few seconds on a move, the explosion sound is played, and my move is never reached the server (have to press prev + next move arrows or refresh the page).
This makes fast time controls in Atomic basically unplayable as it takes a lot of time to do so, as well as distracts from the game.
Admittedly, my Internet connection leaves much to be desired, however there is no such a problem, e.g. on lichess.
- - - - - - 
I see, I figured the connection issue is related to my mobile operator, most likely (the problem didn't occur when connecting to the site from another network).
Is it worth opening a new issue (whilst the problem could be relied to the mobile operator solely and its restrictions on the ports / connections)?
I will try investigating further, as weirdly enough, websockets worked on lichess but not on pychess.

**Comment by ChronoMonochrome** [comment]
Establishing a low ping values seems to remedy the issue. If the ping gets too high then the connection issues appear (as far as I figured it so far).

**Comment by gbtami** [comment]
Is this issue still exists for you?

**Comment by ChronoMonochrome** [comment]
The issue seems to be mostly gone now (only a few disconnections with ping 200-300 ms, but it gets quickly reconnected). There is still an explosion sound upon the reconnection though (idk if this is a feature, but seems a bit weird to me).

**Comment by gbtami** [comment]
Yea, that exploding sound issue is https://github.com/gbtami/pychess-variants/issues/538
I think we can close this issue now.
