### ISSUE TITLE
Refactoring and testing 

### ISSUE THREAD

**Issue by Bracewind** [gbtami/pychess-variants#59]
Currently, the code in utils does both the logic of the game (move, managing the board representation and knowing when the game start or finish), and the sending of some requests to the users : lobby_broadcast, round_broadcast and others. The requests received seems to be treated by the fishnet file.

Since there is currently some bugs when playing. It could be worthwile to know whether those bugs come from the logic or from the requests. 

To start this refactoring, I propose the creation of at least two entities : one in charge of doing all the logic done in utils and one in charge of sending and receiving requests. One more entity could be created to manage the different representations of a board game. 

I volunteer to do this work, and I will write at the same time unit tests on the different entities created.

**Comment by gbtami** [comment]
I don't really understand what kind of entities you like to create. Some concrete (pseudo?)code would be good to see.
