### ISSUE TITLE
Responsive design/mobile support

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#6]
On browsers, horizontal scroll is disabled even when the board is bigger than the window.

Also, not sure if mobile support is available, but when viewing on a mobile browser, a whole portion of the left side of the screen is cut off and not able to be viewed. Scrolling and resizing doesn't bring it into view.

**Comment by gbtami** [comment]
Thx for the feedback! Telling the truth I'v never had bigger board than the window. Will try to fix it.
There is no mobile support at this stage at all. Maybe later.

**Comment by CouchTomato87** [comment]
Just an update. I showed one of my friends the site, and he used his browser on a PC laptop. He had the same problem as my cell phone, where a large portion of the left side of the screen is cut off. I'm guessing that for any screen whose resolution is too low, the left side gets cut off. I'll show you an example from my phone, which is similar to the screenshot I saw from his laptop. 

![Screenshot_20190808-211847_Chrome](https://user-images.githubusercontent.com/52322435/62747760-d6178c80-ba23-11e9-89cd-c4735fc5110a.jpg)

**Comment by CouchTomato87** [comment]
Have you tried modifying the overflow settings?

https://www.w3schools.com/css/css_overflow.asp

All the elements work except the chat box, which becomes extremely clipped.

**Comment by gbtami** [comment]
This needs something like lichess got with v2.
https://lichess.org/blog/XMvcJSwAADkA0hPE/lichess-v2-is-here

**Comment by paulharris** [comment]
This site should easily be THE place on the internet for Chinese Chess Xiangqi.
Its awesome... but

The HTML layout etc breaks the website for many webbrowsers,
and getting it to work on mobile is key to getting users.
If it can become responsive, you wouldn't need to spend time on an app either.

Use Chrome on the desktop, menu, Web Developer, Responsive design.
Just not usable.  Would be awesome if it was usable...

**Comment by CouchTomato87** [comment]
The site is still a work in progress, so responsive design is planned. Everyone is aware of that limitation. Also, the only browser that doesn't work is IE and older versions of Edge, to our knowledge. If you know anyone who specializes in responsive design though, that would be helpful.

**Comment by paulharris** [comment]
Ok thanks, wish I could help but not able to.

**Comment by abunickabhi** [comment]
Is the issue of horizontal scroll fixed. I currently only have an android OS mobile device, and pychess only partially loads on it.

**Comment by gbtami** [comment]
Mobile support deployed, so i close this now.
Feel free to open new issues for responsive related bugs/regressions.
