### ISSUE TITLE
Show Opponent Piece Possible Movements

### ISSUE THREAD

**Issue by CricketForJapan** [gbtami/pychess-variants#604]
Clicking on your own pieces, and it show the possible moves of that piece.

Please could there be a setting to show the opponent's pieces possible move when clicking on them?

This would be useful. when defending.  I can't always remember all the moves of the variant pieces, so this feature would be great.  It could be an optional feature in settings.

**Comment by gbtami** [comment]
Idk is this possible at all with chessgroundx or not. We will see.

**Comment by Fulmene** [comment]
The best I can think of is reusing premove. This will need modifications to chessgroundx itself and it won't be trivial.

**Comment by gbtami** [comment]
I don't think it worth complicating more chessgroundx code base. People should learn variant rules (piece movements) reading our "Variants" pages.
