### ISSUE TITLE
Minimum break between pairings

### ISSUE THREAD

**Issue by ianfab** [gbtami/pychess-variants#605]
Tournament pairing of course sometimes is slow, but occasionally I also have the opposite problem. I know I want to pause after the game, but within a fraction of a second after returning to the lobby, I get paired and have to play another game. I think there should be some minimum break of at least 2-3 seconds to give players the chance to pause.

**Comment by gbtami** [comment]
Just notice that you can use the "PAUSE" button after game finish :)
Maybe it should be less terse. Maybe "PAUSE TOURNAMENT".
But the 3sec idea seems good, because people click on "BACK TO TOURNAMENT" most of the time anyway.
