### ISSUE TITLE
Add search feature for players

### ISSUE THREAD

**Issue by Tev1903** [gbtami/pychess-variants#614]
A friend of mine played a few games and I'd like to see them but I can't find them since there is no way to search by player. And the www.pychess.org/@/<their_name> address that someone suggested didn't work for me. Kept saying the site couldn't be reached. Now I'm probably entering it wrong but my point still stands that the site should be noob proof and simple for people. Makes engaging with the site easier and males people want to stay. So I think it'd be a huge improvement. Thanks

**Comment by gbtami** [comment]
You are absolutely right.
As a workaround (until someone implements this feature) you can use "All players" in the "Players" page, then Ctrl+F for text search. ![https://i.imgur.com/JUTeuj8.png](https://i.imgur.com/JUTeuj8.png)
![https://i.imgur.com/pCOt49Y.png](https://i.imgur.com/pCOt49Y.png)
