### ISSUE TITLE
Analysis board does not accept any moves

### ISSUE THREAD

**Issue by nnickoloff1234** [gbtami/pychess-variants#620]
Making any moves in analysis mode doesn't work.
In best case a piece could be moved/dropped once for the current side, this move will be reflected on the board, but not on moves list and that is all.

In console following error is visible:

`
Uncaught TypeError: this.ffishBoard is null
    sendMove https://www.pychess.org/static/pychess-variants.js.br?v=2baf3ae1ac621652eb1adcb4753c0f904069a8a6:923
    onUserDrop https://www.pychess.org/static/pychess-variants.js.br?v=2baf3ae1ac621652eb1adcb4753c0f904069a8a6:1094
    callUserFunction https://www.pychess.org/static/pychess-variants.js.br?v=2baf3ae1ac621652eb1adcb4753c0f904069a8a6:9524
`

**Comment by nnickoloff1234** [comment]
And the relevant line in analysisCtl.ts:

`
        const san = this.ffishBoard.sanMove(move, this.notationAsObject);

`

**Comment by gbtami** [comment]
Works for me. Possible more info needed to reproduce.

**Comment by nnickoloff1234** [comment]
Happens on Firefox 78.11.0esr (64-bit) on debian 10

Now tested on my other PC where i have Firefox 90 on Mint and it works fine there

Didn't realize it is due to old browser version (about 1 year actually - i have no idea if that is considered old in browser years nowadays)
