### ISSUE TITLE
Legal move not playable in Shako

### ISSUE THREAD

**Issue by Tev1903** [gbtami/pychess-variants#621]
https://www.pychess.org/25zDsMv7
Take a look at this position: 
![image](https://user-images.githubusercontent.com/85580484/132096972-c5c4a9cc-a1f8-49be-81ef-8abfade737b6.png)

 I'm playing Shako and I'm in check from Black's canon on f10 due to my pawn being on f5. I should be able to get out of check by playing fxe6. Yet I'm not being allowed to play that move. Think this is a bug.

**Comment by ianfab** [comment]
@gbtami  Fixed on Fairy-SF side in https://github.com/ianfab/Fairy-Stockfish/pull/351.
