### ISSUE TITLE
Indent lists in guides

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#624]
Currently, lists (for example ordered lists) are indented to the LEFT of the main text. Ideally, they should be indented to the right.

**Comment by gbtami** [comment]
We can try to add this to variants.css
```
.guide ol {
    list-style-position: inside;
    padding: 1vh;
}

```
![https://i.imgur.com/51s10XS.png](https://i.imgur.com/51s10XS.png)
