### ISSUE TITLE
Third party game creation

### ISSUE THREAD

**Issue by Fulmene** [gbtami/pychess-variants#629]
Make it possible to invite *two* players to play a game you create.

The main benefit of this feature is manual tournament organisation. It eliminates the need to educate the entire participants how to create games on Pychess, and just need a handful number of tournament organisers to have that knowledge. For this reason, it might be useful to restrict this feature to someone with the "tournament director" role only.

**Comment by Fulmene** [comment]
The design as discussed on Discord: The "director" will be taken to a screen with game link similar to the Play with a Friend feature. The difference is that instead of a single link, it'll present the director with two links, one for white, and one for black.

**Comment by gbtami** [comment]
I'm not sure about the design. That was just one quick idea. We can think about other designs as well.
