### ISSUE TITLE
analysis board bug with given FEN if black's turn

### ISSUE THREAD

**Issue by bmacho** [gbtami/pychess-variants#631]
[analysis board with given FEN when white's turn](https://www.pychess.org/analysis/chess?fen=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR%20w)
[analysis board with given FEN when black's turn](https://www.pychess.org/analysis/chess?fen=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR%20b)

In the later case, when someone moves, the moves and variations don't show up in the right hand box. A part of the program just die. 
This is because in analysisCtrl's sendMove function,  ffishboard.gameply() comes back with a greater value when the first move was black's. (See the [comment at 917 in  analysisCtrl.ts](https://github.com/gbtami/pychess-variants/blob/b3d9dcdd8ddb2cbc56e19dcbfa723e0c0554420a/client/analysisCtrl.ts#L917)) 

When I replace this.ffishBoard.gamePly() with newPly it seems to work, although I am not sure if we need the same number every time in the sendMove function, or in some cases the board's state changes, and we need that changed value.

**Comment by gbtami** [comment]
This is the same as https://github.com/gbtami/pychess-variants/issues/419 I think.
