### ISSUE TITLE
Create variant shields pages

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#634]
https://lichess.org/tournament/shields/crazyhouse

**Comment by visualdenniss** [comment]
also adding shield defender name to shield info box would be great. 
<img width="288" alt="Screen Shot 2021-09-15 at 10 50 15" src="https://user-images.githubusercontent.com/80699817/133402350-574f8c12-8952-448a-9ea6-a1e7fcb80685.png">
