### ISSUE TITLE
Local Analysis for S-chess 960?

### ISSUE THREAD

**Issue by notruck** [gbtami/pychess-variants#655]
Is local analysis for S-chess960 supported? I can't seem to switch it on, even though the mouse cursor changes when hovering over the button. 

https://www.pychess.org/R9IsFnT2

It's working fine for Shako in the same browser (Firefox 92 on Linux). 

Thanks!

**Comment by gbtami** [comment]
See https://github.com/gbtami/pychess-variants/blob/master/client/analysisCtrl.ts#L572

Also you have to wait a tiny bit more when hovering over the button to see the answer :)
![https://i.imgur.com/Lbg62mu.png](https://i.imgur.com/Lbg62mu.png)
