### ISSUE TITLE
Can you do Makpong (Thai Chess, Makruk(Pong).

### ISSUE THREAD

**Issue by thaichessswinboard** [gbtami/pychess-variants#66]
Rules of MakPong is  start position like Makruk but different rules. If you inCheck by opponent you can move King away but you can captures or you must protect Check. Example Rook Check Khun and you can protect Khun by move some Med or Cone or Knight or Rook to protect Khun only or try to move Khun away from Check of Opponent if Khun move or any pieces can't protect Khun it Checkmate. And if Khun of yours side have to captures by opponent it Checkmate too. Or if You have Check by Knight but yours can't captures Knight of Opponent side it Checkmate too.

Example 

1. Nb1-d2 Nb8-d7 
2. Sc1-c2 d6-d5  
3. Me1-f2 Md8-c7 
4. f3-f4  Mc7-d6 
5. Ng1-f3 Ng8-e7 
6. e3-e4  d5xe4  
7. d3xe4  Sf8-f7 
8. Mf2-e3 g6-g5  
9. Sf1-f2 Sc8-c7 
10. Kd1-c1 g5xf4  
11. g3xf4  Nd7-c5 
12. Kc1-b2 f6-f5  
13. e4xf5  Ne7-d5 
14. f5xe6=M Nd5xc3 
15. Nd2-b1 Nc5-a4 
16. b3xa4  Nc3xa4 

Check mate because it Check my knight and you must move Khun.

I hope you understand the Rules.

Regard.
PCST

**Comment by gbtami** [comment]
Only variants supported by Fairy-Stockfish have any chance to be added.

**Comment by Fulmene** [comment]
Since makpong is now supported by Fairy-Stockfish, could we consider reopening this?

**Comment by gbtami** [comment]
We should add Makpong (and Ka Ok for Ouk) as additional checkbox to new game dialog, similar to 960 option.
