### ISSUE TITLE
Point system for Janggi arena

### ISSUE THREAD

**Issue by Fulmene** [gbtami/pychess-variants#667]
Currently, winning by checkmate doesn't make any differences from winning by material scoring in Janggi arena. I propose to use the 7-point system in arena like in Janggi tournaments, and games that end in material scoring should be treated as draws for the purpose of arena rulings (like the game needs to last more than ten moves for it to count etc).

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/ec11bf3418972943200e4a88cef24937e961239e
