### ISSUE TITLE
Missing time and counting of bottom player on mobile

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#678]
![https://cdn.discordapp.com/attachments/884382880338415616/899917461678346310/Screenshot_20211019-140855_Chrome.png](https://cdn.discordapp.com/attachments/884382880338415616/899917461678346310/Screenshot_20211019-140855_Chrome.png)

![https://cdn.discordapp.com/attachments/884382880338415616/899917461888049162/Screenshot_20211019-140905_Chrome.png](https://cdn.discordapp.com/attachments/884382880338415616/899917461888049162/Screenshot_20211019-140905_Chrome.png)

**Comment by kezsulap** [comment]
It is, sorry for that. I opened a PR with a fix
