### ISSUE TITLE
PGN import is broken for 960 variants

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#693]
![https://cdn.discordapp.com/attachments/884382880338415616/905150454328074270/Screenshot_from_2021-11-02_18-42-27.png](https://cdn.discordapp.com/attachments/884382880338415616/905150454328074270/Screenshot_from_2021-11-02_18-42-27.png)

**Comment by kezsulap** [comment]
I looked into it. This happened because PGN copied from dev instance had [Variant "Capahouse960"] which isn't considered valid. When I tried importing this game as [Variant "Capahouse"] it worked fine.

**Comment by gbtami** [comment]
I think ffish.js doesn't recognize games as 960 when Variant tag ends with "960".
Maybe we should file this issue in Fairy-Stockfish repo as well.

**Comment by QueensGambit** [comment]
Thanks for the info.
Yes, it looks like there's a problem when reading 960 variants.
https://github.com/ianfab/Fairy-Stockfish/blob/b3a6aa1e8ecc1cfddf4230a0cc9cb5afe87ba192/src/ffishjs.cpp#L565-L568
It checks for the substring "960", but does not remove it from variant specification string.

The test pgn files also do not cover a 960 game, yet.
https://github.com/ianfab/Fairy-Stockfish/tree/master/tests/pgn
