### ISSUE TITLE
Opponent move cancels already started piece drag from pocket

### ISSUE THREAD

**Issue by catask** [gbtami/pychess-variants#70]
On lichess there is the option to take a piece from the gate and hover over the board, then when the opponent makes his move it can be dropped in very little time. On py-chess when hovering a piece from the gate on the board, and the opponent makes a move then the piece is returned to the gate.

**Comment by CouchTomato87** [comment]
Related to piece dropping, spectators can play with one side's pieces (I think it's black for shogi) but not the other's

**Comment by gbtami** [comment]
@CouchTomato87 that issue is fixed already.
