### ISSUE TITLE
Redirect to correct url, when opening incorrect ones but in same domain

### ISSUE THREAD

**Issue by nnickoloff1234** [gbtami/pychess-variants#735]
It would be nice if the HTTP server redirects the user to https, when the site was accessed via http, and also to "www" subdomain if it is missing. 

Then following easy to mistake urls will then work and open pychess:

https://pychess.org/
http://www.pychess.org/
http://pychess.org/

Also supporting plain text http i guess not nice for security reasons

**Comment by gbtami** [comment]
First one is fixed now and the remaining issues are tracked in https://github.com/gbtami/pychess-variants/issues/1111
