### ISSUE TITLE
Allow classical chess army in Empire Chess to be rearranged.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#748]
You can rearrange the pieces of the Imperial army…but the regular classical chess pieces aren’t allowed to be shuffled. Please add the ability to rearrange the classical chess pieces in Empire Chess. Thanks.

**Comment by gbtami** [comment]
Can you provide a FEN or screenshot/video to let us see what is not allowed please?

**Comment by Curious2021** [comment]
bnrkrbnq/pppppppp/8/8/8/PPPSSPPP/8/TECDKCET[] w - - 0 1 is a valid position which is accepted but the castling rules get ignored even though the editor clearly shows you should be allowed to castle using chess960 rules.

**Comment by Curious2021** [comment]
You can shuffle the classical pieces ONLY IF YOU CLEAR THE ENTIRE BOARD. But this shouldn’t be necessary if the shuffled pieces are valid. In this case why would it be necessary to wipe the entire board just to shuffle the back rank pieces? That’s overkill. And if you rearrange the back rank classical pieces the editor refuses to accept the position if the rooks are not in the corners. But if you WIPE the entire board you can rearrange the rooks anywhere on the back rank without any error warning from the editor but chess 960 castling rules are ignored for the classical chess pieces.

**Comment by gbtami** [comment]
Our About page clearly states that 960 castling version is available for Chess, Crazyhouse, Atomic, S-chess, Capablanca, and Capahouse variants only.

**Comment by Curious2021** [comment]
I stand corrected. Alright but why the requirement that the entire board be wiped to set up the back rank pieces? Couldn’t it be possible to rearrange the back rank pieces without disturbing the pawns? In other words rearranging back pieces is not possible while the pawns are in place. You have to wipe the pawns for the back rank arranging of pieces to be considered a valid setup.

**Comment by gbtami** [comment]
You can rearrange back rank pieces as you want. But if you moved rooks/king out from theirs initial position, it is your duty to click off castling rights check boxes accordingly. I mean Editor is dumb. It doesn't know much about variant rules.
