### ISSUE TITLE
Add KoTH variant to Pychess

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#749]
Please consider adding the chess variant KoTH just like Lichess has but with additional options like chess 960 setups which Lichess doesn’t allow.

**Comment by SriMethan** [comment]
I already made a pr for this https://github.com/gbtami/pychess-variants/pull/725 and it got closed, look at https://github.com/gbtami/pychess-variants/pull/725#issuecomment-992198554
