### ISSUE TITLE
Analysis: Wrong side drop suggestion in shogi

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#75]
In the analysis, when a drop is suggested, the suggestion uses the image for the opposite side rather than your own.

**Comment by gbtami** [comment]
I always forget in Shogi EVERYTHING is opposite :)

**Comment by gbtami** [comment]
Am I correct that this is only happens when board view is flipped?

**Comment by CouchTomato87** [comment]
Ah, yes it is.
