### ISSUE TITLE
Game abort countdown needs to be one or two minutes.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#751]
30 seconds is simply too short to allow us time to make a move before games get aborted. Please increase the countdown to one minute or even 2 minutes would be even better.

**Comment by gbtami** [comment]
We use lichess countdow times before game start. Longer waiting times may be counter productive in arena tournaments and may annoy players when opponent doesn't appear in time.

**Comment by Curious2021** [comment]
Do you need countdown when playing against an engine?!

**Comment by gbtami** [comment]
If you was not able to make a move in time, you can start another AI game immediately.
