### ISSUE TITLE
Switch sides during games against engine. 

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#755]
This is NOT a new variant Gbtami. So this satisfies your insistence on not adding any new variants. This is simply a request to allow players who play games against Stockfish to be able to switch sides during the games. Currently when you play any variant you’re stuck playing your color through the whole game. But against engines this shouldn’t be necessary and it would be helpful if you could switch sides during the game against the computer. So I’m requesting you allow one to switch sides during games against Stockfish only. No, Lichess doesn’t let users do this on their site but this lack shouldn’t deter you from being able to enable this on Pychess. My two cents.

**Comment by gbtami** [comment]
If you are curious what Stockfish think about a given position you can use analysis mode, or other local chess GUI.
