### ISSUE TITLE
S-chess enhancement…alternate start choice allowing pieces to be part of starting position.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#765]
In the rules of S-chess, you place the elephant and hawk on vacant squares after the original pieces leave the starting position. In this proposed alternate starting position, the player can choose to replace the starting pieces and simply use the elephant and the hawk in the initial position and play on from there. We currently are able to do this manually in the editor…but it would be nice to have this ability offered in the alternate choice of position setups in the dialog box when choosing to play Seirawan Chess.

**Comment by gbtami** [comment]
S-Chess, S-Chess960 and S-House are more than enough from one kind of chess variant.
