### ISSUE TITLE
Spectator issues

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#77]
Some spectator comments:

1. For spectators joining the game midway and wanting to go through the game on their own, the actions during the game make it jump to the current move, which is to the annoyance of the spectator.

2. The "give time" button still shows up for the spectators (although it appropriately doesn't work).

3. Chats don't merge after the game is over.

**Comment by gbtami** [comment]
I can't reproduce 3.
Can you open a new issue for this with more details please?
