### ISSUE TITLE
Analysis tab not working

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#775]
**Exact URL where the bug happened**

**Steps to reproduce the bug**
Finish any game and hit the analysis tab to run variation analysis of moves in the game. Nothing happens.
**What did you expect to happen?**
Pychess would immediately run a quick blunder check of the moves played to find any improvements.
**What happened instead?**
Nothing.
**Operating system and browser version**

**Comment by gbtami** [comment]
No. This is **not** expected even on lichess.
