### ISSUE TITLE
Rule for kaiser king faceoff in Empire Chess needs updating

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#776]
I just discovered the real reason for the kaiser king faceoff rule in Empire Chess. Apparently if there are no pieces intervening between the kaiser and the king...the gold army king is not allowed to escape from check if the kaiser is facing off with the royal black king while it's on the same file. This is not made explicit in the rules of Empire Chess. It just states the kaiser and the king "can't face off"...with no explicit explanation for this rule. Only via trial and error do I understand what the meaning of this rule is. Couch Tomato needs to update the explanation for the kaiser king face off requirement with an explicit meaning of this rule.  Another detail about this rule is that it appears to only apply to the Gold army. Not the regular chess army which is Black.

**Comment by gbtami** [comment]
@CouchTomato87 updated Empire Chess docs. Hope this helps.
