### ISSUE TITLE
Request for chess960 position ID box.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#779]
The reason for this request is because when the server unexpectedly reboots in the middle of a game you LOSE the position you’re trying to study and this goes to waste. A chess960 position ID box would FIX this annoyance. Because then a player could input the position ID to reset the game again with the exact FEN start position. This is a reasonable request and I believe this has merit.

**Comment by gbtami** [comment]
Yo can get the aborted game starting FEN in Analysis mode and use it as custom FEN to create a new game.
