### ISSUE TITLE
Analysis tab not allowing any position to be input using an iPad device.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#781]
**Exact URL where the bug happened**

**Steps to reproduce the bug**
On a iOS iPad tablet try setting any position using the Analysis tab manually. The pieces refuse to move to their new positions and you cannot activate the button allowing a local Stockfish analysis of that position. 
**What did you expect to happen?**

**What happened instead?**
Nothing. 
**Operating system and browser version**
iOS 15.1 built in Safari.

**Comment by gbtami** [comment]
1. Analysis menu is not Editor! You should make valid moves only.
2. Local (in browser) Fairy-Stockfish analysis is not supported for user defined variants. See https://github.com/ianfab/stockfish.wasm/issues/4
3. stockfish.wash has requirements described on https://github.com/ianfab/stockfish.wasm
Idk your iPad supported or not at all.
