### ISSUE TITLE
Sittuyin docs needs more detailed rules section

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#783]
**Exact URL where the bug happened**

**Steps to reproduce the bug**
In the Sittuyin variant of Makruk you can’t place the rooks anywhere on your side of the board. There is no explicit rule stating the rooks must only be placed on the first rank.
**What did you expect to happen?**
I should be allowed to place the rooks anywhere in this variant. 
**What happened instead?**
The rooks are forcibly only allowed on the first rank and there are no rules stating this to be a requirement.
**Operating system and browser version**
ios 14.1 iPad or iPhone.

**Comment by gbtami** [comment]
In Sittuyin you can place your rooks on the back rank only. See https://vdocuments.net/how-to-play-myanmar-traditional-chess-eng-book-1.html
Seems our docs is rather succinct regarding the rules.
