### ISSUE TITLE
Cannot add elephants and hawks in Seirawan Chess via the editor GUI. Must be typed.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#785]
**Exact URL where the bug happened**

**Steps to reproduce the bug**
you must be in the editor and select the variant Seirawan Chess. The dialog box shows a graphic of the elephant and hawk with a number next to the symbol telling you the number of elephants and hawks that can be used in the game of Seirawan Chess. The counter is set to 1. However one is SUPPOSEDLY to have the ability to use a finger, mouse or Apple Pencil to tap on the icons with the elephant and hawk to alter this counter and increase the number of elephants and hawks that can be used in that variant. 
**What did you expect to happen?**
Tapping on the elephant and hawk icons would increase the number of pieces that can be brought to bear in the game. 
**What happened instead?**
Nothing happens anymore. It used to work before. 
**Operating system and browser version**
iOS 15.1 iPad

**Comment by gbtami** [comment]
You can drag and drop pieces below/above the board to the pockets.

**Comment by Curious2021** [comment]
I tried as you described and it doesn’t update with the new tally when i try dragging the pieces to the pocket.

**Comment by gbtami** [comment]
Seems your issue is the same as https://github.com/gbtami/pychess-variants/issues/612 then.

**Comment by Curious2021** [comment]
Gbtami, I just tested the editor and discovered that the drag and drop of the pieces work...but ONLY if I'm using a Windows desktop. I cannot add the pieces to the pockets using the iOS browsers on the iPhone and iPad OS. This needs a separate ticket if you want I'll write it up. Otherwise this does need to be fixed.
