### ISSUE TITLE
Allowing pawns on the first and last ranks to move two spaces.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#789]
I see Pychess allows pawns on the first and last ranks but the pawns only move one space. Could you consider allowing the program to recognize pawns moving two spaces from the first and last rank?

**Comment by gbtami** [comment]
We don't have variants with this kind of pieces at all.

**Comment by Curious2021** [comment]
Wait a second. There are drop variants that allow pawns onto the first rank that are allowed to go two steps Gbtami.

**Comment by gbtami** [comment]
No. They can move one step only from back ranks.

**Comment by Curious2021** [comment]
oh…i didn’t read that line carefully. i automatically assumed that meant it could go 2 steps. my bad.
