### ISSUE TITLE
How about double move chess variant?

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#795]
Same rules of classical chess but each player gets to play two moves per turn.

**Comment by gbtami** [comment]
https://www.pychess.org/faq

**Comment by Curious2021** [comment]
Is it because Stockfish Fairy doesn’t support it or is it because you simply don’t want to add this? Double move chess would be a fun variant and no other site offers it. Pychess would be the only place in the world to play this.

**Comment by kezsulap** [comment]
Yes there is a site supporting double move chess https://greenchess.net/rules.php?v=double-move

**Comment by Curious2021** [comment]
That is mail only. not live.
