### ISSUE TITLE
Shogi last move highlight not working

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#8]
Was watching some random replays and noticed that for shogi, the green highlight boxes for the most recent move do not work when reviewing the game. When you open a game (for example https://pychess-variants.herokuapp.com/4Yk3ElYX ) the highlight is there. But as soon as you go back either one step or to the beginning, the highlights don't work. I've checked S Chess and Xiangqi -- both of those still work.

**Comment by gbtami** [comment]
Thx for reporting this!
