### ISSUE TITLE
undefined piece moving

### ISSUE THREAD

**Issue by helloplaychess** [gbtami/pychess-variants#810]
https://prnt.sc/26hjk1h

I enter a few moves and I see this in the console

now there is a main line created

in the middle of the main line I create a side-line

https://prnt.sc/26hjl6q

first of all, the moves are not being shown until I make one move for white and one for black

and now, when the moves are not being shown and I press the button to go one move back or one move forward, it will send an error message: red:

https://prnt.sc/26hjm2o

**Comment by helloplaychess** [comment]
important to note: the yellow messages only show up when the engine is on, so this is engine output

**Comment by gbtami** [comment]
May I ask you too use full image links and ! at the beginning please, to let github display them and save us from extra clicking. For Something like this ![https://i.imgur.com/eCQovi7.png](https://i.imgur.com/eCQovi7.png)

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/0860a5d3de8aa6316eb954a34ee1b648d50f0574
