### ISSUE TITLE
Remove abort countdown for human vs engine play.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#813]
I can understand keeping a abort countdown for games between humans. But this is not necessary for games between humans and Fairy Stockfish. Please remove this requirement. Lichess does NOT do this on their website in human vs engine play.

**Comment by gbtami** [comment]
Countdown is useful to keep server in healthy state and prevent growing useless abandoned games number.
You can start new engine games any time  if you miss the start.
