### ISSUE TITLE
Make the pocket item counters responsive

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#814]
When you change the size of the board the pockets get so small the number of the pieces listed in the pockets are covered up by the number icons. Therefore you can't see what the pieces are in the pocket. A tooltip popup would allow the player to know what piece is in the pocket by hovering a mouse over the piece number.

**Comment by gbtami** [comment]
I don't think this would be the good fix. I think we should make the pocket item counters responsive instead.
