### ISSUE TITLE
Spactators have to click on latest move button to catch up current position

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#82]

**Comment by CouchTomato87** [comment]
What should it be?

**Comment by gbtami** [comment]
Sometimes when the the spectator arrives to an ongoing game he stucked in the arriving position. He didn't moved at all in the move list backwards! New moves are coming to the move list, but the position  is just the same what he got when he arrived. It should be updated with incoming moves/positions.

**Comment by CouchTomato87** [comment]
Oh, I just witnessed that myself and got confused. I think the problem is still happening even though this is closed then!

**Comment by gbtami** [comment]
Because it is not deployed yet :)
