### ISSUE TITLE
stealth promotion in shogun chess.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#831]
https://www.pychess.org/A991w2RD

Link shows knight promotes to a general but the choice to promote the piece isn’t shown until AFTER the next move is played by the opponent. In effect it stealth promoted its original piece to the promoted piece without prior knowledge after the prior move is completed. If this move is legal then i should be allowed the same privilege to stealth promote a piece without my opponent’s knowledge.

**Comment by gbtami** [comment]
Works for me. 
![https://i.imgur.com/OjHVPbY.png](https://i.imgur.com/OjHVPbY.png)
Can you provide a screenshot/video about your issue please?

**Comment by Curious2021** [comment]
The issue is fairy stockfish promoted to a general but I didn’t see this after it reached the promotion zone. it revealed its promoted status until after the next move. meaning…it promoted to the general on the previous move but this is not shown. the link is the game…just fast foward through the game and you’ll see the issue.

**Comment by gbtami** [comment]
No. You misunderstand the rules.
9...Nc3 was NOT a promotion move. Promotion is NOT mandatory!
11...Na4=G was a promotion move!
