### ISSUE TITLE
Draw offer causes sound to disappear.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#837]
After offering  a draw to a computer opponent causes the sound to go silent. To get the sound back…you need to leave the site and return to the website to get the sound back. This can be duplicated on any variant. I got it when i was playing Ouk Chatrang. it happened on my iOS iPad 3rd generation 512 gig capacity edition iOS 15.3.

**Comment by gbtami** [comment]
I can't reproduce this.
Offering draw to Fairy is meaningless anyway, because it never accepts it.
