### ISSUE TITLE
Misjudgement of fairystockfish in Xiangqi analysis

### ISSUE THREAD

**Issue by NelloHo** [gbtami/pychess-variants#843]
**Exact URL where the bug happened**
https://www.pychess.org/analysis/xiangqi?fen=c3k2C1/4anR2/9/3NP4/9/6n2/9/1r1p5/4p4/3K5[]_w_-_-_0_1
https://www.pychess.org/analysis/xiangqi?fen=c3k2C1/4a4/6R2/9/9/9/9/9/9/3K5[]_w
**Steps to reproduce the bug**
When using the Xiangqi analysis mode with a rook and a canon on the same line.
**What did you expect to happen?**
It still require a few steps to end the game. 
**What happened instead?**
Fairy-Stockfish judges a "rook-canon" check to be "checkmate" and shows "#1" and recommand R3+1 in analysis mode !
Actually, black a5-6 will simply avoid the check. After I did that, the engine stops, however, the game is not over!
I find out that everytime a rook and a canon are on the bottom line checking , the engine will misjudge it to be checkmate.

**Operating system and browser version**

<img width="950" alt="未命名2" src="https://user-images.githubusercontent.com/99171663/152753916-3a47ff6d-b233-4584-aec5-be65b74904b9.png">
<img width="956" alt="未命名" src="https://user-images.githubusercontent.com/99171663/152753934-321bd623-ccd3-43c6-be60-9d4f6a4876ab.png">

**Comment by gbtami** [comment]
This is a bug in https://github.com/ianfab/stockfish.wasm already fixed in upstream https://github.com/ianfab/Fairy-Stockfish
It can be fixed updating wasm port with upstream changes.
