### ISSUE TITLE
Copy FEN position of current game. 

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#855]
Currently you cannot copy an FEN chess position of a game in progress. This would be helpful if while playing a game you suddenly get a notification the Pychess server needs to reboot…causing all the hard work you put into a position to be lost forever. It would be nice to be able to save positions like this as they could be copied via browser or iPhone.

**Comment by gbtami** [comment]
On server restart ongoing games are aborted and saved. You can open them later, go to Analysis and copy-paste the FEN.
