### ISSUE TITLE
Birds flying all over the place in mobile tournament view

### ISSUE THREAD

**Issue by kezsulap** [gbtami/pychess-variants#863]
![Screenshot_20220223_170921_com android chrome](https://user-images.githubusercontent.com/16389252/155412288-983aaa8e-db6c-4133-bed5-4738faec8758.jpg)
![Screenshot_20220223_170819_com android chrome](https://user-images.githubusercontent.com/16389252/155412312-91102ca7-1a48-47f3-b99c-f9ed12a755b1.jpg)
![Screenshot_20220223_170800_com android chrome](https://user-images.githubusercontent.com/16389252/155412384-84c27d2a-76ef-42d6-9637-409c5cd4da96.jpg)

They way I could reproduce it was to hold a finger on a pocket for a second or so and then scroll, but it also occurred naturally when I was just trying to scroll the page

**Comment by gbtami** [comment]
@nnickoloff1234 @Fulmene any idea? Is it related to click drop stuff maybe?

**Comment by Fulmene** [comment]
This is because chessground has movable colour be `'both'` by default. Setting it to `undefined` in any view-only chessground, along with #992 , should fix this.
