### ISSUE TITLE
Promoted pawn should be shown as such, as opposed to met, in Makruk

### ISSUE THREAD

**Issue by Fulmene** [gbtami/pychess-variants#87]
In a real Makruk game, promoted pawns are represented by flipping the pawn piece over. Although they are functionally the same as the met, the discrepancy from the OTB game is quite jarring. Furthermore, they are also notated differently in game notation.

I'm willing to solve this issue myself, but I think I'll need some guidance on how each part of the code works.

**Comment by gbtami** [comment]
Screenshot from PlayOK
![http://i.imgur.com/aIB40CS.png](http://i.imgur.com/aIB40CS.png)

**Comment by gbtami** [comment]
Our problem as ubdip explained in Discord chat: "promoted pawns and met can not be distinguished in makruk FENs".
The site is based on Fairy-Stockfish (server side) and chessgroundx (client side), and they are communicating via FEN.

**Comment by ianfab** [comment]
Proposed solution as discussed:
* [ ] Implement option in Fairy-Stockfish for `Position::fen` to indicate promoted pieces with `~` even if not required (in contrast e.g. to crazyhouse).
* [ ] Allow to use the aforementioned option in `get_fen` of pyffish.
* [ ] Use it in pychess-variants to generate the FEN passed to chessgroundx for makruk.

**Comment by ianfab** [comment]
I pushed a first version of the code that allows to generate makruk FENs with promoted pawns in Fairy-Stockfish. However, although the changes are small, they touch core parts of the board representation and could potentially completely break multiple variants, therefore it needs extensive testing before it can be merged.
