### ISSUE TITLE
Janggi pieces graphics are extremely blurred.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#877]
![6CEB61CB-110F-4BFC-BA88-F1A425C65172](https://user-images.githubusercontent.com/73664660/156945125-39434947-f440-4a02-8eda-5c8db665338b.png)

**Comment by Curious2021** [comment]
you want to explain why i’m seeing this blurry image when i try using this piece set?

**Comment by gbtami** [comment]
This is possible your mobile browser rendering issue, because pieces are .svg so it should be sharp.
And on my Huawei Android phone they are perfectly rendered.
Maybe your mobile browser version is not the latest?

**Comment by Curious2021** [comment]
.on a hunch i decided to clear out my Safari cache and reloaded the browser. this appears to have solved the problem…as the cache somehow corrupted the graphic images of the pieces when I resized them.
