### ISSUE TITLE
Tournament games aborted by server restart (or any other reason) shouldn't affect player rating

### ISSUE THREAD

**Issue by Fulmene** [gbtami/pychess-variants#884]
**Exact URL where the bug happened**
https://www.pychess.org/zFreVTMI

**Steps to reproduce the bug**
1. Play a tournament game.
2. Get the game aborted by any way other than initial move timeout.

**What did you expect to happen?**
No change to the players' rating.

**What happened instead?**
There are some changes to the players' rating.

**Operating system and browser version**
Irrelevant.

**Comment by gbtami** [comment]
I have absolutely zero idea how this happened, because `update_ratings()` call is guarded by `if self.result != "*":` https://github.com/gbtami/pychess-variants/blob/master/server/game.py#L415 and it is not called anywhere else.

**Comment by gbtami** [comment]
Tournament games are not aborted any more (after games are paused/resumed on server restart).
