### ISSUE TITLE
Remove link to Lichess profile for Anonymous players?

### ISSUE THREAD

**Issue by notruck** [gbtami/pychess-variants#89]
This one is only a minor detail. No real difference whether it's "fixed" or not, but since those anonymous players don't have a corresponding profile on Lichess, shall we remove their @ links?

**Comment by notruck** [comment]
Amusingly-named random guest's profile for easy reference:

https://pychess-variants.herokuapp.com/@/AnonymousRUOK

**Comment by gbtami** [comment]
Thx, agreed.
