### ISSUE TITLE
Win rate percentage bug

### ISSUE THREAD

**Issue by shuvashish76** [gbtami/pychess-variants#890]
Self-explanatory

![Screenshot_2022-03-24-23-10-18](https://user-images.githubusercontent.com/48226312/159977740-f5c6bddc-00e4-4bb2-b62e-7ef78862aaa9.jpeg)

https://www.pychess.org/tournament/VNAIr1tp

**Comment by gbtami** [comment]
This is duplicate of https://github.com/gbtami/pychess-variants/issues/675
