### ISSUE TITLE
Numerical value of material difference of piece captures.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#897]
In lichess, if you selected the option to show material difference you get not only a graphical representation of the pieces captures…but you also get a numerical value of the total amount of that difference. For example, you get 3+ in case you have a rook and a pawn vs a bishop. Currently Pychess doesn’t support this.

**Comment by gbtami** [comment]
This is duplicate of https://github.com/gbtami/pychess-variants/issues/353
