### ISSUE TITLE
Transparency of game request settings

### ISSUE THREAD

**Issue by ianfab** [gbtami/pychess-variants#9]
There are two scenarios where I found it difficult to keep track of the game settings:
- The chess960 flag is not be visible in the list of game requests, so the opponent does not know about it before accepting the request.
- The AI level from the "play with the machine" dialog is not shown anywhere during or after a game.

**Comment by gbtami** [comment]
I can't decide what would be better to 960 flag to use. Text or icon? Maybe some icon, because the number of Caparandom starting positions is not 960.

Yes, adding AI level here and there is needed and planned.

**Comment by ianfab** [comment]
To me a dice would make sense, since it only indicates the randomization but does not directly refer to the number of positions. At least unless you want to support dice shogi, then it would of course better fit there ;-)

**Comment by gbtami** [comment]
- [x] chess960 flag (dice)
- [ ] show AI level

**Comment by ianfab** [comment]
@gbtami Thanks. Just one minor issue: When clicking on the name of a bot in a game, it links out to an invalid user name, e.g., https://pychess-variants.herokuapp.com/@/Elephant-Eye%20level%201

**Comment by gbtami** [comment]
Thx! Will try to fix it ASAP.

**Comment by ianfab** [comment]
Thx, works fine now.
