### ISSUE TITLE
Shogi board/sqare dimensions are not correct

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#915]
Seems lishogi 11/12 is the correct one. See here also https://boardgames.stackexchange.com/questions/10836/specific-standard-measurements-and-info-necessary-for-making-a-standard-shogi-se
@CouchTomato87 what do you think?

**Comment by Fulmene** [comment]
Where do we get the 13x15 dimensions from anyway? Is it ShogiGUI?

[Shogi Playground](https://play.mogproject.com) seems to use the 11x12 ratio also, according to my eyes. It's the ratio from the physical board, so we really can't go wrong with it I guess.

I assume simply changing the dimensions in the board images would do the trick, provided the centering code from the Portella piece set works correctly?

**Comment by gbtami** [comment]
For 11:12 they have 4 only. ![https://i.imgur.com/nIll0vt.png](https://i.imgur.com/nIll0vt.png)
![https://i.imgur.com/hWrDtof.png](https://i.imgur.com/hWrDtof.png)

**Comment by CouchTomato87** [comment]
I can work on making 11:12 versions of I use those as a basis. Making new boards is easiest, right?

Making new piece sets may be much much more challenging

**Comment by gbtami** [comment]
Possible pieces will be OK on 11:12.

**Comment by CouchTomato87** [comment]
I think the line thicknesses may get skewed though? Especially for the png
boards. Recreating boards might not be terribly difficult. And if Lishogi
uses 11x12, then we don't even need to recreate -- just use those :)
