### ISSUE TITLE
Why is a perfectly valid FEN position being rejected by the editor?

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#920]
Why is this pasted FEN position I generated being rejected by the Pychess editor? I made sure to uncheck the castled positions and I still get a red marker surrounding my FEN as being invalid for consideration. Here is the exact FEN code I generated. Can somebody please explain this?

3rr1k1/3q2p1/R4p1p/1p2p3/nP6/P1P1Q1BP/K3NP2/2R5

**Comment by gbtami** [comment]
This FEN is incomplete. You have to add "side to move"  w or b at lest.

**Comment by Curious2021** [comment]
Reopen this ticket then, Gbtami…because I took that out thinking that was what was causing the problem. Originally it had the side to move option in the code…W 33. It still wasn’t working.

**Comment by gbtami** [comment]
What is the variant you set up on Editor page and what is the exact FEN you paste there?

**Comment by Curious2021** [comment]
Chess was the variant and that was the exact FEN code I pasted in there.

**Comment by gbtami** [comment]
Works for me.
Attach a screenshot please.

**Comment by Curious2021** [comment]
What would a screenshot do what a FEN position code can’t? i’m sorry gbtami but i’m not going to post a photo of a simple copy and paste job unless you can tell me what this will do to show you what’s wrong. Because I’m not getting your reasoning for it.

**Comment by gbtami** [comment]
This is how it works for me. I just want to see how it looks like for you. Maybe I will notice what is the difference.
![https://i.imgur.com/HtIm63k.png](https://i.imgur.com/HtIm63k.png)

**Comment by gbtami** [comment]
If you use "W" instead of "w", that explains it.

**Comment by Curious2021** [comment]
Not only the w but also the two hyphens at the end signifying the move order number when setting up the position. Because this must be specified during the setup of the position as well denoting the exact moment in the game the position can be recreated.

**Comment by gbtami** [comment]
Standard starting position FEN is `rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1`
It contains 6 parts. Pychess can create meaningful defaults  (- - 0 1) for missing latest 4 parts, but you have to provide "w" or "b" next to the placement part.
