### ISSUE TITLE
Perfectly legal option to castle during chess960 game not permitted. 

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#922]
https://www.pychess.org/iIeULP6H

This is position number 701 on the chess960 website which i just tried to play in this position id in pychess which allows chess 960 to be played. I immediately resigned this game because it would NOT allow me to castle short using the position you see in the graphic at the very end when I resigned. My king is not in check, and I made sure the option to castle was enabled in the setting while choosing chess960. There is absolutely no excuses this time. Period.

**Comment by gbtami** [comment]
According to https://www.pychess.org/iIeULP6H?ply=0 you missed to give castling rights in start FEN.

**Comment by Curious2021** [comment]
> Until #554 not fixed you have to give correct castling rights in the new game dialog FEN input field.

That's exactly what I did. And it still wouldn't allow me to castle. I'm telling you there's a problem with the castling rights even using your strict instructions. I followed the instructions and it still wouldn't let me castle.

**Comment by gbtami** [comment]
No. You missed to provide castling rights in start FEN. ![https://i.imgur.com/h0xRhsz.png](https://i.imgur.com/h0xRhsz.png)
I tried it myself with correct FEN. Castling works as expected. See in https://www.pychess.org/2rYnWRnT?ply=19
