### ISSUE TITLE
Can't choose a piece in chennis/kyoto when dropping a piece with two clicks

### ISSUE THREAD

**Issue by kezsulap** [gbtami/pychess-variants#941]
When I tap a piece in a pocket and then a square rather than drag it I don't get the option of choosing a piece, instead the promoted version get dropped automatically. It doesn't happen 100% of the time, but most of the time. Also I haven't tested it with mouse rather than touch input

**Comment by Fulmene** [comment]
Should be fixed with [655e3be](https://github.com/gbtami/pychess-variants/commit/655e3be5a6ee6d5e8652bd5329671a2f683627ba)
