### ISSUE TITLE
Drop suggestion piece type is incorrect after flip board

### ISSUE THREAD

**Issue by gbtami** [gbtami/pychess-variants#942]
Example: start position in https://www.pychess.org/gQj8wkFm?ply=0
![https://i.imgur.com/JWgx76G.png](https://i.imgur.com/JWgx76G.png)

**Comment by Fulmene** [comment]
This can potentially be solved by merging latest chessground into chessgroundx. Although I'd probably need a bit of time to read their exact code.

**Comment by Fulmene** [comment]
Fixed in [114c599](https://github.com/gbtami/pychess-variants/commit/114c599563fdf86228f95e231cddbaaf464c28fd)
