### ISSUE TITLE
Max Cores Always Used

### ISSUE THREAD

**Issue by WeniMakOfWay** [gbtami/pychess-variants#958]
On lichess I go into options and set analysis to just 1 core.

On pychess there is no such option and it seems to use all cores. My computer overheats when all 8 cores are being used. As a result I am unable to analyse my games.

I think pychess should definitely have this option to tweak #cores as a necessity. Or at least make the default only use 1 core.

**Comment by gbtami** [comment]
You are absolutely right. This is already in https://github.com/gbtami/pychess-variants/issues/303
