### ISSUE TITLE
Bug with the last games in the tournament

### ISSUE THREAD

**Issue by MaxLand13** [gbtami/pychess-variants#966]
[Tournament](https://www.pychess.org/tournament/mL4gyHTZ)
[My last game in this tournament](https://www.pychess.org/j9fk1w0H)

I started tournament game when there wasn't much time left in the tournament. My game dragged on (more than 100 moves) and ended after the tournament time expired.
Although the game is labeled "Monthly Xiangqi Arena" and it's in the general PGN file of the tournament (Tournament -> Download all games), it didn't count in the tournament standings and I placed 4th instead of 3rd.

Screenshots:

1. This game in the my profile
![InkedArena_bug1](https://user-images.githubusercontent.com/47477833/175939759-6da52a83-a644-4e41-8c97-a74640dfef2a.jpg)

2. This game in the Tournament PGN file
![Arena_bug4](https://user-images.githubusercontent.com/47477833/175942894-3aec76ba-aa58-4431-84aa-08612052717c.png)
![Arena_bug2](https://user-images.githubusercontent.com/47477833/175940878-f435973e-7972-4bc1-bf0e-f57ab936c79d.png)

3. But it didn't count in the tournament standings
![Arena_bug3](https://user-images.githubusercontent.com/47477833/175941571-36f0d78c-c5d4-4b96-9ce2-8a19d2184526.png)

**Comment by Fulmene** [comment]
Not a bug. Games that finish after the tournament time limit don't count towards the standing. This is the same behaviour as Lichess.
