### ISSUE TITLE
Kyoto shogi notation

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#97]
Kyoto shogi notation is kind of off. I'm not aware of an official standard, but probably having the name using standard notation (P/R, L/T, K, G/N, S/B) and not using any promotion/demotion notation at the end would probably make the most sense.

**Comment by gbtami** [comment]
I think this issue should be moved to https://github.com/ianfab/Fairy-Stockfish/issues if you still think it needed :)
