### ISSUE TITLE
Suggestion: please add game phase to the analysis mode 

### ISSUE THREAD

**Issue by NelloHo** [gbtami/pychess-variants#973]
<img width="290" alt="image" src="https://user-images.githubusercontent.com/99171663/178148576-2df71a91-ca14-4c45-8add-06931e5cf7bb.png">

**Comment by gbtami** [comment]
This is rather problematic to define these terms in general for all variants. For example in drop variants endgame is almost unexistent. Possible this is the reason lichess doesn't use these markers in crazyhouse games. F.e. https://lichess.org/B6CMEYmz/white
