### ISSUE TITLE
Remove time limit for the first move for non-tourney games

### ISSUE THREAD

**Issue by visualdenniss** [gbtami/pychess-variants#976]
In Lichess there is no time limit for the first move when one is playing against AI or simply playing from lobby/challenge. Basically only in tournament play there is a time restriction for the first move. This applies to both registered users and also anon users (e.g. when they play against AI), so i d suggest implementing this practice to pychess as well, as one in some variants either needs to think more on first move, or move when ready in a match play or simply need to talk to his opponents before the game etc.

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/5f677edea906543d49b4401eee59e50c20124c97
