### ISSUE TITLE
Generate a new random board for 960 variants

### ISSUE THREAD

**Issue by notruck** [gbtami/pychess-variants#98]
The current behavior in 960 variants when players click on [Rematch] is to keep the same starting position from the last game. This does ensure fairness in the next game, where they get to replay the identical startpos, only with the colors reversed. To get a new random board, they have to go back to the lobby and create a new game from there. 

I think it is a GOOD THING for the site to remember the last startpos, until the players explicitly agree to generate a new board. Auto-generating new boards after 2 games (or even 4 or 6 games) may sound like a good feature, but people sometimes mis-click, games get aborted by accident and so on. It'll be quite frustrating not being able to properly restart a game with the right colors and the same random pos.

If they do not wish to continue, they can always return to the lobby and start over. 

But for some people, it seems to be a minor to moderate inconvenience, and I've seen some players complain about it in the chat. 

Would it be possible/viable to include a new button (or checkbox), which appear only in 960/random variants, which lets players choose between [Rematch with same board] or [Rematch with new board] ?

Thanks!

**Comment by notruck** [comment]
Would be a cool feature to have, as we anticipate more zh960 interest. :)

**Comment by gbtami** [comment]
I think auto-generating new boards after 2 games is what lichess doing in chess960.
This seems reasonable and most logical. New buttons may clutter the UI.
