### ISSUE TITLE
"Invalid Move" loss

### ISSUE THREAD

**Issue by Tech-Expert-Wizard** [gbtami/pychess-variants#981]
Another issue on "Invalid Move" loss was mentioned in #956, but it seems to be different.
**Exact URL where the bug happened**
I've seen several examples of games where one player lost because of this bug, e.g. https://www.pychess.org/8RTrB4Jf and https://www.pychess.org/jwNGFnfC and https://www.pychess.org/fA5Y8hLE
**Steps to reproduce the bug**
Click to a previous move during a tourney game. The bug seems to only happen during tournaments. I tested with a normal, non-tourney game and the bug doesn't occur.
**What did you expect to happen?**
The game should've proceeded normally.
**What happened instead?**
The player who clicked to a previous move during a tourney game lost by "Invalid move."
**Operating system and browser version**
Windows 10 and Firefox 102 (for the kyoto shogi game that I lost because of this bug; I don't know what OS or browser the other players are using), but I don't think this is relevant. It seems more like a server-side issue.

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/655e3be5a6ee6d5e8652bd5329671a2f683627ba
