### ISSUE TITLE
Add scrollbar to settings dialog

### ISSUE THREAD

**Issue by Fulmene** [gbtami/pychess-variants#987]
![image](https://user-images.githubusercontent.com/13796147/184209643-6a3c3450-8a06-4f3d-88dd-6a39c6998544.png)

**Comment by CSSandHTMLonly** [comment]
@Fulmene 
Does this PR fix what you asked for?
https://github.com/gbtami/pychess-variants/pull/1171

**Comment by gbtami** [comment]
Fixed via https://github.com/gbtami/pychess-variants/commit/891e6443d111d11916c363edd19f208c2a841177
